### ISSUE TITLE
Rename cpp-executable plugin to cpp-application plugin

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#103]
This plugin adds a convention for building a C++ _application_, for which one or more _executables_ and _packages_ are produced (or will be soon).

**Comment by big-guy** [comment]
PR: https://github.com/gradle/gradle/pull/3539
Waiting for https://builds.gradle.org/viewQueued.html?itemId=9413224

Once we have a new nightly, we can update the samples.  We shouldn't call this done until we've updated the samples.

**Comment by lacasseio** [comment]
The PR is merged, waiting for the nightly to update the samples.

**Comment by lacasseio** [comment]
The samples has been updated, closing as delivered.
