### ISSUE TITLE
Rename swift-executable plugin to swift-application plugin

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#104]
As per #103, for Swift.

**Comment by lacasseio** [comment]
- [ ] `cpp-executable` to `cpp-application`
- [ ] Update native-samples

**Comment by big-guy** [comment]
@lacasseio There's also #103 for the cpp renames.  We can do them both together if you'd like.

**Comment by lacasseio** [comment]
The sample has been updated, closing as delivered.
