### ISSUE TITLE
Support development lifecycle from Xcode with XCTest

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#108]
Allows developers to seamlessly transition from a Xcode-base build system to a Gradle-base build system without affecting their development lifecycle.

### Expected Behaviors
Gradle will generate Xcode projects allowing a developer to:
- Build and run test using the action button (See A)
- Build and run specific test using inline test button from the text editor
- View test results from the Test navigator (See B)

<img width="449" alt="screen_shot_2017-08-25_at_11_17_36_am" src="https://user-images.githubusercontent.com/22181740/29720202-2e4907f0-8987-11e7-9154-bb5aba75cbb3.png">

### Test cases
- [x] Build and execute test using `xcodebuild` through the CLI

**Comment by big-guy** [comment]
@lacasseio WRT "manually testing", is there a command-line equivalent of the button presses from Xcode that we could drive via a test fixture to sanity check that the generated xcode projects are usable?

**Comment by lacasseio** [comment]
I was going to add this as a separate item of work, but I think you are right to do the extra mile now and add some `xcodebuild` support now.

**Comment by adammurdoch** [comment]
From my point of view, a feature with no functional tests does not exist. We should really try hard to avoid stories where manual testing is the only testing we do. Otherwise, it's a spike not a feature.

**Comment by lacasseio** [comment]
You are right @adammurdoch, my mistake. I will look into having as many functional tests as possible through the CLI and `xcodebuild` as suggested by @big-guy.

**Comment by lacasseio** [comment]
I experimented a little bit with [SikuliX](http://sikulix.com/) and it seems we could create real acceptance test for Xcode for the features that aren't testable via `xcodebuild`. What's your thought about using such framework? We could automate scenario like "given a Xcode project, the user can execute all test using the test action button".

**Comment by big-guy** [comment]
I've used Sikuli.  Maintenance was too much of a burden, IMO. I think our xcodebuild fixture get us 80-90% of what we need.  We know we're generating working xcode project files and I think it's safe to rely on complaints from users if we somehow work from the command-line but fail from the IDE.

Since using Sikuli would require macOS build agents, I'd rather just have the macOS build agents and run our xcodebuild tests there.

**Comment by lacasseio** [comment]
Sounds good, moving this in done as all item assign to this epic has been delivered.
