### ISSUE TITLE
Incremental build for Swift

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#112]
As part of the work avoidance scenario, incremental compilation, and linking are a good candidate by only recompiling the changed files and relinking only when dependencies change.

### Expected Behaviors
Gradle is expected to take advantage as much as possible the incremental feature of `swiftc`.

### Test Cases
The test cases to support should be close to the one found in [AbstractNativeLanguageIncrementalBuildIntegrationTest](https://github.com/gradle/gradle/blob/master/subprojects/language-native/src/integTest/groovy/org/gradle/language/AbstractNativeLanguageIncrementalBuildIntegrationTest.groovy), and [AbstractNativeLanguageIncrementalCompileIntegrationTest](https://github.com/gradle/gradle/blob/master/subprojects/language-native/src/integTest/groovy/org/gradle/language/AbstractNativeLanguageIncrementalCompileIntegrationTest.groovy).

**Comment by big-guy** [comment]
Initial PR: https://github.com/gradle/gradle/pull/4226

I'm going to merge this and get the verification steps updated and follow up with more integration tests + perf test.

**Comment by big-guy** [comment]
Initial PR: https://github.com/gradle/gradle/pull/4226
Follow-up to fix flaky tests: https://github.com/gradle/gradle/pull/4228
Additional test coverage: https://github.com/gradle/gradle/pull/4239

@ghale would you like to take a look?

**Comment by big-guy** [comment]
@ghale I've addressed your comments here: https://github.com/gradle/gradle/pull/4256
