### ISSUE TITLE
Kotlin/Native support

### ISSUE THREAD

**Issue by gildor** [gradle/gradle-native#119]
Do you have any plans to support Kotlin/Native or collaborate with Kotlin/Native team to bring gradle-native plugins features not only for cpp and swift but for kotlin/native plugin as well?
Currently, they have own Gradle plugin `konan`, but I think that coordination of effort give benefits to Kotlin, gradle-native and users

**Comment by lacasseio** [comment]
Thanks @gildor for the question. We encourage you to use the [user forum](https://discuss.gradle.org) for such question in the future.

At the moment, support for Kotlin-Native is not on our roadmap. You are right to say that coordination between both efforts would be beneficial for everyone and we hope to achieve this in the future.

**Comment by adammurdoch** [comment]
Something that _is_ on our roadmap, however, is to make it easy for a plugin outside of Gradle core to extend the native support. This might mean, for example that a kotlin-native plugin could contribute native binaries that are then used by the core plugins say to publish or use as a tool for some build task or linked into another binary as a library or packaged into an rpm whatever.
