### ISSUE TITLE
Clean up VisualStudio 2015 support

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#120]
As a user, I want to be able to use the Windows 10 SDK that is installed with VS2015.  I also want to the include and lib paths for VS2015 to only contain the paths necessary.

## Implementation Notes
- https://discuss.gradle.org/t/windows-10-sdk-cant-be-configured-gradle-4-1/23894

## Not Covered
- Any sort of additional modeling around runtime libraries or sdks (i.e. this work is only to get the detection/usage working the way a user would expect).
- Any method of declaring a dependency on the runtime libraries or sdks beyond simply setting the location on the toolchains as is currently supported with older versions.

## Test Cases
- Visual Studio tool chain detects and uses the Windows 10 SDK libraries when present.
- User can explicitly specify the location of Windows 10 SDK.

**Comment by ghale** [comment]
After actually playing with this some, I think the part of this story that deals with the extra include and lib paths is not actually an issue (or rather, these paths are not as superfluous as originally thought).

[This doc](https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx) talks about the runtime libraries for VisualCpp in a little detail.  After re-reading it several times and playing with it, I think I have a better understanding of how the VS2015+ toolchain works.  Basically, when linking it needs three distinct libraries: a runtime library (`libucrt.lib` and friends), a runtime initialization library (`libcmt.lib` and friends), and potentially an implementation-specific library (i.e. `libvcruntime.lib` and friends).  The first is in the UCRT, the second two are in the `VC\lib` dir.  I think you can get away without the implementation-specific library if you don't use any of the extended library functions, but you'll always need the runtime initialization library.  Additionally, if you include a standard C++ header, you'll also need a standard C++ library (i.e. `libcpmt.lib` and friends) which are also in the `VC\lib` dir.

What this means is that we will always need the `VC\lib` because we'll always need the runtime initialization libraries.  Additionally, we'll always need the `VC\include` when compiling C++ sources that include any of the standard C++ header files (e.g. `iostream`).  So including these directories on the header and lib path are necessary to cover all of the toolchain scenarios.  

We could potentially model this at some point such that the include dir was not present in a scenario where it wasn't needed (e.g. compiling C sources, no references to extended library functions), but this would fall into the category of further modeling that we decided we would not do as part of this story.

**Comment by adammurdoch** [comment]
I think for this issue it's ok to expose too much stuff. We should aim for something like the following:

1. I can write an exe or lib that uses the standard C libraries, and Gradle finds the right headers and libraries at compile and link time, and I can run the exe.
2. I can write an exe or lib that uses the windows API, and Gradle finds the right headers and link path, and I can run the exe. Gradle may need me to list some libraries as linker args in this case (eg `user32.lib`) but not where they live.
3. I can write an exe or lib that uses the standard C++ libraries, and Gradle finds the right headers and libraries at compile and link time, and I can run the exe.

- Standard C libraries == something like `#include <stdio.h>` and `printf()`
- Standard C++ libraries == something like `#include <iostream>` and `std:cout`
- Windows API == something like `#include <windows.h>` and `WriteFile()`

**Comment by adammurdoch** [comment]
Later, we can bust these up into the 3 pieces and get you to declare which pieces you need.

**Comment by ghale** [comment]
@lacasseio You can see the current state of windows 10 sdk support at https://github.com/gradle/gradle/pull/2901.  I'll continue to polish this some, but I'd appreciate any feedback.  One thing I did is break the windows 10 stuff (ucrt, windows sdk, etc) into a separate common locator pattern instead of adding more complexity to the existing `WindowsSdkLocator`.  The `DefaultWindowsSdkLocator` is now a wrapper for the various types of locators that we might have for windows sdks and simply establishes a precedence for the locators.  We should probably also bust up the legacy locator and have a separate locator for the windows 8 style installations to simplify this some more (we might be able to use the `WindowsKitComponentLocator` for this in some way).  But this is probably outside the scope of this story.

With respect to the test cases that adam listed above, I feel like we have this covered with `CHelloWorldApp` (1), `CppHelloWorldApp` (2), and `WindowsResourceHelloWorldApp` (3) and the existing toolchain tests.  As discussed in our standup, what we don't have is any testing for different windows sdks (i.e. windows 8 vs windows 10).  We do test visual studio versions, but then each toolchain just uses a `WindowsSdkLocator` to find the latest windows sdk available (which will be windows 10 sdk once it is installed).  I think we should have at least one test that uses each locatable windows sdk and validates that we have coverage for older sdk versions.  I'm going to add something for this before I call this story complete.

**Comment by ghale** [comment]
This has been merged.
