### ISSUE TITLE
Add cygwin64 CI coverage

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#127]
The current model C++ plugins work fine with cygwin64, but we have no CI test coverage for this.

**Comment by big-guy** [comment]
We should consider how this might break `release` and try to avoid breaking it.

**Comment by big-guy** [comment]
We want to add `cygwin` and re-enable the tests that have been disabled for it.

We should get with Donat and coordinate an install on one agent and test there first.

**Comment by ghale** [comment]
So it appears that gcc on cygwin64 builds for 64-bit, but does not cross-compile to 32-bit.  There is a package that can be installed for cygwin64 to do 32-bit compilation, but it requires you to call a separate executable altogether (i.e. "-m32" is not enough).  Alternatively, you can install cygwin32 and cygwin64 side-by-side (again calling separate executables based on architecture).  See [here](https://superuser.com/questions/845507/can-cygwin-64-bits-compile-32-bits-sources) and [here](https://stackoverflow.com/questions/30119573/compile-32bit-code-from-cygwin64) for background discussion.  My understanding is that there's a similar process with mingw as well.

So there are a couple of directions we can go with this:

1. Only discover the 64-bit cygwin toolchain in our test infrastructure and only run 64-bit tests (tests that require 32-bit or 32 and 64-bit toolchains will be ignored).  
1. Install and discover both 32-bit and 64-bit cygwin toolchains and treat them as multiple versions (i.e. we test only 64-bit with platform jobs and both with allVersions jobs).  In this case, we'd get coverage for 32-bit-only and 64-bit-only, but not 32-and-64-bit tests.
1. Install both 32-bit and 64-bit cygwin but configure them as a single custom toolchain.  We'll configure the 32-bit executable for 32-bit binaries and the 64-bit executable for 64-bit binaries.
1. Variation of the above - install only 64-bit cygwin with the 32-bit support and configure the toolchain to use the 32-bit executable when building 32-bit binaries.

I'm inclined to do 3 for now.  I think this gives us a good bit of flexibility, allows us to test both architectures with cygwin, and allows us to eventually remove the 32-bit complexity from our test infrastructure (once mingw 64 bit is installed on the CI machines, too).  The downside is that this would be testing a somewhat non-standard configuration (i.e. the vast majority of users probably would not be customizing the toolchain in this way and would probably only build 32-bit or only build 64-bit).  Thoughts?

**Comment by big-guy** [comment]
+1 on option 3, but if we have trouble with some of our tool chain discovery/system include discovery, we should consider how to fix this properly in Gradle.

**Comment by ghale** [comment]
Yeah, I think a follow up issue here would be to try to discover and handle the different compilers implicitly similar to how visual studio handles it (but hopefully with less complexity).

**Comment by ghale** [comment]
I ended up going with option 4. Cygwin64 with 32-bit support has been installed on all the CI machines (along side the cygwin32 install, which is still needed in the short term for supporting the release branch).

PR: https://github.com/gradle/gradle/pull/8111

**Comment by lacasseio** [comment]
I left a review on the PR. It's mostly questions that may result in some change.
