### ISSUE TITLE
The XCTest plugin should not fail on apply on an unsupported operating system but should instead fail only when attempting to build the tests

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#128]
It should be possible to run `gradle tasks` for a build that uses the `xctest` plugin on any platform, but it should be an error to run `gradle test` on an unsupported platform.

**Comment by lacasseio** [comment]
Tasks that require specific tools that may not exist on the system could be skipped if it makes sense. For example, `CreateSwiftBundle` could be skipped `onlyIf { swiftStdlibToolLocator.find() != null }`.

**Comment by lacasseio** [comment]
The following test case should be working:
- [ ] Apply `xctest` plugin on non-macOS system doesn't crash the build
- [ ] Can run the `tasks` task successfully on non-macOS system when `xctest` plugin is applied
- [ ] Running `test` and `check` tasks won't execute `xctest` tasks

Everything else is out of scope for this issue which is returning a meaningful error message when explicitly invoking the link and `xctest` tasks.
