### ISSUE TITLE
XCTest plugin should not require an Info.plist file to be present

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#134]
Currently, building the test suite will fail when an `Info.plist` file is not present in `src/test/resources`. Adding an effectively empty `Info.plist` allows the tests to run, however an empty file adds no other value.

Instead, the plugin should handle a missing `Info.plist` and provide a stub to allow the tests to run.

**Comment by lacasseio** [comment]
This is currently in review in PR https://github.com/gradle/gradle/pull/3004.

**Comment by lacasseio** [comment]
There are 2 issues that split through the last PR:
- [ ] Missing `Info.plist` should not be included in Xcode projects
- [ ] Missing `Info.plist` should not crash the build
