### ISSUE TITLE
4.1 regression: working directory when linking

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#139]
In 4.0, directly adding linker args with relative paths worked when the path was relative to the project directory:

```
linker.args "-Lbuild/path", "-lsomething"
```

In 4.1, this fails to find the `something` library.  

I suspect https://github.com/gradle/gradle/commit/81319fd6faf8fd6f9659e0fb1090a88a2f3dcadb#diff-dbff81faa3548c2a1967fc628db6ce38R45 changed the behavior of our linking task to use a working directory relative to the output file.

**Comment by adammurdoch** [comment]
It would be better if the working directory is not part of our public contract, so we can make it whatever we like based on toolchain, caching strategy, etc. So, we might instead guarantee to interpret linker/compiler args relative to the project directory.

**Comment by big-guy** [comment]
Yep, it would also be better if the "extra things to link" were specified in some way that we would understand how to build the appropriate command-line automatically instead of using raw linker arguments.  I think that helps our caching story too.  Raw arguments that could contain absolute paths would kill caching.

**Comment by lacasseio** [comment]
This has been fixed and will be in Gradle 4.3.
