### ISSUE TITLE
Install Swift toolchain on linux CI machines

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#14]
@adammurdoch commented on [Tue May 30 2017](https://github.com/gradle/stable-native/issues/29)

We will need to be able to test the Swift support on CI, so let's get the Swift toolchains installed on the linux build VMs.

---

@pioterj commented on [Wed May 31 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-305104939)

@donat could probably help with this.

---

@donat commented on [Wed May 31 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-305114392)

I added the task to the dev-infrastructure backlog. Can somebody guide me or send me a good tutorial how to set up the Swift toolchain?

---

@donat commented on [Wed May 31 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-305114954)

Also, what is the urgency here? Is there a deadline, or should I treat this task with a lower priority?

---

@lacasseio commented on [Wed May 31 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-305298061)

@donat We are looking at getting a minimal Swift compilation done in the coming week. We could disable the test on CI. I would be useful if we could take advantage of the CI though. I can help with this but I need information on where we should untar the Swift toolchain on the Linux CI machines.

@pioterj Could you give some guidance on the priority.

---

@adammurdoch commented on [Wed May 31 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-305301254)

It would be good to have some kind of CI tests running in the next week or so.

Another potential option is to add some mac os machines to the CI pool, which we also should do at some point.

---

@donat commented on [Fri Jun 02 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-305814502)

I'll try installing the swift toolchain on the CI machines on Tuesday (Monday is a holiday here). 

---

@donat commented on [Tue Jun 06 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-306499519)

Swift is now installed on the Linux build machines, see https://github.com/gradle/dev-infrastructure/issues/108.

---

@lacasseio commented on [Mon Jun 12 2017](https://github.com/gradle/stable-native/issues/29#issuecomment-307821740)

See [slack discussion](https://gradle.slack.com/archives/C31L7J0P8/p1497077136732999) for more information on the little issue we had with Swift toolchain installation on Linux CI.

**Comment by lacasseio** [comment]
CI test seems to be all passing so I will close this issue for now.
