### ISSUE TITLE
Publish metadata that describes the available files of a C++ library

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#143]
Generate and publish a Gradle specific metadata file to the Maven modules produced by the `maven-publish` and `cpp-library` plugins, to describe the files that make up the library.

Currently, only a `pom.xml` is generated. While this can be used to describe the dependencies of the library, to some degree at least, it does not describe the files. This has some implications:

- The consumer has to perform multiple resolves of a given set of dependencies, first to calculate the graph and a second time to find the artifacts. This is inefficient and is opaque to the reporting that we have and other build logic, including . The subsequent resolves are not visible to build scans (but this is really https://github.com/gradle/dotcom/issues/97). Resolving the runtime libraries for a component requires 3 resolves.
- The consumer has to make assumptions about which files are available, which mean it cannot deal well with static, header-only, symbol-only or resource-only libraries.

This story adds a Gradle specific metadata file that is published along side the `pom.xml` to provide extra metadata.

Implementation:

- [x] Add generation task only for C++ libraries for this story.
- [x] Metadata includes api, link and runtime variants.
- [x] For each variant, list file name, url, size and hash.
- [x] Add internal flag to enabled resolving using the metadata
- [x] Fetch metadata after fetching pom
- [x] Each variant listed in metadata is treated as variant of 'runtime' scope.
- [x] Remove some hackery from C++ plugin
- [x] Public design docs describe the format.

Test cases

- [x] Metadata file is generated for a Maven publication
- [x] Metadata file is generated for published C++ libraries and applications

**Comment by adammurdoch** [comment]
The changes to generate the first version of the metadata file are in master. The file isn't used yet, that's next.

**Comment by eljobe** [comment]
Specifically, those commits were:
https://github.com/gradle/gradle/compare/b279815977e0...b76067a5183e

**Comment by adammurdoch** [comment]
This is blocked on https://github.com/gradle/gradle/issues/3009

**Comment by adammurdoch** [comment]
This is done enough. Split out https://github.com/gradle/gradle/issues/3267 as something to fix later.
