### ISSUE TITLE
Swift source files should be recompiled when a library it uses changes

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#144]
When I have a Swift component A that depends on a library B, when I change the source of the library B, then the source of A is not recompiled, but should be.

The Swift compile task does not consider the module files of its dependencies as inputs, meaning changes to the module files are ignored on later execution. Instead the source should be recompiled when one of the module files it uses changes.

**Comment by eljobe** [comment]
This is specifically for when an ABI change is made to library B. If some implementation detail of library B changes, the compilation of B will not result in a different B.swiftmodule, and so, A needs not be recompiled. Correct? (I'm basing this on the behaviors observed when building with SwiftPM)

**Comment by lacasseio** [comment]
That sounds about right. Assuming we aren't mistaking, we should test these scenarios:
- [ ] Non-ABI change of a source file of library B does not recompile component A
- [ ] ABI change of source file of library B recompile component A

### Open Questions
- Do we consider a change to a file and adding/removing a file when testing ABI/non-ABI change equivalent? Putting it differently, do we need to test for modification, adding, and removing a file or simply one of the three is good enough for our test coverage?

### Out of scope
- [ ] Adding a new public method/class in library B doesn't recompile component A
- [ ] Removing a public method/class in library B recompile component A
   - This last one could go deeper and recompile component A only if it was used which is a bit more tricky

**Comment by adammurdoch** [comment]
For this issue, we should care about correctness rather than performance. So, we should recompile A when an ABI change is made to B, in the simplest way possible. If we also happen to recompile A when a non-ABI is made to B, that is also fine for this issue. We should split out compile avoidance (don't recompile when there's no ABI change) as a separate feature to do later. Without the correctness fixes in this issue, our Swift support is unreliable and basically not usable in practice. Without compile avoidance, it's not as good but at least still works.

> Adding a new public method/class in library B doesn't recompile component A

We should in fact recompile A in this case, as adding a new class or function can lead to compilation failures in A. For example, the new class may now collide with a class of the same name in another module used by A, or may cause A to accidentally and incorrectly override a function in a subclass it uses from B, or ...

Until we know the language much better, we should avoid trying to be too clever with compile avoidance, and simply start with recompiling A on any _visible_ change in B.

**Comment by lacasseio** [comment]
Thanks for your input Adam, it makes sense to split this into two issues.

**Comment by big-guy** [comment]
This seems to be working, I added some coverage: 

https://github.com/gradle/gradle/pull/3529

**Comment by big-guy** [comment]
@eljobe could you take a look at this?

**Comment by eljobe** [comment]
Reviewed. I'm happy with this change. Thanks for picking this up.
