### ISSUE TITLE
Xcode delegate clean action to Gradle

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#153]
The Xcode clean action isn't properly passed to Gradle. Given the fact that Xcode has no knowledge of the intermediate files generated by Gradle, Xcode cannot clean a project properly.

### Expected Behavior
Xcode should delegate the clean action to Gradle in order to perform a proper clean.

### Open Questions
* Should Gradle perform cross-cutting clean, meaning only cleaning the files for a specific component, or should it clean the entire project (i.e. `gradle :project:clean`)?
* Should Gradle tries his best at cleaning the intermediate files from Xcode derived data directory such as `$BUILT_PRODUCTS_DIR`?

### Test Cases
- [ ] Invoking clean in Xcode should invoke the right clean task in Gradle
- [ ] Files are correctly deleted
- [ ] Clean action on already clean project should succeed

**Comment by big-guy** [comment]
PR https://github.com/gradle/gradle/pull/3301
