### ISSUE TITLE
Users can append compiler arguments current list

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#156]
As complexity evolves, sometimes a user only wants to add more compiler arguments as opposed to replacing them. As some compiler arguments are lazily evaluated, we want to avoid evaluating the arguments when we decide to add more arguments.

### Expected Behavior
Users can add additional arguments to the current list of arguments without triggering the evaluation of the arguments.

### Test Cases
- [x] Can add an argument without causing the previous arguments to be evaluated (a `Provider` value used as an argument changes after an argument is added should use the last value)
- [ ] Increases the argument count when a new one is added

**Comment by lacasseio** [comment]
One proposition I have is to add to `ListProperty` method such as `add` and `addAll`.

**Comment by big-guy** [comment]
Would that be like this?
```
void add(Provider<? extends T> provider);
void addAll(Provider<? extends Collection<T>> provider);
```

And you would use it something like...
Instead of this:
```
final List<String> currentCompilerArguments = compile.getCompilerArgs().getOrElse(Collections.<String>emptyList());
compile.getCompilerArgs().set(project.provider(new Callable<List<String>>() {
    @Override
    public List<String> call() throws Exception {
        File frameworkDir = new File(sdkPlatformPathLocator.find(), "Developer/Library/Frameworks");
        return Lists.newArrayList(Iterables.concat(
            Arrays.asList("-g", "-F" + frameworkDir.getAbsolutePath()),
            currentCompilerArguments));
    }
}));
```

Do this:
```
compile.getCompilerArgs().addAll(new Callable<List<String>>() {
    @Override
    public List<String> call() throws Exception {
        File frameworkDir = new File(sdkPlatformPathLocator.find(), "Developer/Library/Frameworks");
        return Arrays.asList("-g", "-F" + frameworkDir.getAbsolutePath());
    }
});
```

And instead of:
```

final List<String> currentCompilerArguments = compileDebug.getCompilerArgs().getOrElse(Collections.<String>emptyList());
compileDebug.getCompilerArgs().set(project.provider(new Callable<List<String>>() {
    @Override
    public List<String> call() throws Exception {
        return Lists.newArrayList(Iterables.concat(
            Arrays.asList("-enable-testing"),
            currentCompilerArguments));
    }
}));
```

You would do:
```
compileDebug.getCompilerArgs().add(project.provider(new Callable<String>() {
    @Override
    public String call() throws Exception {
        return "-enable-testing";
    }
}));
```

There might be good reasons to provide convenience methods for `add(T)` and `addAll(List<T>)` too.

**Comment by lacasseio** [comment]
Right now, I'm toying with the following which is really similar to what you have:
```
public interface ListProperty<T> extends PropertyState<List<T>> {
    void add(T item);
    void add(Provider<? extends T> item);
    void addAll(List<? extends Provider<? extends T>> items);
}
```

Which allows things like:
`compile.getCompilerArgs().add("-parse-as-library");`

and

```
compile.getCompilerArgs().addAll(Lists.newArrayList(Providers.of("-g"), providers.provider(new Callable<String>() {
    @Override
    public String call() throws Exception {
        File frameworkDir = new File(sdkPlatformPathLocator.find(), "Developer/Library/Frameworks");
        return "-F" + frameworkDir.getAbsolutePath();
    }
})));
```

**Comment by lacasseio** [comment]
I'm moving forward with @big-guy proposition as it feels better aligned with the interface.

**Comment by adammurdoch** [comment]
Another approach is to add 'map in place' methods to `PropertyState`, something like:

```
interface PropertyState<T> {
    // applies the given mutation to the value of this property, when the value is queried
    void transform(Action<T> mutator);
}

compile.getCompilerArgs().transform(l -> l.add('-F' + someDir))
compile.getCompilerArgs().transform(l -> l.remove('-something-i-dont-want'))
```

**Comment by big-guy** [comment]
Do the `add`/`addAll` methods preclude the 'map in place' idea or make it harder to implement?

Should we keep adding these other methods or only add 'map in place'?

**Comment by adammurdoch** [comment]
I would go with the 'add' methods for now. This better matches the intent of the use case I think. The 'map in place' methods are the get-out-of-jail methods for when you (the build logic author) need to do something with the entire result after it has been configured and before it is used.
