### ISSUE TITLE
Support for generated sources

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#166]
Allow C, C++, Objective-C source and header files and Swift source files to be generated prior to compilation and IDE import. Support generated test source files.

**Comment by big-guy** [comment]
This currently works for sources generated within a project, but fails for generated public headers across projects.

**Comment by lacasseio** [comment]
See #994 for the generated public headers. This issue should tie up whatever is missing to support generated sources such as reviewing all open issues on the board to either close them, prioritize them or write more sample to demonstrate.

**Comment by lacasseio** [comment]
I find the current approach (aka using `ConfigurableFileCollection`) to be satisfying for solving this roadmap item. There's a [bug](https://github.com/gradle/gradle-native/issues/994) and addressing it will not change the direction for supporting generated sources. Let's close this issue, fix issue #994 as a bug fix and open new issues with specific use-cases that we may have missed with this feature.

**Comment by lacasseio** [comment]
Both [Swift](https://github.com/gradle/native-samples/tree/master/swift/source-generation) and https://github.com/gradle/native-samples/tree/master/cpp/source-generation have samples showing how to generate sources.
