### ISSUE TITLE
Build C++ projects with source dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#182]
This should have a sample in native-samples

**Comment by big-guy** [comment]
@eljobe could you take a look at this?

**Comment by big-guy** [comment]
Fails on Windows due to a long file path (>300 characters):
https://builds.gradle.org/viewLog.html?buildId=8644536&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_languageNative

:(

**Comment by big-guy** [comment]
I'm not sure what we should do about this.

The paths on CI are way over the limit.  This is ~300 characters (I think the C:\ don't count):
> C:\tcagent1\work\6031ced305d8bea4\subprojects\language-native\build\tmp\test files\CppDependenciesIntegrationTest\can_depend_on_C___l..._from_VCS\cla6j\.gradle\vcsWorkingDirs\3j106tklsik3q9jsnzaf5obc2\114d2253a10f763e1138e11c31e17b3e600f456f\log\build\obj\main\debug\bf0q611b80li3hv48z24l97tm\logger.obj

To get to just under 260, we could flatten the hierarchy again.  Instead of `vcsWorkingDirs/<repo>/<commit>`, we just do `vcsWorkingDirs/<repo+commit>`.  We can save a few characters by changing `vcsWorkingDirs` to just `vcs`.  

We could move the working directory to the GRADLE_USER_HOME.  That's likely to be on a shorter path, but it may have other problems (slower/mounted over NFS, need to worry about concurrent builds).

Alternatively, we could keep the repo id and shorten `vcsWorkingDirs` and substitute the commit id to some internal mapping, e.g., `vcs/<repo>/<mapped commit>` where <mapped commit> would be ~single characters.  I think I'm partial to this idea.  WDYT @eljobe ?

**Comment by adammurdoch** [comment]
This is more a problem with the C++ compile task (or the tool chain really). I would fix that instead of using an artificial location for the vcs working dir.

**Comment by big-guy** [comment]
The path that we're choosing right now only leaves 22 characters left for the build in our test, so even if we put the obj files directly into `build`, we wouldn't fit.

Or to put it another way, 90/260 characters are due to the way we choose the VCS working directory.

**Comment by adammurdoch** [comment]
This doesn't have anything to do with source dependencies. I can manually check out the same source into a directory whose path has the same length and run into the same problem. And this will keep happening to me even if we change what we happen to use for the working directory for source dependencies.

Instead of changing where we check things out to, we should fix the C++ plugin so that it works for projects that are deeply nested on the file system. For example, we can invoke `cl.exe` in the project directory and use relative paths to point to things.

**Comment by big-guy** [comment]
I took a stab on my branch to use relative paths in more places: https://github.com/gradle/gradle/pull/3144

It's not complete.  Lots of unit tests fail since I need to pass around a working directory everywhere and there seems to be something special going on with the PCH integration tests, but it shows a few problems:

- If the path to the working directory is over 260 characters, the compiler won't even start (it'll complain the path is too long).
- If the working directory + path to a file is over 260 characters, the compiler complains the file doesn't exist.

Here's some of the failures:
https://builds.gradle.org/viewLog.html?buildId=8750150&

To confirm this, I tried running the compiler by hand from a directory just under the path limit with a file that was under the path limit (`m.cpp`) and one just over it (`main.cpp`).  You can see that the `m.cpp` compiles (but fails to link for other reasons) and `main.cpp` is reported not found.

![image](https://user-images.githubusercontent.com/5387972/31586784-1ae78836-b1a4-11e7-820d-3b46204ee567.png)

I think making the paths relative (and the working directories for all the tools consistent) would be a good idea, but I'm going to create a new issue for that.

To just get the test coverage working again, I shortened the path by reducing the length of the test name and switching over to the non-Git VCS backend.  See https://github.com/gradle/gradle/commit/e8b69d267dde8e3f6533e850e675e18885a2e95c

**Comment by big-guy** [comment]
Relative path issue is #218
