### ISSUE TITLE
Investigate why build-scan plugin misbehaves with source dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#189]
This assumes you have the gradle/gradle build-scan init script in ~/.gradle/init.d

```
git clone https://github.com/gradle/native-samples
cd cpp/source-dependencies
./gradlew build --scan
```

This explodes with

```
A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://e.grdev.net/help and include the following via copy/paste:

----------
Gradle version: 4.4-20171007063318+0000
Plugin version: 1.9

java.lang.IllegalStateException: Root project has not been attached.
        at org.gradle.invocation.DefaultGradle.getIdentityPath(DefaultGradle.java:112)
        at org.gradle.invocation.DefaultGradle_Decorated.getIdentityPath(Unknown Source)
        at org.gradle.configuration.ConfigurationTargetIdentifier$3.getBuildPath(ConfigurationTargetIdentifier.java:125)
        at org.gradle.configuration.BuildOperationScriptPlugin$OperationDetails.getBuildPath(BuildOperationScriptPlugin.java:122)
        at com.gradle.scan.plugin.internal.a.n.e.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.c.e.run(SourceFile:62)


java.lang.IllegalStateException: Root project has not been attached.
        at org.gradle.invocation.DefaultGradle.getIdentityPath(DefaultGradle.java:112)
        at org.gradle.invocation.DefaultGradle_Decorated.getIdentityPath(Unknown Source)
        at org.gradle.configuration.ConfigurationTargetIdentifier$2.getBuildPath(ConfigurationTargetIdentifier.java:105)
        at org.gradle.configuration.BuildOperationScriptPlugin$OperationDetails.getBuildPath(BuildOperationScriptPlugin.java:122)
        at com.gradle.scan.plugin.internal.a.n.e.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.c.e.run(SourceFile:62)


java.lang.IllegalStateException: Root project has not been attached.
        at org.gradle.invocation.DefaultGradle.getIdentityPath(DefaultGradle.java:112)
        at org.gradle.invocation.DefaultGradle_Decorated.getIdentityPath(Unknown Source)
        at org.gradle.configuration.ConfigurationTargetIdentifier$3.getBuildPath(ConfigurationTargetIdentifier.java:125)
        at org.gradle.configuration.BuildOperationScriptPlugin$OperationDetails.getBuildPath(BuildOperationScriptPlugin.java:122)
        at com.gradle.scan.plugin.internal.a.n.e.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.c.e.run(SourceFile:62)


java.lang.IllegalStateException: Root project has not been attached.
        at org.gradle.invocation.DefaultGradle.getIdentityPath(DefaultGradle.java:112)
        at org.gradle.invocation.DefaultGradle_Decorated.getIdentityPath(Unknown Source)
        at org.gradle.configuration.ConfigurationTargetIdentifier$2.getBuildPath(ConfigurationTargetIdentifier.java:105)
        at org.gradle.configuration.BuildOperationScriptPlugin$OperationDetails.getBuildPath(BuildOperationScriptPlugin.java:122)
        at com.gradle.scan.plugin.internal.a.n.e.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.c.e.run(SourceFile:62)
```

**Comment by big-guy** [comment]
I've pinged Rene about this, but he won't be able to look at it until next week.

**Comment by eljobe** [comment]
@big-guy, it looks to me like the Build Scan Plugin is just reading the `includedBuilds` from the `Gradle` instance to determine if it is a composite build. Didn't we introduce a separate place that our implicitly included builds are registered as they are discovered? I bet if we patch the plugin to look there too, we'll start getting the same behavior.

See:
https://github.com/gradle/dotcom/blob/ce27d73e41f3e68206222cf7a285c57e4206499b/scans-plugin/src/main/java/com/gradle/scan/plugin/BuildScanPlugin.java#L306

**Comment by big-guy** [comment]
@eljobe The check happens too early.  It's when the plugin is being applied and we won't know that we have implicitly included builds until much later (after interesting things have happened that the build scan plugin would want to collect).

The build scan plugin could ask "could the build possibly have included builds?" by checking if there are any VCS mappings and disable itself accordingly.  I think that would be temporary until the build scan plugin supports composite builds.

**Comment by eljobe** [comment]
I think that makes a lot of sense. But, maybe we should run the proposal by the GE team? Can you send that email?

**Comment by big-guy** [comment]
I opened an issue on their board yesterday about this and tagged @breskeby about it.

I added a comment just now that suggests that we temporarily disable the build scan plugin if we detect there *could* be included builds from a VCS mapping

**Comment by eljobe** [comment]
I just had a crazy idea about this one. What if, when running the settings script, if we notice a `vcsMapping`, we insert a "placeholder" `includeBuild` that doesn't do anything special, but it tricks the Build Scan Plugin into thinking that it's a composite build. Then, very early in dependency resolution, we could just remove the "placeholder"?

The main reason I'm even suggesting this, is so that it would work for existing versions of the Build Scan Plugin. Maybe it's not a big deal though. We have some time before we're going to be recommending using source dependencies.

**Comment by adammurdoch** [comment]
I wouldn't bother trying to trick the build scan plugin. Instead, we should increment min supported build scan plugin version to a version that doesn't blow up.

**Comment by eljobe** [comment]
And until such a version exists, just keep blowing up? (I'm cool with it, just wanted to make sure I understand your suggestion.)

**Comment by adammurdoch** [comment]
Exactly right.

Looking at those stack traces again, it look like an issue in the build tool to me though.

**Comment by adammurdoch** [comment]
Definitely an issue in the build tool. Those build operations shouldn't be firing without us assigning an identifier to the implicitly included build.

**Comment by eljobe** [comment]
@adammurdoch, for my understanding, isn't this also true for composite builds? In other words, shouldn't the build tool be creating identifiers for the *explicitly* included builds as well?  I wonder if this may be one of the things that the core team is already working on to help the build scan plugin work with composite builds?

**Comment by big-guy** [comment]
There could be an underlying issue with composite builds that is masked because the build scan plugin bails out early when using composite builds.

**Comment by big-guy** [comment]
Yeah, I think there's something wrong with what we're doing when applying either init scripts or settings.gradle and expecting to get a identifier for the build operation.

I think this is something we can fix, but I think we should still talk to Rene next week (or the week after) so GCS knows what's going on.

**Comment by big-guy** [comment]
Here's a stab at fixing the build operations generated: https://github.com/gradle/gradle/pull/3171

Basically, we were always assuming we could get the "identity path" of a Gradle instance (which was based on the root project name and build hierarchy).  For `ApplyScriptPluginBuildOperationType`'s generated for projects, the root project would be configured.  For `ApplyScriptPluginBuildOperationType`s generated for Settings (a settings file) or Gradle (an init script), this only worked for the outermost build because we special case the build with no parent as having the build path `:`.  Included builds would not have a root project set for either of these build operations, so we couldn't determine the identity path for them.

With the change, we set the root project's name just before the settings file is evaluated and again after it has been evaluated (in case it's changed).

**Comment by adammurdoch** [comment]
For included builds, we can assign an identity as soon as we know about the build, before we run _any_ build operations on that build. We do the same thing for projects as soon as we know about them.

For explicitly included builds, the identity can be based on directory passed to `includeBuild()` and we can later offer ways to override this at that point.

For implicitly included builds, the identity can be based on the component identifier.

Once the identity of a build is consumed by something, e.g. when it is exposed via a build operation, it should never change again. So settings the root project name and then _changing_ the name later is out as a solution.

**Comment by big-guy** [comment]
There are three build operations that have a `ConfigurationTargetIdentifier` that we care about:

- `ApplyScriptPluginBuildOperationType` for `Project`s (for `build.gradle` and scripts applied from there)
- `ApplyScriptPluginBuildOperationType` for `Settings`s (for `settings.gradle` and scripts applied from there)
- `ApplyScriptPluginBuildOperationType` for `Gradle`s (for init scripts)

The `ConfigurationTargetIdentifier` has a `getBuildPath` that should return the path to the build.  This is the same kind of path used for `BuildIdentifier`.

There are five types of builds that have these build operations:

- The root build
- `buildSrc`
- An explicitly included build
- An implicitly included build
- A `GradleBuild` build

We special case the root build and always give it the path `:`, so it never has a problem finding its build path or changing its path.  All of the other builds are considered nested builds and should behave similarly to one another.

For project build scripts, things work because the build path is determined before any build operations are created.
For settings files and init scripts, all of the nested builds have a problem because they currently determine their build path based on their root project name, which isn't added until after settings and init scripts have been evaluated.

At some point, we must have run across this problem in `buildSrc` and added this assumption (directory name == root project name) for included builds:
https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java#L141-L146

I think it makes sense to change `buildSrc` and explicitly included builds to use their directory names as their build paths. This can be locked in early enough and prevented from changing.

Implicitly included builds can do the same for now, since we assume the included build from VCS is a single project and in the root of the repository.

That only leaves us with `GradleBuild` builds.  We haven't had any restrictions/assumptions on the name of the build or the root project name when used from `GradleBuild`. To make all nested builds consistent, I think we have to assume the same thing (directory name == root project name).  The other choice would be to use a `GradleBuild`'s task name.

I've started down that path with the current PR.  When we create a nested `DefaultGradle`, I assign it a build name based on the root directory.

WDYT?

**Comment by adammurdoch** [comment]
Sounds good.

I think later we might split the identifier into some synthetic id (eg an integer) that we can assign early to the build before we know anything about it, and some more stable path-like id that we calculate after we've run the settings script for the build. Nothing we need to do now though.

**Comment by big-guy** [comment]
It looks like we have some tests that rely on being able to configure the build id from the root project name:
https://builds.gradle.org/viewLog.html?buildId=8733218&

If I force the build id to be derived from the directory name for included builds, this effects the identifier for all projects too:
https://github.com/gradle/gradle/blob/1d3fa8aab141cf76381740602301be0751f7fb0c/subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java#L530

Thoughts on how this should be working?

**Comment by big-guy** [comment]
I think we should punt on this for now.  We know why the build-scan plugin misbehaves and it's not something special to source dependencies. We're going to have the same problem with composite builds in general.

The GCS team is going to disable the build-scan plugin if they detect there are VCS mappings, which is probably "good enough" for now.
