### ISSUE TITLE
Emit sensible errors for missing settings scripts

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#190]
As a build developer, I want Gradle to emit a clear error message indicating that the external source dependency I am attempting to use does not contain a required settings script, so I don't have to understand some cryptic stack trace to know how to fix the situation.

**Comment by eljobe** [comment]
@big-guy, I am looking at the bullets on this issue, and I feel like the 5th one, "Missing source dependency version (e.g., requested 2.0.0, no match exists)" should really be deferred to be part of #185 

Do you agree?

**Comment by big-guy** [comment]
Yes, SGTM

**Comment by eljobe** [comment]
Part one ready for review in: gradle/gradle#3146

**Comment by eljobe** [comment]
@big-guy, with respect to "Duplicate GAV mappings", I noticed this test: https://github.com/gradle/gradle/blob/4093363969a0fe5b8d08bc5cff0711e1230f4683/subprojects/dependency-management/src/integTest/groovy/org/gradle/vcs/internal/VcsMappingsIntegrationTest.groovy#L108-L129

I think that might actually make sense as the long-term behavior. In light of that should we just drop "Duplicate GAV mappings" as something we're trying to prevent?

**Comment by big-guy** [comment]
I had added that test long before we had talked about failing on duplicates.  I think allowing duplicates is the right behavior since the duplicate might not be clearly a exact duplicate.

e.g.:
This is an obvious duplicate:
```
vcsMappings {
  withModule("org:name") { /* vcs config */ }
  withModule("org:name") { /* different vcs config */ }
}
```

This one is not:
```
vcsMappings {
  withModule("org:name") { /* vcs config */ }
  addRule("some rule") { details ->
    if (details.requested.group == 'org') { /* different vcs config */ }
  } 
}
```

I think the behavior for other similar features (dependency substitution, component selection, etc) is to allow for duplicates, but the last one wins. 

Maybe we should have some coverage that you get a useful error if you supply bad configuration? e.g.:
https://github.com/gradle/gradle/blob/5dad245559078684009174d5fa37f2a3c46a2024/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/ComponentSelectionRulesErrorHandlingIntegTest.groovy#L20

**Comment by eljobe** [comment]
Okay. I'm sold. Updated the issue description accordingly.

**Comment by eljobe** [comment]
I was looking into making better error handling for "Unsupported version selectors (ranges, dynamic)" but, I don't think this makes sense in the context of a dependency resolver. Since resolvers are chained together, the only reasonable thing to do is to fail to resolve the dependency if you can't handle the version selector, and see if some other resolver in the chain can handle it.  I think it would be wrong to print an error or otherwise try to detect and throw an error in this scenario. No?

**Comment by big-guy** [comment]
I think I agree with you, it would be strange to fail early when there could be other resolvers that could satisfy the version.

**Comment by eljobe** [comment]
Okay. Also stricken from the Description of the issue.

**Comment by eljobe** [comment]
Repurposing this issue to only be about better error-handling for missing settings scripts. The other two issues from the description have been moved to #212 and #213
