### ISSUE TITLE
Support VCS mappings defined by another source dependency

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#194]
When source dependency is defined in settings.gradle and that source dependency in turn has a settings.gradle that defines a source dependency, both source dependencies should be resolved and pulled into the build.

## Test Coverage
- Given project A which defines a source dependency on project B which defines a source dependency on project C, when A resolves a configuration which contains a dependency with the coordinates of project B, both project B and project C are resolved from their source repositories and added to the build.
- Given project A which defines a source dependency on project B and project C, and project B also defines the same source dependency on project C, when A resolves a configuration which contains a dependency with the coordinates of project B, both project B and project C are resolved from their source repositories and added to the build.
- Given project A which defines a source dependency on project B and project C, and project B also defines a source dependency on project C with a different url, when A resolves a configuration which contains a dependency with the coordinates of project B, project C is resolved from the url specified by project A.
- Given project A which defines a source dependency on projects B and C, which each define a source dependency on D, projects B, C and D are all resolved from their source repositories and added to the build.
- Given project A which defines a source dependency on projects B and C, which each define a conflicting source dependency on D (i.e. different urls), an error is thrown when A resolves a configuration with B and C.
- Given project A which defines a source dependency on projects B and C, which each define a conflicting source dependency on D (i.e. different urls), a source dependency can be defined in A that resolves the conflict and projects B, C and D are all resolved from their source repositories and added to the build.

**Comment by ghale** [comment]
Following up on the discussions we had yesterday about what to do when we have conflicts, I think the following is a reasonable approach:

- If project A has a source dependency defined for projects B and C, and project B also has a source dependency defined for project C with a different url, then project A always wins.
- I project A has a source dependency defined for projects B and C, and projects B and C have a conflicting source dependency defined for project D, then the last one wins (i.e. the same behavior applies as if two conflicting definitions were defined in project A).  If the user wants a particular version of project D (and can't resolve it in projects B and C), then they can define it in project A, which will win over anything defined in the nested projects.

Another way to state this is that the rules defined in the root build always apply.  Any rules defined in the nested builds are only evaluated if there are no rules in the root build that resolve the dependency.  As a user, I always have a way to get what I want (by defining a rule in the build I am working on) but if I don't care, then I can just take whatever my source dependencies resolve.

I've created a spike of this approach at https://github.com/gradle/gradle/compare/gh/stable-native/nested-source-dep-conflict.  The iffy part about this is determining whether we are in the root build or not.  I'm doing it here by checking if `Gradle.getParent()` is null or not, which seems to work fine.  I'm not sure if there is a better way to determine this, though.

**Comment by adammurdoch** [comment]
I don't think we should use 'last one wins'  on conflict when the root build has nothing to say about the mapping. This is another case of conflict resolution, where we have 2 different instances of the target we need to choose from, just like when different versions of a library are requested in the graph. When this happens, we choose a version independently of where the requests appear in the graph. We should do the same thing when two different locations are requested.

There are several ways we might resolve a conflict where the locations are different:

1. Select an instance based on the URL, e.g. order them lexicographically and choose the first, or probe each URL and see if they are just aliases for the same thing.
2. Fail. The user then has to select one and add a mapping to the root build.
3. Grow out the metadata rules so that I can say "git url x can be replaced with git url y"

I would do 2 for now and see if anyone really has this problem.

**Comment by ghale** [comment]
Sounds good.  I've updated the description above to capture the test case and created https://github.com/gradle/gradle/pull/3688.

**Comment by ghale** [comment]
Merged.
