### ISSUE TITLE
Support version range selectors for source dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#195]
Support `x.+` and range version selectors to select revisions from source dependencies.

**Comment by adammurdoch** [comment]
This PR adds a rough implementation: https://github.com/gradle/gradle/pull/4090

I think some refactoring to reduce duplication and edge cases, and to make source and binary dependencies more similar. would be worth doing before closing this.

**Comment by big-guy** [comment]
@adammurdoch are the refactorings/edge cases covered somewhere under the "Stable source dependencies" issue?  Is this something I could help finish up to close this issue?
