### ISSUE TITLE
Hide/Remove source dependencies public APIs from 4.3

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#199]
Since this isn't done enough yet, we should make sure we don't impact the public API or impact the 4.3 release with half finished work.

**Comment by eljobe** [comment]
I wonder if we should bump this one to a higher priority. For example, I just noticed that the `grgit` library does depend on a later version of `jgit`
https://github.com/ajoberstar/grgit/blob/master/build.gradle#L48
