### ISSUE TITLE
Build an executable from C++ source

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#2]
@adammurdoch commented on [Mon May 22 2017](https://github.com/gradle/stable-native/issues/16)

Add a plugin (or plugins) that allows a native executable with no dependencies to be compiled and linked from C++ source.

For this story, the plugin can assume:

- a hard-coded set of platforms. This might just be the current platform for now.
- a hard-coded set of tool chains, for example just the ones we have now in a fixed order.
- a hard-coded convention for the source and header locations.

Implementation:

- [ ] ~Lazy toolchain selection.~ (Split out to https://github.com/gradle/gradle-native/issues/111)
- [x] Handle changes to build dir.
- [x] Handle changes to task output locations.

Test coverage should verify that the application can be executed and run.

- [x] Empty project with no source or dependencies.
- [ ] ~Incremental build and compile works for source and header files.~ (Split out to https://github.com/gradle/gradle-native/issues/113)
- [x] Stale outputs are removed when source files are removed or renamed.

**Comment by lacasseio** [comment]
Lazy toolchain selection was split out into the [configuration avoidance epic](https://github.com/gradle/gradle-native/issues/111).

**Comment by lacasseio** [comment]
Left over test coverage can be reviewed as part of https://github.com/gradle/gradle/pull/2800.
