### ISSUE TITLE
Extract Xcode XCTest support to specialized plugin

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#201]
The current XCTest plugin is opinionated as using the Xcode runtime (macOS only).

### Expected Behavior
Extract Xcode XCTest implementation to its own plugin. Take this time to also extract the generalized test configuration to base plugins to be reused by the next implementation step. The `xctest` plugin will apply the Xcode XCTest plugin under the hood.

**Comment by big-guy** [comment]
@lacasseio is this really reviewing?

**Comment by adammurdoch** [comment]
I wouldn't do this. Or, at least, I wouldn't do this any time soon.

**Comment by lacasseio** [comment]
This was abandon in favor of XCTest support directly in the same plugin.
