### ISSUE TITLE
Use Corelibs on Linux for XCTest support

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#202]
Corelibs XCTest is the runtime version of Apple XCTest for Linux (it also work on macOS).

### Expected Behavior
Gradle support Corelibs XCTest support on both macOS (for development purpose) and Linux. The `xctest` plugin will apply the Xcode runtime plugin on macOS and the Corelibs runtime plugin on Linux. There won't be any plugin alias for each runtime at this stage.

### Test
Tests should be the same as the Xcode runtime.

**Comment by lacasseio** [comment]
This is currently been implemented by PR https://github.com/gradle/gradle/pull/3084.

**Comment by big-guy** [comment]
PR for test fixture clean-up: https://github.com/gradle/gradle/pull/3369

It's not all the things I'd want to do, but I think things are a little better without the extra wrapping/delegating now.
