### ISSUE TITLE
Investigate possible 4.3 regression

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#204]
Did we change something that would cause `MavenDependencyWithGradleMetadataResolutionIntegrationTest` to take 8mins now?

https://builds.gradle.org/viewLog.html?buildId=8527773&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_dependencyManagement&tab=buildLog

**Comment by big-guy** [comment]
I don't think this is anything we've changed.

The builds started timing out here: https://builds.gradle.org/viewLog.html?buildId=8471984&tab=buildResultsDiv&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_dependencyManagement

And the change was reverted in the next build.

https://github.com/gradle/gradle/commits/oehme/performance/build-options still has the "bad" commit.

**Comment by eljobe** [comment]
@oehme, I tend to agree with @big-guy's assessment here. Are you happy with this conclusion as well?

**Comment by oehme** [comment]
Yep, I am.

**Comment by eljobe** [comment]
We have a strange process we're still developing on the Stable Native team where we don't close issues until the end of the iteration. This way, we don't lose track of what we've done during the iteration.
