### ISSUE TITLE
Advertise new native features in blog post

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#205]
It's been ~6 weeks, so we should provide another update to follow the last blog post:
https://blog.gradle.org/state-and-future-of-the-gradle-software-model

We should talk about what's in 4.2 and the latest nightlies and point to our latest samples (https://github.com/gradle/native-samples).

**Comment by adammurdoch** [comment]
Here's a rough sketch of a blog post that introduces the new c++ plugins: https://docs.google.com/document/d/1mKxoA8teBDWLYVFr2e1Qdrrbg5plDuoaO4efqn4OGzw/edit

**Comment by eriwen** [comment]
Ping. Any update here?

**Comment by big-guy** [comment]
@adammurdoch I'll start collecting the things we need for the example.

**Comment by big-guy** [comment]
I spoke to Eric and he said he's willing to spend some time polishing this for us this week. 
 @lacasseio can we get this in a good state so we can hand it off to him (his Tuesday)?

**Comment by lacasseio** [comment]
@big-guy Can you have a look at the draft so far and point out anything that should be improved before giving it to Eric.

**Comment by big-guy** [comment]
I think this is a good enough place that we should get an external set of eyes to make it better @eriwen can you take a look?

**Comment by eriwen** [comment]
Yes, I'll review tomorrow.

**Comment by eriwen** [comment]
This is a very well-done blog post — nice job all! 

I've made a few comments and adjustments to the doc. The outstanding things in my mind are:

 - [ ] A binary dependencies example replacing the source dependency one
 - [ ] Either a CI example or omitting that bit at the end (which I'm fine with)

If one of you would be willing to take care of those, then I think we are ready to translate this to markdown, make some gifs/screenshots, and then publish!

**Comment by big-guy** [comment]
@eriwen Have you had a chance to look at the blog post again and see if there's anything else you need from us?

There are a few TODOs in the PR, but they're for taking screenshots of the build scans.

**Comment by eriwen** [comment]
@big-guy I have looked over the post. Not thoroughly, but enough to know I can handle everything from here on. I'll take care of screenshots. 

Again, this post is really awesome and I'm going to work with @gradle/marketing to make sure we can get as much readership as possible

**Comment by big-guy** [comment]
published: https://blog.gradle.org/introducing-the-new-cpp-plugins
