### ISSUE TITLE
Unused source dependencies should clean up after themselves

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#211]
In two scenarios, Gradle will leave behind unused source dependency working directories forever.

If I have a dependency on `latest.integration`, we currently create/use a different checkout each time the commit changes (maybe this will be different in #187).  

If I have a dependency on `1.0`, then `1.1`, then `1.2`..., each of those builds will occupy space and will never be cleaned up until someone manually deletes the local checkout directory.

We should consider some sort of clean-up policy (like the local build cache) where old, unused source dependencies are removed.

We don't currently have a centralized copy of external source dependency repositories, but if we add that, we should consider this problem as well.

**Comment by adammurdoch** [comment]
The implementation should reuse the solution used for cleaning up the local build cache, rather than adding another ad hoc implementation. This may mean refactoring what is already there so it can be reused.

**Comment by big-guy** [comment]
Yep, that's what I had in mind.

For future reference: https://code-review.gradle.org/cru/REVIEW-6510
This is what we need to look at or update (this automatically deletes old files, but may not work for directories):
https://github.com/gradle/gradle/blob/19c0d62245075e9d40920b905c091199cecea15f/subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/FixedSizeOldestCacheCleanup.java#L39

**Comment by big-guy** [comment]
Here's what I'm going to do:

- Introduce a new cleanup action that deletes any entry older than a given age.
- We'll run this GC every 7 days and delete any entries that have not been used in 7 days.
- Wire this cleanup action into the `PersistentCache` we create for each checkout.
- Whenever we attempt to populate a checkout, we'll touch the directory to mark it as recently used.
- Instead of locking each individual commit directory (as we do now), we'll lock the parent directory, which represents a single repo.

TODO:
- How do we delete completely unused repositories? e.g., I had a VCS mapping defined and now I don't.  Or I had a dependency on something (that has a VCS mapping) and now I don't.  This checkouts will be kept indefinitely.

Test coverage:
- After checking out multiple copies of a given repository, bump the GC time and make some checkouts "old" artificially so we'll run the GC on the next build and delete some things.  Observe that we only keep the appropriate set of checkouts. 
- Unit level coverage of the clean-up action

**Comment by adammurdoch** [comment]
> How do we delete completely unused repositories?

Wouldn't the GC just take care of this? A cache garbage collector might need some way to communicate to the cache infrastructure that the cache is no longer required and can be closed and deleted.

**Comment by adammurdoch** [comment]
Or is this because we discover the caches only when they are referenced by a vcs mapping? Then we would need a way to keep track of the caches that need to have GC applied to them regardless of whether they are used or not.

**Comment by big-guy** [comment]
Merged in https://github.com/gradle/gradle/commit/afe03622828593ab77419af1692c24c010016d4c
