### ISSUE TITLE
Add XCTest to the swift-package-manager sample

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-native#215]
As a Swift developer, I'd like to see an example of how tests should be configured in Gradle for my project which is currently using the SwiftPM tool to build, so I don't have to figure out how to add them myself.

**Comment by big-guy** [comment]
I half-started this before we got into everything else last week: https://github.com/gradle/native-samples/pull/3

**Comment by eljobe** [comment]
I've added a failing integration test in https://github.com/gradle/gradle/commit/d1f4cf40bb1424591681e87c83199d42b912290f

**Comment by big-guy** [comment]
@eljobe I left you some comments

**Comment by big-guy** [comment]
I merged the sample into native-samples.
