### ISSUE TITLE
Publish metadata that describes the available variants of a C++ library

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#220]
Extend the module metadata file published to a Maven repository added in #143 to include information about all of the available variants for a C++ library. Currently, only the debug variants are visible in the metadata.

This change allows the remaining workarounds for dependency resolution to be removed from the C++ plugin, as the dependency resolution engine can calculate the correct result using only the published metadata.

Implementation:

- [ ] (maybe) don't download POM when metadata found.

Chores:

- [ ] Fix issue where publish task dependency on generation task is not inferred.
- [x] Review the module artifact name.
- [ ] Move construction of configurations/variants from plugin to domain object.
- [ ] shared lib is not uploaded twice
- [ ] use HTTP repo and make assertions about uploads on publish and downloads on resolve

Later

- [ ] Support number attribute types.
- [ ] Public API to define custom component types.
- [ ] Xcode integration when project has external dependencies.
- [ ] Artifact transform (or some other caching) is used for headers rather than unzipping on each build of each consumer.
- [ ] understand and honor header file charset.

**Comment by big-guy** [comment]
@adammurdoch did you want to split some parts of this out to call this card done?

**Comment by adammurdoch** [comment]
This is done enough for now. Split out some issues for later work.
