### ISSUE TITLE
Add a slice selector for sub matrix build

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle-native#227]
Hi

On Windows, I am running a gradle build for Poco whith those dimensions

1. LinkMode: shared/static
2. BuildMode: release/debug
3. Platform: Win32/x64
4. Flavor: bundled/unbundled

So, the ful matrix build has 16 builds. But often, I do not want to build the complete matrix, but only a slice part of it. For exemple, when there is an issue, the build to run is `shared/debug/Win32/bundled`
but it can be also on the x64 coordinate. Thus, this issue is requesting the capability to run a sliced build using a sliced selection vector as for exemple `gradlew build(shared, debug, Win32, bundled)` or `gradlew build(*, debug, Win32, bundled)`  or `gradlew build slice(shared, debug, Win32, bundled)` 

I know that this could be simulated by using dependsOn feature but this is not really useable because the slice can change from time to time and because I would have 58 build.gradle scripts to change.

**Comment by lacasseio** [comment]
Thanks for the issue. At the moment, given every build has its own set of requirement, the suggestion is to create your slice tasks. Having a feature This can be easily achieved by using two Gradle features:

1. [**Execution rules for multi-project builds**](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:execution_rules_for_multi_project_builds)
2. [**Configuration injection**](https://docs.gradle.org/current/userguide/tutorial_java_projects.html#sec:common_configuration)

A slice task building only debug tasks would look something like this:
```
class SliceTasksPlugin extends RuleSource {
    @Mutate
    void createBuildDebugSliceTask(ModelMap<Task> tasks, BinaryContainer binaries, BuildTypeContainer buildTypes) {
        tasks.create("buildDebug") {
            dependsOn binaries.withType(NativeBinarySpec).findAll { it.buildType == buildTypes.debug }
        }
    }
}

allprojects {
    apply plugin: SliceTasksPlugin
}
```

This way, you only have a single place to change to affect all subprojects.

**Comment by zosrothko** [comment]
I tested your SliceTaskPLugin and it works for building only the debug component. But I am  trying to add others dimensions to this plugin and succeded in adding the Flavor dimension but failed with the others. Could you show me how to have a sliced plugin for also the Platform dimension(as below)  and the Link dimension (shared only)
```
	platforms {
		win32 {
			operatingSystem "windows"
			architecture 'x86'
		}
		win64 {
			operatingSystem "windows"
			architecture 'x64'
		}
		linux32 {
			operatingSystem "linux"
			architecture 'x86'
		}
		linux64 {
			operatingSystem "linux"
			architecture 'x64'
		}
		macos {
			operatingSystem "macosx"
			architecture 'x64'
		}
	}
```

**Comment by zosrothko** [comment]
By the way, adding to the script `\gradle\subprojects\docs\src\samples\native-binaries\cpp\build.gradle` the Platform dimension (not in the SliceTasksPlugin  plugin but in the Model)  in this attached build.gradle
[build.gradle.txt](https://github.com/gradle/gradle-native/files/1436718/build.gradle.txt)
fails as
```
C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp>gradlew clean buildDebug
Support for running Gradle using Java 7 has been deprecated and is scheduled to be removed in Gradle 5.0. Please see https://docs.gradle.org/4.3/userguide/java_plugin.html#sec:java_cross_compilation for more details.
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileHelloLinux32DebugSharedLibraryHelloCpp'.
> No tool chain is available to build for platform 'linux32':
    - Tool chain 'visualCpp' (Visual Studio): Don't know how to build for platform 'linux32'.
    - Tool chain 'gcc' (GNU GCC): Don't know how to build for platform 'linux32'.
    - Tool chain 'clang' (Clang): Don't know how to build for platform 'linux32'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

gradlew -version

------------------------------------------------------------
Gradle 4.3
------------------------------------------------------------

Build time:   2017-10-30 15:43:29 UTC
Revision:     c684c202534c4138b51033b52d871939b8d38d72

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Windows 8.1 6.3 amd64
```

**Comment by big-guy** [comment]
@zosrothko Daniel's example was simplified to demonstrate how to select all of the debug binaries, but in your case, you have some binaries that are not buildable (because you're missing a tool chain that could build Linux on Windows).

You would need to filter for only buildable binaries:
```
tasks.create("buildDebug") {
       dependsOn binaries.withType(NativeBinarySpec).findAll { it.buildType == buildTypes.debug && it.buildable }
}
```

You can see some of the properties you can filter by here: https://docs.gradle.org/current/dsl/org.gradle.nativeplatform.NativeBinarySpec.html

**Comment by zosrothko** [comment]
@big-guy Fine.. I extended the slice plugin to build only for x86 architecture but failed to filter the link mode:
```
class SliceTasksPlugin extends RuleSource {
	@Mutate
	void createBuildDebugSliceTask(ModelMap<Task> tasks, BinaryContainer binaries, BuildTypeContainer buildTypes) {
		tasks.create("buildDebug") {
			dependsOn binaries.withType(NativeBinarySpec).findAll { 
				it.buildable && 
				it.buildType == buildTypes.debug && 
				it.targetPlatform.architecture.name == 'x86' &&
				it.component.withType(NativeLibrarySpec).shared
			}
		}
	}
}
```
Got this exception
```
* What went wrong:
A problem occurred configuring project ':CppParser'.
> Exception thrown while executing model rule: SliceTasksPlugin#createBuildDebugSliceTask(ModelMap<Task>, BinaryContainer, BuildTypeContainer) > create(buildDebug)
   > No signature of method: org.gradle.nativeplatform.NativeLibrarySpec.withType() is applicable for argument types: (java.lang.Class) values: [interface org.gradle.nativeplatform.NativeLibrarySpec]
     Possible solutions: asType(java.lang.Class), with(groovy.lang.Closure)
```
What is the proper way to filter only Shared build?

**Comment by lacasseio** [comment]
I see the issue now. You would need to use `binaries.withType(SharedLibraryBinarySpec)`:
```
class SliceTasksPlugin extends RuleSource {
	@Mutate
	void createBuildDebugSliceTask(ModelMap<Task> tasks, BinaryContainer binaries, BuildTypeContainer buildTypes) {
		tasks.create("buildDebug") {
			dependsOn binaries.withType(SharedLibraryBinarySpec).findAll { 
				it.buildable && 
				it.buildType == buildTypes.debug && 
				it.targetPlatform.architecture.name == 'x86'
			}
		}
	}
}
```

or you could keep `withType(NativeBinarySpec)` and use `instanceof` instead:
```
class SliceTasksPlugin extends RuleSource {
	@Mutate
	void createBuildDebugSliceTask(ModelMap<Task> tasks, BinaryContainer binaries, BuildTypeContainer buildTypes) {
		tasks.create("buildDebug") {
			dependsOn binaries.withType(NativeBinarySpec).findAll { 
				it.buildable && 
				it.buildType == buildTypes.debug && 
				it.targetPlatform.architecture.name == 'x86' &&
                                it instanceof SharedLibraryBinarySpec
			}
		}
	}
}
```

The produced binary is the object type, either `NativeExecutableBinarySpec` or `NativeLibraryBinarySpec` which can be in turn a `SharedLibraryBinarySpec` or `StaticLibraryBinarySpec`. I encourage you to look at the [JavaDoc for `NativeBinarySpec`](https://docs.gradle.org/current/javadoc/org/gradle/nativeplatform/NativeBinarySpec.html) to get familiar with all the native subtype.
