### ISSUE TITLE
Undefined symbols coincidentally matching transitive dependencies should fail to build

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#230]
Given the following `implementation` dependencies: `A -> B -> C` where `B` and `C` are shared library. An undefined symbol in `A` that coincidentally match an exported symbol from `C` should still fail to build with an undefined symbol at link time of `A`.

**Comment by lacasseio** [comment]
A test case exposing this issue can be found [here](https://github.com/gradle/gradle/blob/31c460265f20108d26b2d0d14d7771fd9eee35de/subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppExecutableIntegrationTest.groovy#L557-L590).

**Comment by adammurdoch** [comment]
Also should work for static libraries.

**Comment by b-john** [comment]
This is the same issue as https://github.com/gradle/gradle-native/issues/759, correct?

**Comment by lacasseio** [comment]
You are correct @b-john, this issue is a duplicate of #759. Will close this one as #759 have more information.
