### ISSUE TITLE
Discover VisualCpp version from an installation directory

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#246]
As a user, I would like to add a VisualCpp compiler from Visual Studio <2017 to the system path and have Gradle discover the correct version from the installation directory so that this information can be included in publications of my library.

Eventually, this will also feed into better modeling of toolchain requirements as I can specify a version of the toolchain that I want and Gradle can find it even it it is only on the system path.

## Implementation Notes
- If the version is also found in `vswhere` or the registry, we already find the version from that information.  This only applies to scenarios where the installation is _only_ found on the system path.
- For Visual Studio 2017, the version can be inferred from the path to the compiler as the version is baked into the directory structure (this is already implemented).
- For previous versions, probing the compiler is not useful as it returns an unrelated version (see https://stackoverflow.com/questions/1233312/finding-version-of-microsoft-c-compiler-from-command-line-for-makefiles).  Probing the linker, on the other hand, seems to return a version consistent with other sources (i.e. the registry).  This was only tested on VS2015 and VS2013 - we should also check VS2012 and VS2010.

## Test Cases
- Can infer the VisualCpp version of a compiler from a version of Visual Studio <2017 that is only found on the system path.
- A compiler found on the system path that we cannot infer the version from is ignored.

**Comment by eljobe** [comment]
This is not necessary with #256.  We don't expect to find Visual Studio installations we haven't already discovered.
