### ISSUE TITLE
Pool threads created by forking processes

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#247]
I'm not sure if this is going to make a big difference performance wise, but I've noticed that in profiling reports that we create 3 new threads every time we call an external tool.

e.g., our `nativeMonolithic` perf project has ~40k source files and I see over >100k threads created after one build (although, no more than ~60 are alive at any given time).

**Comment by adammurdoch** [comment]
This is fixed now, as part of #302. The creation of all the threads was causing a bunch of noise in the profiler outputs, but probably not affecting the build performance in a major way.

The changes are here: https://github.com/gradle/gradle/compare/56751189b3636c22a1ba0ff99e303a35e7da3e90...010abecca658c2d9c92c2d223b8a7554eff0ccf4

**Comment by adammurdoch** [comment]
Reopening this until the performance tests have been updated to lock in the performance improvement.

**Comment by adammurdoch** [comment]
Performance tests updated. Closing this now.
