### ISSUE TITLE
Revisit native test fixtures for generating integration test projects

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#250]
Some ideas...

- Improve discoverability (where are all of our test projects?)
- Improve clarity (what does the fixture do?)
- Inline test fixtures that are not expected to be reused by many other integration tests

We want to avoid unnecessary coupling between tests through the test fixtures and balance that with duplication across integration tests.

**Comment by eljobe** [comment]
Let's all try to clean this up as we move along.
