### ISSUE TITLE
Depend task detects changes in build outputs without source code modification

### ISSUE THREAD

**Issue by k-mack** [gradle/gradle-native#251]
Hi,

I upgraded to Gradle 4.3 from 4.2.1 and noticed that some projects are compiled from scratch every time without any changes to their source files. Using Gradle 4.2.x, these same projects would only be compiled if their source files changed. It seems like this stems from the new `depend` task finding differences in the project's previously generated outputs (even though no source code was modified):

```
Up-to-date check for task ':projLib:dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp' took 0.191 secs. It is not up-to-date because:
  discovered input file /project/src/build/tmp/compileProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp/output.txt has changed.
  discovered input file /project/src/build/libs/projCommon/static/linux64/release/openmp/libproj-common.a has changed.
```

The above message is produced every time after this particular project is compiled for the first time regardless of any source code changes. I don't know what this task is finding different about `output.txt` and the static library `libproj-common.a` from run-to-run.

```
$ ./gradlew projLib:build -Parch=x64 -Pflavor=openmp -Ptype=release --info
...
> Task :projLib:dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp 
Putting task artifact state for task ':projLib:dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp' into context took 0.0 secs.
Up-to-date check for task ':projLib:dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp' took 0.191 secs. It is not up-to-date because:
  discovered input file /project/src/build/tmp/compileProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp/output.txt has changed.
  discovered input file /project/src/build/libs/projCommon/static/linux64/release/openmp/libproj-common.a has changed.
Cannot determine changed state of included 'BOOST_USER_CONFIG' in source file 'config.hpp'. Assuming changed.
Cannot determine changed state of included 'AUX778076_INCLUDE_STRING' in source file 'include_preprocessed.hpp'. Assuming changed.
Cannot determine changed state of included 'PP1' in source file 'is_function_ptr_helper.hpp'. Assuming changed.
Cannot determine changed state of included 'PP1' in source file 'is_function_ptr_tester.hpp'. Assuming changed.
Cannot determine changed state of included 'PPI' in source file 'is_mem_fun_pointer_impl.hpp'. Assuming changed.
Cannot determine changed state of included 'PPI' in source file 'is_mem_fun_pointer_tester.hpp'. Assuming changed.
Cannot determine changed state of included 'AUX778076_INCLUDE_STRING' in source file 'include_preprocessed.hpp'. Assuming changed.
Cannot determine changed state of included 'BOOST_SLIST_HEADER' in source file 'slist_traits.hpp'. Assuming changed.
Cannot determine changed state of included 'BOOST_TYPE_INDEX_USER_TYPEINDEX' in source file 'type_index.hpp'. Assuming changed.
Cannot determine changed state of included 'BOOST_ABI_PREFIX' in source file 'abi_prefix.hpp'. Assuming changed.
Cannot determine changed state of included 'BOOST_ABI_SUFFIX' in source file 'abi_suffix.hpp'. Assuming changed.
After parsing the source files, Gradle cannot calculate the exact set of include files for dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp. Every file in the include search path will be considered a header dependency.
adding files in /project/src to header dependencies for dependProjCommonLinux64ReleaseOpenmpStaticLibraryCommonCpp
adding files in /project/3rdparty/boost-1.60.0/include to header dependencies for dependCommonLinux64ReleaseOpenmpStaticLibraryCommonCpp
adding files in /project/src/KML to header dependencies for dependCommonLinux64ReleaseOpenmpStaticLibraryCommonCpp
adding files in /project/src/filter/include to header dependencies for dependProjCommonLinux64ReleaseOpenmpStaticLibraryCommonCpp
adding files in /project/src/protocol/include to header dependencies for dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp
adding files in /project/src/protocol/src to header dependencies for dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp
adding files in /project/src/src/projCommon/headers to header dependencies for dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp
file or directory '/project/src/src/projCommon/headers', not found
adding files in /project/src/build/src/generated/headers to header dependencies for dependProjCommonLinux64ReleaseOpenmpStaticLibraryProjCommonCpp
```

I'm familiar with seeing Gradle struggle to understand the Boost macros and performing a rebuild, but I typically see that whenever I make a source code change to that project. Gradle would then normally proceed to rebuild the entire project. This new behavior, however, rebuilds the project regardless of any source code changes.

### Environment

* Gradle 4.3
* Debian Stretch
* `org.gradle.parallel=true`
* `org.gradle.configureondemand=true`
* Build cache is not used

**Comment by big-guy** [comment]
It looks like the build directory is showing up on the include path somehow.   Do you have an example of how your project is configured?

**Comment by k-mack** [comment]
@big-guy, thanks for the response. The project's `buildDir` is on the include path. I am using inclusion patterns to indicate what specific files are to be included. Maybe my understanding of the `include` method on the C++ source set is wrong.

Regardless, changing `project.buildDir` to somewhere else did resolve the problem, but why did this change from Gradle 4.2.x to 4.3? Or was the previous behavior wrong and 4.3 is actually doing what is desired? I was thinking that the inclusion patterns was the reason this was working before.

For context, we migrated a medium-sized C++ repository from Make to Gradle but didn't change the directory structure to match Gradle's C++ plugin's conventions. We have a `src/` that contains all the source files, and acts as the `projectDir` for many subprojects. So the `buildDir` for each project is `src/build/`. Inclusion patterns for each component tell Gradle what files inside `src/` belong to each specific subproject. This hasn't been a problem until now. I suppose changing the `buildDir` to `src/../build/` shouldn't be too big of an issue for us. Now I'm just curious as to why it did work before.

Below is a mock of what we have:

```
model {
    components {
        projCommon(NativeLibrarySpec) {
            baseName = 'proj-common'
            sources {
                generatedCpp(CppSourceSet) {
                    generatedBy tasks.generateCppSources // definition not showed here
                }
                cpp {
                    source {
                        srcDir '.' // this makes the project's `buildDir` included on the path
                        include 'source1.cpp'
                        include 'source2.cpp'
                        include 'source3.cpp'
                        // ... and so on such that each source file
                        // related to this project in "included"
                        // The same is done in `exportedHeaders {}` (not shown here)
                    }
                }
            }
        }
    }
}
```

**Comment by big-guy** [comment]
@wolfs could you take a look at this and see if something has changed?

**Comment by k-mack** [comment]
I had more time to play with this today. I wasn't able to replicate it with a simple project. However, I noticed the behavior I described above occurs when the following message is produced:

```
Cannot determine changed state of included <macro> in source file '<file>'. Assuming changed.
...
After parsing the source files, Gradle cannot calculate the exact set of include files for dependBlahBlahBlah. Every file in the include search path will be considered a header dependency.
adding files in /project/src to header dependencies for dependBlahBlahBlah
adding files in /project/3rdparty/boost-1.60.0/include to header dependencies for dependBlahBlahBlah
adding files in /project/src/KML to header dependencies for dependBlahBlahBlah
...
```

It appears that when `adding files in /project/src to header dependencies for dependBlahBlahBlah` is performed, Gradle is not applying the inclusion (and probably exclusion) patterns assigned to the component's source set. Thus, any and all files located in `/project/src`, for example, end up being registered as inputs to the `dependBlahBlahBlah` task regardless of how the source set is configured in the model for that component.

I suspect that this also happens when adding the project's dependencies' files: the patterns in the dependencies' source sets are not applied.

Our projects that don't include complex 3rd-party headers, such as Boost, don't experience this behavior and file globbing works as it did in Gradle 4.2.x.

**Comment by k-mack** [comment]
Maybe this is where the respective component's source set include/exclude patterns should be applied.

https://github.com/gradle/gradle/blob/208aa909e0da9b069c9668e797d186be8a3326a8/subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/DefaultHeaderDependenciesCollector.java#L52

**Comment by lacasseio** [comment]
@k-mack I assume when you are talking about include/exclude patterns, you are talking about something like this:
```
model {
    components {
        projCommon(NativeLibrarySpec) {
            baseName = 'proj-common'
            sources {
                generatedCpp(CppSourceSet) {
                    generatedBy tasks.generateCppSources // definition not showed here
                }
                cpp {
                    exportedHeaders {
                        srcDir '.' // this makes the project's `buildDir` included on the path
                        include 'header1.h'
                        include 'header2.h'
                        include 'header3.h'
                    }
                }
            }
        }
    }
}
```

If this is the case, those include/exclude pattern are not taken into consideration. The exported headers only consider folders and are used as include roots by the compiler. We should probably remove those methods to avoid confusion in the future.

**Comment by k-mack** [comment]
@lacasseio okay, that's probably how we are being bit by this. All our headers and source files are colocated inside `src/`. When Gradle determines it needs to add files in /project/src to header dependencies for dependBlahBlahBlah, all the headers (\*.hpp) and source files (\*.cpp) in that directory, regardless of their relationship to the current project, are added to `headerDependencies` in `DefaultHeaderDependenciesCollector.collectHeaderDependencies` and then become inputs to the `depend` task via `Depend.detectHeaders`.

We'll stick with Gradle 4.2.1 until we have time to better organize our source files. This isn't a blocker for us, but we were interested in trying out Gradle 4.3's native build cache feature.

Just thinking out loud, this might deter some projects from migrating to Gradle. There are other repositories that follow a similar pattern where all the public headers are organized in one directory. Apache Mesos (https://github.com/apache/mesos) is one project I can think of. Their public headers are organized in the top-level `include/` and all the sub-projects use this as one of their CMake's target include directories.

**Comment by wolfs** [comment]
@k-mack Thank you for the report.
IIUC, your include path contains the build dir. Moreover, you are using Boost, so you have some macro includes in your code. Like @lacasseio already mentioned, includes and excludes have no effect on the include path, so Gradle will go ahead and check all the files in the build directory for changes. That means that any task running after the depend task which modifies some already existing files in the build directory will make the depend task out of date. Now that compilation and header dependency analysis is split into two tasks, this also means that after the depend task there will always be some task modifying the build directory - the compile task. I guess this is what you are experiencing.
I strongly suggest that you do not have the `build` dir or some parent dir of it as part of the include path. You can accomplish that by either moving your sources or the build directory.
I guess moving the build directory to some other place should be easier to accomplish in your setup.

**Comment by k-mack** [comment]
Thanks for all the feedback. I think this issue should actually be renamed to "Depend task does not use SourceDirectorySet include/exclude patterns when adding header dependencies as new inputs" since this is about more than just adding build outputs as inputs to the `depend` task (although that was what initially sparked this issue). This will affect any project that shares an include-directory with another project **and** its `IncrementalCompilation.isMacroIncludeUsedInSources()` is true.

**Comment by wolfs** [comment]
@k-mack This is not new for the depend task with Gradle 4.3, but the same happened with the compile task in Gradle 4.2: Includes and excludes are ignored for the include path.

**Comment by k-mack** [comment]
@wolfs I understand what you are saying. Because of that, it's not really about the include-path. It's more about how the Depend task is adding all files in the include-path as new task inputs to itself. A change in any file in the shared include directory no longer makes the Depend task up-to-date:

https://github.com/gradle/gradle/blob/b7480a034256bb241d62735d5dfd651ec4ad2430/subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/tasks/Depend.java#L101_L103

As far as I can tell, something has changed from Gradle 4.2.1 to Gradle 4.3 in `IncrementalNativeCompiler.handleDiscoveredInputs` that ultimately provides files as task inputs for Depend.

Attached is a project that replicates the behavior I am seeing on my end. The AsciiDoc document provides the procedure to follow to demonstrate the behavior. Hopefully this will shed some light the issue. Also, the variable that seems to be causing the behavior I have been describing is a project depending on a prebuilt library header that has macro includes. If the project's header file has a macro include, then both Gradle 4.2.1 and Gradle 4.3 both act the same... depending on a prebuilt library that has macro includes in one of its header is when they diverge with respect to the behavior I have been describing.

[simple_project.tar.gz](https://github.com/gradle/gradle-native/files/1439624/simple_project.tar.gz)

**Comment by wolfs** [comment]
@k-mack Thank you very much for the example! I finally understand what the change between 4.2 and 4.3 is: 
- For 4.2, we only ended up adding all files in the include roots as inputs if the macro include was part of one of the source files.
- For 4.3, we add all the files in the include roots as inputs if a source file or a file included from one of the source files uses a macro include.

That means that with 4.3, we are more eager in detecting if there are any macro includes involved. This seems to be more correct (after all, we do not know for what file changes we need to look for), but also introduces problems as you described.

What is your take on this?

**Comment by k-mack** [comment]
@wolfs Thanks for taking a look at the project I attached. I'm glad it helped to clarify what I've experienced, and thank you for elaborating on the difference between 4.2 and 4.3.

A common organization pattern for a C/C++ repository is to share top-level "include" and "src" directories between all the subprojects. Nested directories ultimately provide the pre-project organization. Apache Mesos is a good example of what I'm trying to describe (https://github.com/apache/mesos). That said, I do think improving this behavior in Gradle will help someone using Make/CMake migrate to Gradle if they so choose to.

Just brainstorming here, but one way this could possibly be improved is by leveraging the dependency information that compilers can produce. For example, GCC has the ability to create lists of dependencies as a program is being compiled. This feature is invoked using:

* the -MD option if you wish to include system headers, or
* the -MMD option if you do not.

(Including system headers is the more robust alternative, which is what Gradle is doing, however they change rarely and can greatly increase the number of dependencies listed.)

I believe this is what CMake does. It knows how to tell gcc to generate dependency files. On other platforms like with Visual Studio, it knows how to tell cl.exe to output header dependencies and it can parse that output too. The only requirement is that the necessary headers are found during compilation.

I'm not sure if this exact workflow meshes with how Gradle does things, but If Gradle did something similar, it would have the exact set of files it would need to add as inputs to the Depends task. This may be kind of awkward since the Compile task would need to update the Depends task. What I am not sure about is what would need to be done if the compiler flags are changed between builds and a new definition is specified that ultimately changes what headers and sources are depended on, which would throw off the Depends task's up-to-date check.

**Comment by big-guy** [comment]
Thanks for your thoughts. 

> Just brainstorming here, but one way this could possibly be improved is by leveraging the dependency information that compilers can produce. For example, GCC has the ability to create lists of dependencies as a program is being compiled. 

Yep, we've looked into that.  The issue is that this doesn't give us a complete picture of the dependencies that we need to be correct. If you `#include "logger.h"` with include path `[ A/, B/ ]` and we find the header in `B/`, then when someone creates `A/logger.h`, we need to recompile.  CMake and other tools punt on this problem and recommend that you avoid ambiguous includes like this through naming conventions.

> (Including system headers is the more robust alternative, which is what Gradle is doing, however they change rarely and can greatly increase the number of dependencies listed.)

If we handled macros appropriately, I think this wouldn't be a huge problem since we can skip the more expensive analysis if we know the files have not changed.

> What I am not sure about is what would need to be done if the compiler flags are changed between builds and a new definition is specified that ultimately changes what headers and sources are depended on, which would throw off the Depends task's up-to-date check.

WRT compiler flags, that's a good point.  The `Depend` task only cares about the include path right now, but to handle macros appropriately, we would need a more complete understanding of the compiler arguments.  I think our approach here would be to make the binary the "source of truth" and configure the depend, compile and other tasks based on that.

**Comment by big-guy** [comment]
@k-mack could you given 4.4-rc-1 a try?  We changed some things WRT how we handle macro includes and although, we have more to do, it would be nice to know if this is going in the right direction for you.

**Comment by k-mack** [comment]
4.4-rc-1 is an improvement from 4.3.x w.r.t. the `simple_project` that I posted above, and it behaves just like 4.2.x, which is great. From this alone I will say that Gradle is moving in the right direction.

I'm experiencing the same behavior as reported in the original issue with shared include-paths while using 4.4-rc-1 with the bigger repos I work on. I'm fairly certain this is due to us using Boost, which has some interesting macro includes that forces Gradle to add all files on the include paths as inputs to the Depends task. It seems like 4.4-rc-1 takes longer than 4.3.x to scan the header files, at least the first time the Depends task is ran -- probably just circumstance with all the stuff I have running on my machine. You guys are already looking into Boost's macro includes with #301, so I'll track that issue. I'm guessing this is what I'm running up against. I'll cross my fingers for 4.5.

Should this issue's title be renamed to something regarding macro includes while sharing source and include-path directories between multiple sub-projects, or maybe something even more generic? While our discussion has been spot-on about the actual problem I have ran into, the issue's title is now kind of misleading.

**Comment by k-mack** [comment]
The conversation drifted away from the original post and evolved into a discussion of dealing with macros in the `#include` directive. With respect to my original post, @wolfs pointed out the problem and solution [here](https://github.com/gradle/gradle-native/issues/251#issuecomment-341429780). Therefore, I am closing this issue.
