### ISSUE TITLE
Write design spec for consolidating XCTest code path on Linux and Mac

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#254]
XCTest API has 2 implementations, one for macOS (Xcode) and one for Linux (corelibs). Both behave differently from the build system point of view. There is an opportunity to consolidate both behaviors into a single one. This work needs to have minimum impact on developer using or migrating to Gradle for there XCTest needs.

### Constraints and informations
* Apple bundle is the only way to integrate with Xcode on macOS to get a nice developer workflow. In this scenario, Xcode can only delegate the building part. The test execution is driven by Xcode.
* XCTest bundle runs through `xctest` driver application on macOS
* Linux driver application is compiled into the resulting Swift binary containing the tests
* macOS driver application doesn't allow test suites/cases listing, the Obj-C reflection runtime can be used as a 3rd party tool (i.e. xctool from Facebook or Swift PM)
* Linux doesn't support Obj-C reflection runtime
* Linux driver application support listing tests from the command line
* On Linux, the convention is to manually list tests in a file called LinuxMain.swift. This is only a convention that the build tool needs to honor.

**Comment by big-guy** [comment]
@lacasseio What would we really need to do for this now?  `XCTest` executes Linux and macOS tests in the same way and the differences are hidden behind the same public API.

**Comment by lacasseio** [comment]
You are right that now, both are quite similar. If we want to get into parallel execution, then looking at writing our own driver could be helpful. We can defer this to much later.

**Comment by big-guy** [comment]
OK, I've updated a couple of issues and created a new one so we can close this one.

#115 For parallel test execution
#116 Gradle generated LinuxMain.swift
#318 For proper wildcard support in `--tests`
#319 Proper Gradle XCTest driver
