### ISSUE TITLE
Document Provider APIs

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#255]
This is a duplicate of the original issue (https://github.com/gradle/gradle/issues/2629) simply for tracking during the sprint.

**Comment by lacasseio** [comment]
I wrote an outline of the [user guide chapter](https://docs.google.com/a/gradle.com/document/d/1TB-_beIENjAnI7j3YwgLiuMBE2EfHKy1_MGQ42ERldI/edit?usp=sharing).

**Comment by big-guy** [comment]
@lacasseio I've put several comments into the document.

I think we have all the right pieces here, but we'll need to make another pass at the exact prose (I'm happy to help more here).  I especially liked the FAQ/Summary sections.

As for next steps...

1. Could you submit a PR to gradle/gradle that adds the outline of this chapter to the user guide? This can be as-is or just the section titles or whatever minimal work we need to support updating the Gradle guide.
1. Could you take a look at updating the [Gradle Guide](https://github.com/gradle-guides/implementing-gradle-plugins) and submitting a PR for that?
1. Could you then update the user guide chapter based on the comments in the Google doc?

**Comment by big-guy** [comment]
@lacasseio I made a pass through the doc and updated the text as I went. You really did the hard work of pulling things together which made my editing job much easier.  I think we're ready to move this into asciidoc and get the samples into the auto-tested user guide infrastructure.
