### ISSUE TITLE
Build configuration should succeed on Windows when xctest plugin is applied

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#262]
When a project has the `xctest` plugin applied, configuration fails on Windows with the following:

```

FAILURE: Build failed with an exception.

* Where:
Build file 'Z:\gradle\test-projects\swift\build.gradle' line: 4

* What went wrong:
A problem occurred evaluating root project 'testApp'.
> Failed to apply plugin [id 'org.gradle.xctest']
   > Extension of type 'SwiftXCTestSuite' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BuildTypeContainer, FlavorContainer, NativeToolChainRegistryInternal, SwiftApplication, PlatformContainer, ReportingExtension]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

Configuration should always succeed, execution should fail. In this instance, attempting to build or run the tests (or anything with Swift source) should fail with a nice error message from the tool chains saying "No swift compiler available on Windows".

**Comment by lacasseio** [comment]
Unfortunately, I'm unable to reproduce this. A build scan could have helped with narrowing down exactly where it fails (missing the call stack). It looks like this was fixed as a side effect of some recent changes. I will see if I can sync an older master and write a test for this.

**Comment by big-guy** [comment]
@lacasseio the project in `XCTestPluginOnUnsupportedPlatformIntegrationTest` should do a little extra configuration to make sure we can apply and configure the `xctest` plugin.  I don't know if there's another test that shows xctest + swift plugins can be applied and configured on Windows?

**Comment by lacasseio** [comment]
Commit https://github.com/gradle/gradle/commit/4d368ccc6a81be58a9bf65409f871846e4c0f2a5#diff-596a8af724203b2212c7bb865e1b34d8 fixed this issue. The issue used to be triggered by [`XcodePlugin`](https://github.com/gradle/gradle/blob/master/subprojects/ide-native/src/main/java/org/gradle/ide/xcode/plugins/XcodePlugin.java#L206) or [`SwiftLibraryPlugin`/`SwiftExecutablePlugin`](https://github.com/gradle/gradle/blob/master/subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/plugins/XCTestConventionPlugin.java#L225). I'm looking to see if there is already code coverage for this.

**Comment by lacasseio** [comment]
@big-guy I'm looking into this and it would be nice to remove that test in favor of more assertion in other tests. I'm looking into `XCTestConventionPluginTest` so it can assert that what every the OS, an extension is created with type `SwiftXCTestSuite`.
