### ISSUE TITLE
Build an executable from Swift source

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#27]
This story builds on the spike work in #1 to add some polish and test coverage for building an executable from Swift source.

Test coverage:

- [x] Something sensible happens when project has no source.
- [ ] ~Ensure that incremental build works when source files are changed, added, removed and renamed.~ Incrementalness is handled by `swiftc`
- [x] Ensure that stale output files are removed when source files are removed or renamed.
- [x] Ensure that changes to the build directory location are respected (as was done for C++ executables).

**Comment by lacasseio** [comment]
Left over test coverage can be reviewed as part of https://github.com/gradle/gradle/pull/2800.
