### ISSUE TITLE
Allow build authors to declare their intention wrt implementation dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#272]
Split from https://github.com/gradle/gradle-native/issues/267

We don't have to honor the meaning of implementation dependencies until the swift compiler lets us.

**Comment by big-guy** [comment]
@ghale I think your change was the intention of this issue (this is one of those "of course I'll recognize what this means later" issues).

PR: https://github.com/gradle/gradle/pull/4021

**Comment by ghale** [comment]
This has been merged.
