### ISSUE TITLE
Support test filtering for XCTest

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#273]
There's no way to only run a subset of XCTests from the command-line or exclude tests from build configuration.

No special configuration:
`gradle xcTest --tests "*SomeFilter*"` should only run `SomeFilter` tests.

With build.gradle (pseudo):
```
xcTest {
  filter "*SomeFilter*"
}
```
`gradle xcTest` should only run `SomeFilter` tests.

**Comment by lacasseio** [comment]
It seems XCTest doesn't support `*` character. You can either specify the class name or the class name and the method name. We could use the JVM code, however, the Javadoc specify everywhere that `*` is supported. We won't be able to support `*` until we build our own driver.

I suggest that we implement the minimum to support test filtering and invest time in our own driver instead at a later time. This would mean you wouldn't get any support for filtering tests through `gradle.build`. Test filter support would simply forward `--tests` value to XCTest.

@gradle/native What do you think about this design?
