### ISSUE TITLE
Incremental build impact of using "macro" includes

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#274]
Given a project with a C++ source that use "macro" includes (e.g., `#include SOME_MACRO`) in any immediate or transitive header dependencies, Gradle is unable to determine the set of dependencies used by that file.  This causes Gradle to fail over to "include everything that could possibly be an input", which snapshots every file in the include path.

This manifests itself as a incremental build problem in a few of ways:

1. If the include path is large (e.g., the system include dir alone could be >1GB), Gradle needs to snapshot many more files.  This usually requires extra memory to be provided to the daemon.
1. If the include path includes the project directory, build directory or root directory, Gradle needs to snapshot files that change on every build. This breaks incremental builds.
1. Unimportant differences in the include path (e.g., extra system packages that are never used) can cause cache misses.

Macro includes are commonplace for libraries like Boost.  Users have no real workaround once a they encounter this.

**Comment by wolfs** [comment]
This got even worse in Gradle 4.3, since we now also detect macro includes in header dependencies and not only in the sources as we did with 4.2: https://github.com/gradle/gradle-native/issues/251#issuecomment-343079812

**Comment by big-guy** [comment]
Related #279
