### ISSUE TITLE
Swift-on-Linux autodiscovers inputs outside of Gradle's purview

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#275]
On Linux, the Swift tool chain seems to have knowledge about how to find dependencies when compiling and linking that Gradle doesn't know about.

We thought we needed to manually add XCTest libs to the test configuration to make it work on Linux: https://github.com/gradle/gradle-native/issues/269

But in our samples, we didn't do this and the build still works. Looking at the `--info` output, it seems like the Swift compiler (maybe only on Linux?) is embedding information that an `autolink` tool is using to find all of the library dependencies at link time. I don't see this happening on macOS.

autolink tool source:
https://github.com/apple/swift/blob/6607ff73ce7a039fe76e45e5870f21ce6b524f60/tools/driver/autolink_extract_main.cpp

We need to know what these dependencies are and maybe prevent this magic from happening.

**Comment by wolfs** [comment]
That sounds a lot like system includes for C/C++ compilation. Is this a requirement before we can safely enable caching for Swift?

**Comment by big-guy** [comment]
I assume it's something like the system includes for C/C++.  I haven't dug in enough to know how the Swift compiler is finding the correct imports (if it's a path we can discover, if it's something built-in or it's taking something from an environment variable?).

I think it will be a blocking issue for Swift caching because we'll have untracked modules dependencies coming from somewhere.

**Comment by wolfs** [comment]
When compiling with `swiftc` it is possible to pass command line arguments to see where the actual libraries for linking come from:
```
> swiftc -v -static-stdlib bob.swift
Swift version 3.1.1 (swift-3.1.1-RELEASE)
Target: x86_64-unknown-linux-gnu
/opt/swift/3.1.1/usr/bin/swift -frontend -c -primary-file bob.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -module-name bob -o /tmp/bob-7139d8.o
/opt/swift/3.1.1/usr/bin/swift-autolink-extract /tmp/bob-7139d8.o -o /tmp/bob-7ee799.autolink
/usr/bin/clang++ -fuse-ld=gold -target x86_64-unknown-linux-gnu -Xlinker -rpath -Xlinker /opt/swift/3.1.1/usr/lib/swift/linux /opt/swift/3.1.1/usr/lib/swift/linux/x86_64/swift_begin.o /tmp/bob-7139d8.o -L /opt/swift/3.1.1/usr/lib/swift_static/linux @/opt/swift/3.1.1/usr/lib/swift_static/linux/static-stdlib-args.lnk --target=x86_64-unknown-linux-gnu @/tmp/bob-7ee799.autolink /opt/swift/3.1.1/usr/lib/swift/linux/x86_64/swift_end.o -o bob
```

It looks like `XCTest` is actually a part of the Swift installation on Linux.
```
> ls /opt/swift/3.1.1/usr/lib/swift/linux/x86_64/
Dispatch.swiftdoc
Dispatch.swiftmodule
Foundation.swiftdoc
Foundation.swiftmodule
glibc.modulemap
Glibc.swiftdoc
Glibc.swiftmodule
swift_begin.o
swift_end.o
SwiftOnoneSupport.swiftdoc
SwiftOnoneSupport.swiftmodule
Swift.swiftdoc
Swift.swiftmodule
XCTest.swiftdoc
XCTest.swiftmodule
```

On macOS is is, too (and more):
```
> ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/x86_64/
...
UserNotifications.apinotesc
VideoSubscriberAccount.apinotesc
Vision.swiftdoc
Vision.swiftmodule
WatchConnectivity.apinotesc
WebKit.apinotesc
XCTest.apinotesc
XCTest.swiftdoc
XCTest.swiftmodule
XPC.apinotesc
XPC.swiftdoc
XPC.swiftmodule
...
```

It seems like we would want to track the toolchain version better instead of tracking all the libraries in the toolchain installation.
I would even think that `usr/lib/swift` would not change as long as you don't install a new version of `swiftc`. And we track the swift version already. So maybe we don't have to do anything here?

**Comment by big-guy** [comment]
Based on conversations/investigations from @wolfs, I think we can consider this working-as-intended for now.

Since we're tracking the version of Swift being used, this is approximately the same situation we have for Java/JDK compilation.

I've opened #314 as an idea for eliminating these implicit imports by requiring explicit dependencies in the build script, but I think it would be awkward to require this right now.  I think it's good enough to use the Swift version as a proxy for now.  This is different from the C++ standard library since Swift dependencies are through module definitions.  It's difficult to cause an alias between a standard library module and an external module in a way that we wouldn't notice.
