### ISSUE TITLE
Memory pressure in native builds caused by duplicate `ResolveInclude` objects

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#276]
@wolfs was asking about the sizing of our C++ performance tests (they're much smaller than the equivalent software model tests), so I tried bumping the sizes to match:

https://github.com/gradle/gradle/commit/c3cedb4073a409510d7ca430715ce335d69a5c44

This caused local build failures due to running out of memory.  I took a memory snapshot and I see hundreds of MBs of duplicated Strings in `ResolveInclude` objects.  There were >1.1 million `ResolveInclude` objects in the (failed) build of the mediumCppMultiWithMacroIncludes performance project.  There are only 10k headers in total in the project.

PR: https://github.com/gradle/gradle/pull/3445

**Comment by wolfs** [comment]
@big-guy I created a PR with a simple solution: https://github.com/gradle/gradle/pull/3445
Can you check if that fixes the problems you had?
