### ISSUE TITLE
Support for testing C/C++/non-Swift executables

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#277]
In Swift, an executable will either have a single object (which must contain the `main` symbol) or multiple objects (where the file `main.o` must contain the `main` symbol).  We use `UnexportMainSymbol` to hide the `main` symbol before linking to the test executable. For other languages, there is no easy way to know where a `main` symbol will appear.

To support testing non-Swift languages, we need to be able to produce a set of objects or a library that can be linked against by a test driver. 

We could do this several ways:
1. Force the user to exclude the source file that includes the `main` symbol (this is effectively what people do with the software model plugins now).
1. By convention, exclude the `main.o` file. For this and the option above, users would need to structure their software in a different way.
1. Rewrite all object files to remove the `main` symbol (similar to Swift).
1. Compile the production sources differently so the `main` symbol isn't produced.
1. Some other clever linker magic.

We don't necessarily need to be able to call the original `main` symbol for testing, but it shouldn't be a huge burden to test code in the same compilation unit as the `main` symbol.

**Comment by ricnewton** [comment]
Hi @adammurdoch, is there any progress on supporting testing native applications on Windows yet?

If it's any help I hacked up a quick class based on https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format to hide the main symbol that seems to work (at least for the latest Visual C++): 
 https://github.com/ricnewton/gradle/blob/windows-native-unexport-main/subprojects/language-native/src/main/java/org/gradle/language/swift/tasks/SymbolHider.java

I don't really do java but it seemed to work for basic test application using google test.

**Comment by adammurdoch** [comment]
No progress yet, we've been blocked on finding a simple way to hide the main symbol. Looks like your class is exactly what we need, at least for the unit testing plugins. Would you be interested in putting together a PR that wires this into the C++ application plugin? Or even one that simply includes your class?

**Comment by ricnewton** [comment]
Sure, I could take a look.

That branch already wires it up in https://github.com/ricnewton/gradle/blob/windows-native-unexport-main/subprojects/language-native/src/main/java/org/gradle/language/swift/tasks/UnexportMainSymbol.java, but it's a bit hacky. In particular wasn't sure how to handle the possible IOException, the try/catch looked very hacky.

Will take a look and see if there are any tests for it I can use/update.

**Comment by ricnewton** [comment]
Should also say this works with Visual C++ but no idea about clang or gcc on windows if they are supported compilers.

**Comment by ricnewton** [comment]
Initial pull request raised here: https://github.com/gradle/gradle/pull/8127

Advise on how to handle the possible IOException would be useful.
