### ISSUE TITLE
Improve build performance when macro includes are present in C++ source and header files

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#279]
Measure, profile and improve the build performance when macros are used to include a header file. For example:

```
#ifdef _linux
#define HEADER "mylib_linux.h"
#else
#define HEADER "mylib_windows.h"
#endif
#include HEADER
```

It is unspecified exactly what "improve" means until "measure" and "profile" have been completed. Perhaps these should be split into 2 or more issues.

**Comment by adammurdoch** [comment]
There are some improvements for this in the `release` branch that will be included in 4.4. The C/C++ dependency analysis now understands much more about the source and header files and gives up much less easily.

Specifically, the analysis now handles`#include` directives that use a macro as their value, and macros that reference another macro, a quoted include or a system include. For example:

```c++
#define _HEADER_ "header.h"
#define HEADER _HEADER_
#include HEADER
```

This is sufficient to discover most, but not quite all, of the headers referenced by the boost library. Making this better has been split out to #301.

Given a test project with 20 projects, 50 source and 50 header files per project, we get the following results:

Scenario | release | 4.3
---------|---------|----
ABI change assemble|9.6s|29.9s
up-to-date assemble|1.57s|1.60s
clean assemble|113.7s|112.9s
non-ABI assemble|4.51s|10.5s

"ABI change" changes a header that is visible to all projects but used only by a few source files in each project. Gradle 4.4 correctly handles the macros and can recompile only those files that are affected by the change. Gradle 4.3 recompiles all source files.

"non-ABI change" changes a source file in a project that is visible to all others. In this case, 4.4 recompiles the source file, and 4.3 incorrectly recompiles all of the source files in the project.

"clean assemble" is slower in 4.4, likely because in this particular test project it ends up discovering more input files than 4.3, both because 4.4 can follow more connections in the dependency graph and knows where the C standard header directories are. This can be made faster later (split out as #302).

**Comment by adammurdoch** [comment]
I think we should close this as done. There are some follow up stories to make this better.

**Comment by big-guy** [comment]
SGTM
