### ISSUE TITLE
Build a shared module from Swift source

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#28]
This story builds on the spike work in #1 to add polish and test coverage for building a module from Swift source.

Changes:

- Remove duplication between Swift executable and Swift module plugins.
- Remove duplication between C++ library and Swift module plugins.

Test coverage:

- [x] Something sensible happens when the project has no source.
- [ ] ~Incremental build works when source files are changed, added, removed and renamed.~ Incrementalness is handled by `swiftc`
- [x] Stale output files are removed when source files are renamed or removed.
- [x] Changes to the build directory location are respected (as was done for C++ libraries).

**Comment by lacasseio** [comment]
Left over test coverage can be reviewed as part of https://github.com/gradle/gradle/pull/2800.
