### ISSUE TITLE
Building from Xcode should work consistently when Java 9 is used

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#280]
If you run Gradle from Xcode and a Java 9 JDK is used, switching configurations may not have an effect.  Essentially, when the xcode plugin tries to decide which variant it should produce (debug or release) it queries some environment variables (provided by xcode) to determine what is being selected.  Behind the scenes, Gradle passes the request to the daemon along with the client's environment (set by xcode).  The first time a build is run (and a daemon is started) the client's environment is used to start the daemon, and everything works fine.  However, when using Java 9, subsequent builds will continue to use the same environment variables (regardless if the configuration is changed in Xcode).  This happens because we disabled mutating the environment variables in the daemon on every invocation for Java 9 because this capability was scheduled to be removed in Java 9 (i.e. we disabled it to avoid a fatal exception).

There are a couple of things we should look at to address this issue:

- Change the xcode plugin to not depend on environment variables to decipher what variant should be targeted.
- Re-enable the mutation of environment variables in JDK 9 (they have since backed off removing this capability, at least for java 9)

**Comment by big-guy** [comment]
I think we can also tell Xcode to run `gradle -PXCODE_CONFIGURATION=${CONFIGURATION} _xcode` and then we can read the Gradle properties instead.

**Comment by big-guy** [comment]
Split out issue to just fail on JDK9 for now

**Comment by big-guy** [comment]
@lacasseio or @ghale could you take a look at https://github.com/gradle/gradle/pull/3528?

**Comment by big-guy** [comment]
Since @ghale is in/out today, could you look at this @lacasseio?
