### ISSUE TITLE
System header discovery should locate C++ standard library headers when using clang or gcc

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#281]
The system header discovery mechanism for Clang and GCC discover the standard _C library_ headers, but do not discover the standard _C++ library_ headers.

The discovery mechanism should using `-x c++` to probe the compiler to discover the system headers visible to C++ code and `-x c` to probe the compiler to discover the system headers visible to C code.

We should also make the header resolution process strict after fixing this, as in theory all headers should now be known to Gradle, and this will allow us to see whether theory and practise line up.

PR: https://github.com/gradle/gradle/pull/3577

**Comment by adammurdoch** [comment]
A better option to detect leakage might be to invoke the compiler with `--nostdinc`, rather than strict header resolution.

**Comment by wolfs** [comment]
I am starting to work on that issue now.

**Comment by big-guy** [comment]
@wolfs I think we can close this issue once we've updated the perf tests.

**Comment by wolfs** [comment]
The PR has been merged and the perf tests have been updated via https://github.com/gradle/gradle/commit/6ef9a6ced130b80398d78be92e4e585ab6592c9b.
