### ISSUE TITLE
Allow user to configure location of `module.modulemap` on components exporting C APIs

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#289]
This story allows the user to configure the location of the `module.modulemap` file.

**Comment by adammurdoch** [comment]
I would defer this until someone needs it. Provided there's a conventional location to put the `.modulemap` file and it's optional to have one, then I think we're good for now.

**Comment by lacasseio** [comment]
I created this issue for tracking purpose, but I will close it now and wait for someone to ask for it.
