### ISSUE TITLE
Swift module is consumed by executable in the same build

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#29]
This story builds on the spike work in #1 to add polish and test coverage.

Test coverage:

- [x] Incremental build works when module source is changed in ABI and non-ABI compatible ways. (Demonstrated [here](https://github.com/gradle/gradle/blob/master/subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftIncrementalCompileIntegrationTest.groovy#L57-L92))
- [x] Changes to the module project's build directory location are visible to the consuming component. (Demonstrated [here](https://github.com/gradle/gradle/blob/master/subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftExecutableIntegrationTest.groovy#L282-L319))

**Comment by lacasseio** [comment]
@adammurdoch Can you review if the code I linked to each test case in the description is enough to close this issue?
