### ISSUE TITLE
Investigate performance regression from 4.2

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#293]
In 4.3, we split out the header dependency tracking into a separate task for C/C++ compilation to support C++ caching.  
In 4.4, we added system includes to the tracked include path to ensure we had a complete picture of the dependencies for compilation.

Some existing builds have seen large performance impact due to these changes.  We should strive to get back to 4.2 performance levels and make sure our performance tests capture this regression.

Since 4.3, we are more likely to properly detect "macro includes" and fallback to snapshotting the entire include path (see #279).

**Comment by wolfs** [comment]
The biggest performance regression I have seen was not due to the changes noted above, but due to detecting macro includes in third party dependencies and switching into the "snapshot the whole include path" mode in 4.3, while 4.2 was happily using the discovered inputs only.

**Comment by big-guy** [comment]
Thanks, I meant to include that too.
