### ISSUE TITLE
Build a shared library from C++

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#3]
@adammurdoch commented on [Mon May 22 2017](https://github.com/gradle/stable-native/issues/17)

Similar to #2 , add support for building a shared library binary from C++ source, with the same assumptions.

Implementation:

- Declare API dependencies.
- Reuse build logic from base plugin.

Test coverage:

- [x] Empty project with no source, headers or dependencies.
- [ ] ~Incremental build and compile work for source, header and dependency changes.~ (Split out to https://github.com/gradle/gradle-native/issues/113)
- [x] Implementation headers are not visible to consumers.
- [x] Honours changes to build dir, these are visible to consumers.
- [x] Honours changes to task output locations, these are visible to consumers.
- [x] Stale outputs are removed when source files are removed or renamed.

**Comment by lacasseio** [comment]
Left over test coverage can be reviewed as part of https://github.com/gradle/gradle/pull/2800.
