### ISSUE TITLE
Use an artifact transform to unpack the headers of a C++ library from a Maven repository

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#305]
Currently the C++ plugins use some ad hoc code to unzip and cache the headers of a C++ library. An artifact transform could be used to do the same thing. This would remove the need to maintain a separate cache of unpacked headers, would take advantage of various performance features of artifact transforms such as parallel execution, visibility through build operations and features we later add (such as garbage collection), and would use public APIs so that others can do the same thing in their own plugins, for example, in a plugin that wraps cmake or some other build system.

**Comment by adammurdoch** [comment]
Remove `NativeDependencyCache` as part of this change as it will no longer be required.

**Comment by ghale** [comment]
PR https://github.com/gradle/gradle/pull/8364

Note that this doesn't entirely remove `NativeDependencyCache` from service.  `DefaultSwiftBinary` still has a transform for module maps that doesn't fit well with artifact transforms.  Basically, we derive the name of the module from the module id of the artifact, but as near as I can tell, that information is not accessible in an `ArtifactTransform`.  I'm going to track this under a separate issue.

**Comment by adammurdoch** [comment]
For swift module generation, C++ libraries can publish a metadata artefact that contains the information that the transform needs. We've used this approach several times now to send model information from producer to consumer. I think this would be a good dog-fooding exercise.

**Comment by adammurdoch** [comment]
I guess that metadata artifact would be the module map itself ...

**Comment by ghale** [comment]
That's a good idea.
