### ISSUE TITLE
When building Swift components, static or shared C++ dependencies are supported.

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#316]
As a developer, I can build the shared or static variant of a Swift component and its C/C++ dependencies.

This is blocked on work to model/support static/shared variants of things.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/3894

**Comment by adammurdoch** [comment]
I've merged the PR and made some further changes to make things consistent. I think it's missing some form of sample before we can close it.
