### ISSUE TITLE
Demonstrate C++/Swift interop in native-samples

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#317]
Once we have #287, we should add an interesting sample that exercises several features:

- A C++ library
- A Swift library wrapper with tests
- A Swift application with tests
- The C++ library is a source dependency.
- The Swift library is a source dependency.

Xcode, build cache, XCTest should all work as a real life build.  If there's a simple existing project we can use instead, that would be OK.

**Comment by ghale** [comment]
@big-guy I created a sample for this at https://github.com/gradle/native-samples/tree/master/swift/cpp-dependencies.  Let me know if you have any feedback.
