### ISSUE TITLE
Resolving a C++ library from an HTTP repository is broken

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#329]
Resolving a C++ library from an HTTP repository fails with a `ClassCastException`

Scan: https://e.grdev.net/s/yt3frembgw6na

Seems to be broken from 4.4 onwards.

**Comment by lacasseio** [comment]
The latest nightly fixed this. Closing as fixed as the merged PR has, what appears to be, enough test coverage for this issue.
