### ISSUE TITLE
Swift application should not publish Swift API

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#333]
As mentioned in [this comment](https://github.com/gradle/gradle/pull/3660/files#r155447457), the Swift application wrongly publish his module file to be consumed by other components. The workaround was added as [Swift API dependencies of a test component on the main component didn't expose a `ComponentIdentifier` on the dependency](https://github.com/gradle/gradle/blob/master/subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/plugins/XCTestConventionPlugin.java#L233). The `ComponentIdentifier` is important when filtering out IDE artifact in the context of external dependencies.

### Expected Behaviors
A Swift application shouldn't publish Swift API (module file).

**Comment by adammurdoch** [comment]
This was removed in https://github.com/gradle/gradle/pull/5210
