### ISSUE TITLE
Install Swift 4.x and update the Swift tools installed on the Linux build agents

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#338]
The build agents are using an old version of the tooling. We should install the Swift 4.x tooling alongside the 3.x tooling and test against both.

**Comment by big-guy** [comment]
https://github.com/gradle/gradle/pull/4174

**Comment by big-guy** [comment]
After https://github.com/gradle/gradle/pull/4229 was fixed, the integration tests that use the MultiVersionRunner appear to be back to normal, including my changes.
