### ISSUE TITLE
Choose the auto-detection method for Visual Studio

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#34]
Prior to Visual Studio 2017, VS could be detected using the registry. This wasn't officially supported. With VS 2017, the detection is officially supported through COM object. [Several variants exist](https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/) and this issue is to discuss what method we should use.

### Option 1: vswhere.exe
Microsoft released [_vswhere.exe_](https://github.com/Microsoft/vswhere) as a standalone redistributable executable for detecting VS 2017 and all the way to VS 2010.

#### Pros
* With Visual Studio 15.2, it gets installed at location `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe`

#### Cons
* Prior to VS 15.2, _vswhere.exe_ needs to be fetched or package somehow
* Doesn't support version prior to VS 2008

### Option 2: PowerShell API
It requires PowerShell v5 (to avoid any dependency installation) which comes with Windows 10.

#### Pros
* PowerShell comes preinstalled with Windows 7

#### Cons
* External dependencies needs to be installed for any version prior to v5
* Hard to assume what is available as user could have updated PowerShell

### Option 3: Visual Studio Setup API
This option needs to instantiate COM objects. This isn't trivial in Java. A couple path exists:
1. [JCom (Java-COM Bridge)](https://sourceforge.net/projects/jcom/)
2. [Com4J](https://github.com/kohsuke/com4j)
3. Custom implementation through JNA
4. Custom implementation through JNI
5. [JACOB](https://sourceforge.net/projects/jacob-project/)

#### Pros
* Control over the implementation

#### Cons
* Significant engineering investment

### Resources
* https://en.wikipedia.org/wiki/Microsoft_Visual_Studio
* https://github.com/bazelbuild/bazel/blob/ac29b78000afdb95afc7e97efd2b1299ebea4dac/tools/cpp/cc_configure.bzl#L288

**Comment by adammurdoch** [comment]
I would use `vswhere.exe` if available otherwise use the existing strategy.

**Comment by ghale** [comment]
Did a little digging on this and this is what I am planning:

1. If user specifies a VS location, then use that.
1. If a compiler is found on the path, then use that. 
1. Look for vswhere.exe on the path.
1. If no vswhere is found, query the registry for "HKEY_LOCAL_MACHINE/Software/Microsoft/Windows/CurrentVersion -> ProgramFilesDir (X86)".  Look to see if _ProgramFilesDir_/VisualStudio/Installer/vswhere.exe exists.
1. If vswhere is found, then run "vswhere -legacy -format json", parse the output and use that.
1. If vswhere is not found, then fall back to searching the registry for versions (will only find VS <= 2015).

Note that vswhere is only automatically installed with VS 2017 update 2 or above, which means we have a gap for VS 2017 < update 2.  I think it's a reasonable workaround, however, that if users need to use a version of VS 2017 < update 2, then they can download vswhere from https://github.com/Microsoft/vswhere/releases and put it on the path.

Other options (if we decide we do need to close that gap) might be to:

1. Allow the user to specify a custom location for vswhere.
1. Allow the user to specify a repository dependency for vswhere (i.e. they have to publish it themselves).
1. Publish vswhere in the Gradle artifactory public repository and allow the user to specify that it should be resolved and used.  (Another variation would be to always download/use it)
1. Include vswhere in the Gradle distribution (390kb).

**Comment by adammurdoch** [comment]
Step 2 should be last. The user's path should always be our last choice for discovering things, as the path is more likely to point to something that isn't what we (or the user) think it is. In other words, it's less reliable than the other mechanisms.

**Comment by adammurdoch** [comment]
Step 3 should also be after step 4.

**Comment by ghale** [comment]
As far as moving the path searching to be the last mechanism, I agree with your reasoning, but it's not clear to me what you are suggesting.  As of now, a version found on the path trumps any other versions we find: https://github.com/gradle/gradle/blob/fe5e1334774769abb6ade2aa0e61ada168a1208b/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/DefaultVisualStudioLocator.java#L222-L222

Does that come as a surprise?  Or are you suggesting we should have a different search order for VS2017?  Or are you suggesting we should change it?

**Comment by big-guy** [comment]
I think it makes sense to change it, so people's builds are brittle due to environment differences.  But we should consider the impact on existing builds.

So it would be:
1. If user specifies a VS location, then use that.
1. Query the registry for "HKEY_LOCAL_MACHINE/Software/Microsoft/Windows/CurrentVersion -> ProgramFilesDir (X86)". Look to see if ProgramFilesDir/VisualStudio/Installer/vswhere.exe exists.
1. If vswhere is not found, look for vswhere.exe on the path.
1. If vswhere is found, then run "vswhere -legacy -format json", parse the output and use that.
1. If vswhere is not found, then fall back to searching the registry for versions (will only find VS <= 2015).
1. If we still haven't found anything, if a compiler is found on the path, then use that.

**Comment by ghale** [comment]
Right on.  I think that would be better, too, but I just want to be clear that this would be a breaking change (i.e. if I currently rely on Gradle to find a different version than the latest by using the path, I'll need to now specify the location of that version via dsl) and make sure we're all ok with that.

**Comment by big-guy** [comment]
Yes, and it probably makes this [issue](https://github.com/gradle/gradle-native/issues/181) more painful.

**Comment by adammurdoch** [comment]
The fact that the compiler on the path trumps anything else is an implementation bug in my view. I think we should change it. It's easy enough to add some logic in your build script to get this behaviour back if you so desire.

The real solution would be better modelling, such as being able to declare which C++ version your source uses and which system APIs and their versions. Then we can do a better job of selecting the tools and the libraries to use when there are multiple installations, and validating the installation you have when there's only one. And this means we will be less fragile wrt how exactly we find the installations and in which order.

**Comment by lacasseio** [comment]
It may be breaking change but in reality, VS is rarely discovered through the path.
