### ISSUE TITLE
Support for git submodules in source dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#345]
When cloning a git repository, we currently [do not checkout/clone submodules](https://github.com/gradle/gradle/blob/4b5b6d694d19923403a62508523182dc11b9bd78/subprojects/version-control/src/main/java/org/gradle/vcs/git/internal/GitVersionControlSystem.java#L87).

This means builds that rely that on submodules may not be usable. 

I took a stab at a [naive approach](https://github.com/gradle/gradle/tree/sg/native/vcs-submodules) (recursively clone the submodules and update them as necessary), but this doesn't really work with our older release of JGit (4.5.3).

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/3985

**Comment by ghale** [comment]
This has been merged.
