### ISSUE TITLE
native-samples: SwiftPM samples should include a LinuxMain.swift for tests so the SwiftPM build does the same things as Gradle

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#392]
This makes it easier to compare apples-to-apples.

**Comment by big-guy** [comment]
Sample should reflect migration and start from where a real project would start from

**Comment by lacasseio** [comment]
It seems this is already done, [see the SwiftPM sample](https://github.com/gradle/native-samples/tree/master/swift/swift-package-manager). Closing.
