### ISSUE TITLE
Create Swift PM Package.swift configuration

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-native#40]
As a Swift developer, I want to Gradle to be able to generate a `Package.swift` file which can describe my module and its dependencies, so that my module can be consumed by projects which have not yet migrated to Gradle.

Implementation:

- [x] Includes products and targets.
- [x] Includes source dependencies and project dependencies.
- [x] Fails on external dependencies with no git mapping
- [x] Fails on other kinds of dependencies.
- [x] Includes source location.
- [x] Includes C++ library public headers.
- [x] Can configure location of generated Package.swift.
- [x] Can configure which components to include in Package.swift
- [x] Honors baseName, module, swift version customisations.
- [ ] Honors source file customisations.
- [ ] Generation is incremental, use `@Nested` for model.
- [ ] Does not include tests.
- [x] Library with static and both linkages.
- [x] Samples.
- [x] Generates module map for C++ projects.
- [ ] Use source mappings from current build only, not mappings from entire composite.
- [ ] Generation honors product name customizations in source dependencies.
- [x] Version spec is converted to Swift PM spec.
- [ ] Handles dependency constraints.
- [ ] Handles compiler arg customizations.

Test cases:

- [ ] Root project does not define any components.
- [x] Generated manifest actually works with swift pm.
- [ ] Multiple dependency in same source repo.

**Comment by adammurdoch** [comment]
First cut is in this PR: https://github.com/gradle/gradle/pull/4175

Needs more test coverage, better error handling and to include a little more information in the generated file, but provides enough so that the feature is usable enough to build things with Swift PM.

**Comment by adammurdoch** [comment]
Another round of changes: https://github.com/gradle/gradle/pull/4194

This is probably good enough to park this feature for now.

**Comment by adammurdoch** [comment]
Some more improvements in #444.

**Comment by big-guy** [comment]
@adammurdoch for the unchecked parts of the original issue, do we need to split out new issue(s) to close this one?

**Comment by adammurdoch** [comment]
I've split out some issues. I might add a few more tests before closing this.

**Comment by adammurdoch** [comment]
This is done enough for now.
