### ISSUE TITLE
Verify generated Visual Studio solutions create working builds

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#411]
We want to be able to verify that the metadata generated for Visual Studio is actually usable.  For instance, we can use MSBuild to execute a build and then validate its success: https://msdn.microsoft.com/en-us/library/ms171486.aspx.

**Comment by adammurdoch** [comment]
Can we give this a better title? We should be adding integration tests as part of developing a feature and not have separate "add tests" stories, if we can avoid it. I'm guessing this story is actually about adding a _new_ kind of test coverage to verify that the generated files are actually usable by Visual Studio (using MSBuild as an approximation of Visual Studio).

**Comment by big-guy** [comment]
@adammurdoch I took a stab at renaming it

**Comment by adammurdoch** [comment]
Much better, thanks

**Comment by ghale** [comment]
Jeez, I didn't realize how poorly titled this was.  Of course, _I_ knew what I meant...
