### ISSUE TITLE
Swift projects should be able to consume system libraries as modules

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#413]
Here's an example for creating a modulemap wrapper for libcurl:

https://github.com/IBM-Swift/CCurl

This allows a Swift project to consume the libcurl library like a Swift library or C++ library produced by SwiftPM.

This is sort of related to #165 but we can probably accomplish this with the primitives we have now.

**Comment by big-guy** [comment]
We should start with a sample

**Comment by big-guy** [comment]
@ghale could you take a look at this and see if you have any other ideas? 
https://github.com/gradle/native-samples/pull/9

A few things I don't like (not that we need to do something, but just some things to think about):
- I can't just add the `curl` dependency to the implementation configuration. I have to use the binary's import path configuration.
- There's an implicit link time dependency introduced on libcurl.
- Adding just a directory and things magically working is kind of crappy.

We can't merge it just yet, but it's good enough to look at.  I need to get the libcurl headers installed on our linux agents.

**Comment by ghale** [comment]
I think it looks good for where we are now.

> I can't just add the curl dependency to the implementation configuration. I have to use the binary's import path configuration.

Yeah, this is not great.  I think fixing this in some way is the first step (or one of the first steps) to making prebuilt support better.

> Adding just a directory and things magically working is kind of crappy.

Can you elaborate on what might make this better?  For instance, defining this as some sort of reusable thing so the directory configuration is in one place or whatever would be less crappy.

**Comment by big-guy** [comment]
> Can you elaborate on what might make this better? For instance, defining this as some sort of reusable thing so the directory configuration is in one place or whatever would be less crappy.

I was thinking a few different things.  
- If the `curl` directory had a module map file and a header and a README, I think we're going to treat the README as an input and anything else in that directory.  
- It feels like we're exposing a bit too much of the underlying swiftc/Gradle machinery that we need to say "add a directory to this particular configuration" and poof it works (including linking).
- If we wanted to get this as a binary, composite or source dependency, that doesn't really work.
- As with all types of "file" dependencies, I think we don't record any sort of relationship to the modulemap or directory.  Nothing in our metadata, nothing in reports.  There's no such thing as "resolving" these dependencies if they're conflicts.

I think this is all tied up into our "prebuilt" stories and how we handle system libraries, 3rd party libraries, libraries built by other tools, etc.  This sample is a little special in that it's really something that the user provides that uses a system library.  

I think I'd like something more like this:
```
apply plugin: 'cpp-library'

library {
    linkage = NONE
    dependencies {
        api ':curl:4.3'
    }
}
```

where ':curl:4.3' is something that Gradle knows how to find on the system (but could follow the prebuilt library example for now).

**Comment by adammurdoch** [comment]
We should probably capture an issue to implement this in a better way.

**Comment by big-guy** [comment]
We have all of these issues that overlap with each other and covers the system library/prebuilt library side of things:
https://github.com/gradle/gradle-native/issues/165 - System libraries dependencies management 
https://github.com/gradle/gradle-native/issues/98 - Builds can depend on non-Gradle-built libraries
https://github.com/gradle/gradle-native/issues/380 - C++ or Swift component uses prebuilt binaries for a C++ library

I've added two new issues:
https://github.com/gradle/gradle-native/issues/447 for the header-only aspect of this issue
https://github.com/gradle/gradle-native/issues/448 for the usage of a modulemap dependency with Swift
