### ISSUE TITLE
Flaky GitVcsIntegrationTest where source dependency is not reset properly when local changes are detected

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#414]
Not sure how it's getting into this state and may point to a real issue:

Found two occurrences of this:
https://builds.gradle.org/viewLog.html?buildId=10477098&tab=buildResultsDiv&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_dependencyManagement

I've added some additional logging to see if we can catch it again.

**Comment by adammurdoch** [comment]
The test changes the content of a file without changing its length, making the change less likely to be noticed by git. I'd change the test to change the file length.

**Comment by big-guy** [comment]
I made the content change longer so this should be less likely to happen.  reopen if this reoccurs
