### ISSUE TITLE
Support source dependencies that follow upstream branches

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#417]
Source dependencies can use explicit versions (which match on tags), version ranges (which match on tags) or latest.integration (which is interpreted as "tip of default branch"). 

If you had multiple repositories that all had a `develop` branch, you might want all of your source dependencies to build against the latest `develop` and gradually switch dependencies to a `stable` branch or pin the versions exactly with tags (or commits).  

Implementation

- [ ] error reporting when branch not found.
- [ ] can combine version + branch criteria.
- [ ] can use with dependency constraint.
- [x] can use in C++/Swift dependency DSL.

**Comment by adammurdoch** [comment]
This is an important use case, I think. We have several options for modelling this:

1. Interpret the `version` property of a dependency declaration as a branch name, if it happens to match a branch name.
2. Add a new selector syntax to the 'version' property, e.g. `branch(master)` or `branch=master`
3. Add a new `branch` property to dependency declarations.
4. Add a new `selector` or `criteria` property that can allow criteria to be expressed to match on version, tag, revision, branch, release status, variant attributes, etc.
5. Treat `branch` as a variant attribute and allow criteria to be expressed in terms of variant attributes on a dependency declaration. We'd only need exact matching for a branch attribute.

For me, attempting to jam stuff into the `version` property doesn't make sense, as the version of something and the stream of work, or branch, it belongs to are separate things. A thing has both, e.g. version "4.5.1" from the "release" branch, or version "build_12345" from the "swift-support" branch. The revisions, tags and branches in a VCS are separate things.

Treating 'branch' as a special hard-coded property also seems like something we don't want to do and instead should aim for one of the more open options that would later allow many different kinds of constraints to be expressed would be better. However, adding branch as a thing could be a reasonable medium term option.

Treating branch as an attribute and allowing criteria to be expressed in terms of attributes feels like a good option for longer term evolvability, but is also the most abstract and means more implementation effort to get something working quickly.

We should also consider the scope of this particular issue. Branches can be based off other branches, branches can be merged, changes can be cherry picked, etc. However, these are really just the mechanics and at a higher level of abstraction, things are much simpler. I think we can start with a very simple model where streams of work fork off the "mainline" stream of a product only, continue for a while, and then end. In other words, we'd support exact matching on a branch name only.

**Comment by big-guy** [comment]
Need to start design work on this

**Comment by adammurdoch** [comment]
An initial implementation is here: https://github.com/gradle/gradle/pull/4260

This change introduces a placeholder API (basically option 3 above) pending some further design work.

**Comment by adammurdoch** [comment]
Some more changes: https://github.com/gradle/gradle/pull/4271

**Comment by big-guy** [comment]
@adammurdoch Is anything else needed for this?

**Comment by adammurdoch** [comment]
I want to add a few more tests

**Comment by adammurdoch** [comment]
This is done enough. Raised a few more issues out of this.
