### ISSUE TITLE
Official support for mingw-64

### ISSUE THREAD

**Issue by altavir** [gradle/gradle-native#419]
The official documentation lists mingw-w64 as unsupported toolchain, but it seems that the latest mingw-64 distribution works like charm out of the box with simple declaration like:
```gradle
        mingw_x86_64(Gcc) {
            path minGW64Path
            target("windows_x86_64")
        }
```

Is there any reason why it is not marked as supported or at least partially supported?

**Comment by big-guy** [comment]
It's the same reason we don't claim support for [cygwin64](https://github.com/gradle/gradle-native/issues/127).  We don't have integration coverage for it, so we don't count it.

**Comment by altavir** [comment]
I would not bother about cygwin, it is obsolete with the arrival of ubuntu for windows, but mingw-64 is really important because it is the simplest way to compile x64 libraries on windows. I struggled for two days and did not manage to make gradle work with msvc 2017 build tools and LLVM requires libraries from either mingw or msvc. 

So at least a hint about that mingw-64 could work would be very useful.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/8123

@lacasseio Can you take a look at ☝️ ?
