### ISSUE TITLE
Announce source dependencies

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-native#42]
Source dependencies are a great feature and we should let people know about them.

Clean up the DSL, possibly adding some conveniences for the simple module -> git url mapping.
Create a blog post, which should make it clear that source dependencies work for Java and Android projects as well as native, why you'd use it and a bit of a roadmap.
Add user guide content and samples for jvm builds.
Allow a build scan to be generated for a build that is using source dependencies.

**Comment by lacasseio** [comment]
We already announced source dependencies so I'm going to fold this epic into https://github.com/gradle/gradle/issues/10559
