### ISSUE TITLE
Spike XCode support for Swift executable

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#43]
A [spike was created](https://github.com/gradle/gradle/tree/dl/xcode-ide) to integrate Swift executable into XCode IDE. Here's a step back and how the integration is planned to take place:

1. Introduce specific task for generating the various XCode files for the integration with Gradle. Those tasks use the `GeneratorTask` infrastructure already in use by other IDE integration plugins.
    - `GenerateXcodeProjectTask` takes care of generating the `project.pbxproj` file containing the files to include, targets (how to build each variant and code completion) and build configuration (`Debug`, `Release`, etc.). In general, two targets are generated per variant, one for indexing and one for delegating to Gradle. Given this file is a _Property List_ (plist), a set of new classes needs to be rolled out to add support for this output in `GeneratorTask`. This include `PropertyListGeneratorTask`, `PropertyListTransformer` and `PropertyListPersistableConfigurationObject`.
    - `GenerateSchemeFileTask` takes care of generating the `*.xcscheme` file controlling what target to run from within XCode. In general, one scheme is generated per variant associating with the target delegating to Gradle.
    - `GenerateWorkspaceSettingsFileTask` takes care of generating the `WorkspaceSettings.xcsettings` file simply to disable the automatic creation of additional schemes based on the targets.
2. Introduce an extension to configure the XCode project and workspace. We want to be able to configure the location of the XCode package as well as modeling what needs/can be configured for each XCode package. The public API is modeled as needed. It means only what is required by the user will be modeled. Everything else will be modeled as "good enough" in the internal API. The interface `XcodeExtension`, `XcodeProject` and `XcodeWorkspace` are the only classes.
3. Introduce a plugin to wire everything together and provide a sensible default. The class `XcodePlugin` use the `IdePlugin` infrastructure.

**Comment by adammurdoch** [comment]
> Introduce an extension to configure the XCode project and workspace

We don't need anything to be configurable at this point. Nor do we necessarily need a way for the plugin to describe the model of the component to the generation tasks (which is what this model is used for in the IDEA/Eclipse plugins). The generation tasks can make a whole bunch of assumptions about the component at this point and we can make it better later.

**Comment by lacasseio** [comment]
Sorry for the confusion. I simply modeled it after Visual Studio integration. There is an extension but no public API is exposed. I simply used it as a way to hold some configuration in the internal API so I can configure Swift executable vs module. It's mainly static with little configurations at this point.
