### ISSUE TITLE
SwiftCompile task should not analyse Swift source files to extract header file dependencies

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#44]
The `SwiftCompile` task reuses a bunch of stuff from `AbstractNativeCompileTask` to do its thing. This happens to include preprocessor header file dependency analysis. However, the Swift language has no preprocessor and the (Gradle) `SwiftCompiler` does not use any of the information from the dependency analysis. This is completely pointless work.

**Comment by big-guy** [comment]
@adammurdoch is this probably done now because SwiftCompile and SwiftCompiler no longer share anything with the other native compilation tasks?

**Comment by adammurdoch** [comment]
Yeah, we should close this. There's still a lot of complexity in there that I think we should remove at some point but we can probably live with this for now.
