### ISSUE TITLE
Generated Visual Studio files should be verified against multiple versions of Visual Studio 

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#446]
Our integration tests for verifying the generated visual studio files only runs against the version of msbuild provided by vswhere. To fully mimic building with VS2010, VS2013, VS2015 or VS2017, we really need to pick a version of msbuild that is installed with VS and all of the other supporting msbuild files.

**Comment by adammurdoch** [comment]
This is fixed in https://github.com/gradle/gradle/pull/4527. The test fixture selects the MSBuild version that is distributed with the version of VS under test.
