### ISSUE TITLE
Rename 'swift-module' plugin to 'swift-library' plugin

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#47]
This plugin provides support for building a specific kind of Swift module that is intended to be used as a library, rather than some providing supporting for building any kind of Swift module.

**Comment by lacasseio** [comment]
Just to make sure I understand properly before doing the change, we would rename any notion of "Swift module" to "Swift library"?

- `swift-module` to `swift-library`
- `SwiftModulePlugin` to `SwiftLibraryPlugin`
- `create xcode project for Swift module` to `create xcode project for Swift library`

This change would imply renaming/changing:

- [ ] Plugin `.properties` file
- [ ] Test cases name
- [ ] Usage of the `swift-module` plugin
- [ ] Class name containing `SwiftModule`
- [ ] Samples from [`gradle/swift-samples`](https://github.com/gradle/swift-samples)

**Comment by adammurdoch** [comment]
We don't necessarily want to change every reference to 'swift module'. There are still modules. The issue is that a "Swift module" simply refers to a bunch of Swift code compiled together, regardless of whether that code will end up used as an application, a library, a test suite, a plugin, etc. The plugin that is currently called the "Swift module" plugin is actually very opinionated about what kind of module it is producing. It doesn't produce arbitrary modules, it produces modules that are libraries.

That said, I doubt we have any references to a "Swift module" in the code that are in fact a reference to a module and not a library, except perhaps the 'moduleName' property on the compile task.

**Comment by adammurdoch** [comment]
btw I would treat this as lower priority than getting the Xcode branch into shape.

**Comment by lacasseio** [comment]
This was done in https://github.com/gradle/gradle/commit/3877f9438a5d406f9579d4331d546d3cb1e30355. Feel free to review this change. The samples will be changed once a nightly will be ready.

**Comment by lacasseio** [comment]
This other commit (https://github.com/gradle/gradle/commit/c1a60a518a0eecd7511870c3ac87c37d1b7ccb96) is also part of this change as it slipped through the cracks.

**Comment by adammurdoch** [comment]
I think we can close this now
