### ISSUE TITLE
Define behavior for IDE configuration for builds that have mixed sets of operatingSystems across projects

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#472]
Some questions:
- Do you see projects that have non-sensical variants at all?
- Can you see the source files for non-sensical variants (e.g. Windows variant on macOS)

**Comment by big-guy** [comment]
Investigate current implementation and document here and accept that unless it's crazy.

**Comment by lacasseio** [comment]
Xcode IDE produces a workspace that has an error because of the absence of build configuration (only tried a single project). I manually added a configuration and the code shows up without any build option which is fine. I'm trying to validate there aren't any additional errors.

**Comment by lacasseio** [comment]
Xcode IDE fixes are in PR https://github.com/gradle/gradle/pull/8272

**Comment by lacasseio** [comment]
The quality of the code navigation is degraded because of issue https://github.com/gradle/gradle-native/issues/977 preventing to properly configure the IDE project. I purposefully ignored the issue on PR https://github.com/gradle/gradle/pull/8272 given that it's not essential for this issue.

**Comment by lacasseio** [comment]
Next step is to look at the Visual Studio IDE plugin for its behaviour.

**Comment by lacasseio** [comment]
The Visual Studio IDE plugin isn't failing for this specific use case. It simply ignores the project from the solution. I tried fixing it, but the architecture of the plugin doesn't make it easy to change to current behaviour. We can talk about it on Monday. For now, I will assume we can close this issue in favour of https://github.com/gradle/gradle-native/issues/978 that we can fix later.

**Comment by lacasseio** [comment]
VS IDE generation fails for unbuildable architecture. PR https://github.com/gradle/gradle/pull/8284 fix this issue.

**Comment by lacasseio** [comment]
VS IDE generation fails for unbuildable architecture. PR https://github.com/gradle/gradle/pull/8284 fix this issue.

**Comment by lacasseio** [comment]
I agree they should match. I don't think we should hide them given that would most likely be a step backward. I see this as missing test coverage or miss written test. I tested it with on a VM but may have missed a scenario. Let me take a look when I get back. Sorry for causing all this delay with the RC.

**Comment by lacasseio** [comment]
This issue is partly handled for Visual Studio and Xcode plugin. By partly, I mean we could have better support for intellisense for unbuildable component.

**Comment by lacasseio** [comment]
Issue https://github.com/gradle/gradle-native/issues/980 will continue this work to improve Intellisense.
