### ISSUE TITLE
Gradle should minimize the number of IDE files that are regenerated

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#506]
IDEs typically use the timestamp or content of the IDE metadata files as an indicator of "up-to-date-ness".  

With the changes to VS solution generation #410, whenever we generate the IDE for a multi-project build, we rewrite all metadata files.  This causes VS to reload all projects, even if the files are effectively the same.

We should investigate if the metadata actually changes (I think it shouldn't) but also if we can avoid retriggering expensive reloading in the IDE if a subset of projects actually change by not rewriting all of the files.

Some test cases:
- Adding a new subproject (does it reload everything?)
- Removing a subproject (does it reload everything?)
- Changing the baseName/generated name for something built by Gradle in one project (does it reload everything?)

**Comment by ghale** [comment]
This is ready for review: https://github.com/gradle/gradle/pull/4531

@lacasseio Do you mind taking a look?

**Comment by lacasseio** [comment]
Code review completed!

**Comment by ghale** [comment]
Merged.

**Comment by adammurdoch** [comment]
The implementation feels too complex and not reusable. I would think about simply change the base generator task to assemble the new text content as normal in memory, compare it against the content of the existing output file, and update the file only if the content is different. This means the capability will work for any generation tasks.
