### ISSUE TITLE
Allow services to be injected into extension object constructors

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#518]
Creation of extension objects is inconsistent with other places where model objects are constructed, in that the plugin code that creates the extension objects is responsible for finding and injecting the services required by the extension. In other places, such as plugin application, task creation or using `ObjectFactory`, the created doesn't need to care and Gradle takes care of injecting the services.

This has an impact on the native plugins, as dependencies of the extensions leak into the public API of the plugins. This also adds complexity to the plugins. Instead, change `ExtensionContainer.create()` to inject services into extensions. It will need to do this in a backwards compatible way wrt the `@Inject` annotation. Use this capability to simplify the native plugins.

**Comment by lacasseio** [comment]
@adammurdoch Was this fixed with all the recent changes you did around the injector?

**Comment by adammurdoch** [comment]
yes, it was fixed in 5.2
