### ISSUE TITLE
Announce source dependencies in a blog post

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#519]
- Show why this is useful for development (JVM, native)
- Plugin injection from outer build into source dep
- Details about roadmap/availability in 4.7 and follow on 4.8

**Comment by adammurdoch** [comment]
first draft is here: https://docs.google.com/document/d/1Ymw6sFqqmouFXLhqgnmAzWt9-EuySTgbrr9EvB5nBrY/edit#

**Comment by eriwen** [comment]
I plan to make time to review the draft tomorrow

**Comment by big-guy** [comment]
@adammurdoch I left some comments on your post.

**Comment by big-guy** [comment]
posted https://blog.gradle.org/introducing-source-dependencies
