### ISSUE TITLE
Provide factory methods for operating system families

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#532]
Declaring a target operating system family is somewhat awkward, we should instead add factory methods, including a method to get the host OS family. This can be used for declaring target OS but also for the same purposes that the internal `OperatingSystem` type is used for now.

**Comment by big-guy** [comment]
I don't think this is quite done, but this is what I was thinking:
https://github.com/gradle/gradle/pull/4901

It turns this:
```
library { 
    operatingSystems = [
        objects.named(OperatingSystemFamily, OperatingSystemFamily.WINDOWS), 
        objects.named(OperatingSystemFamily, OperatingSystemFamily.LINUX), 
        objects.named(OperatingSystemFamily, OperatingSystemFamily.MACOS)
    ]
}
```
into:
```
library { 
    operatingSystems = [
        targets.windows(),
        targets.linux(),
        targets.macOS(),
    ]
}
```
or:
```
library { 
    operatingSystem targets.windows()
    operatingSystem targets.linux()
    operatingSystem targets.macOS()
}
```

**Comment by adammurdoch** [comment]
I think we should just close this in favor of whatever comes out of #777.
