### ISSUE TITLE
Allow the target operating system family of a C++ or Swift binary to be queried

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#533]
Currently, target operating system is expressed in terms of `OperatingSystemFamily`, however there is no query method on `CppBinary` or `SwiftBinary` that exposes the target operating system family as an `OperatingSystemFamily` type.

The `targetPlatform.operatingSystem` property does expose some methods to figure this out, but uses different types with different and inconsistent methods. We should make the two types consistent. The `OperatingSystem` type is mutable so probably shouldn't be exposed on `CppBinary` or `SwiftBinary`.

**Comment by big-guy** [comment]
PR https://github.com/gradle/gradle/pull/4883
