### ISSUE TITLE
Test plugins should assume that test suites target the same operating systems as the component under test

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#535]
Currently, the `cpp-unit-test` plugin assumes that the unit test suite targets the host operating system when no target OS is specified for the unit test suite, regardless of the operating systems declared for by the component under test. This doesn't make sense, the unit test suite can only ever target a subset of those targeted by the component under test.

**Comment by big-guy** [comment]
related #464

**Comment by big-guy** [comment]
We now enforce that the unit test is a subset of the component under test
