### ISSUE TITLE
Latest nightly is behave differently than Gradle 4.6 causing build failures

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#551]
While trying to update gather metric on project https://github.com/lacasseio/boost-asio (using Boost and Protobuf), the build fails on the latest nightly (4.7-20180301002546+0000).

### Expected Behavior
The build should keep passing after a Gradle upgrade.

Note: I have yet to confirm if it's a misconfigure been made obvious with the latest Gradle.

### Current Behavior
Build is failing on 4.7-20180301002546+0000 but passing on 4.6.

### Your Environment

 * Build scan URL: 
    * 4.6: https://e.grdev.net/s/gf5p7sleta3oe
    * Nightly: https://e.grdev.net/s/f22v7cirpb4fc

**Comment by adammurdoch** [comment]
Just to add a data point, that build works for me with a recent Gradle build.

**Comment by lacasseio** [comment]
The issue we saw is related to the processing and ordering of the include root by the compiler. For example, in 4.6 the following include root are used in this order as shown by the compiler verbose flag:
```
 /Users/daniel/gradle/tmp/boost-asio/client-0/src/main/headers
 /Users/daniel/gradle/tmp/boost-asio/common/src/main/headers
 /usr/local/Cellar/boost/1.66.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
```

In 4.7, the Mac OS SDK plaftorm include root is added at the end of all the discovered system includes. However, the compiler report the following include root search order (note the position of the platform include root):
```
 /Users/daniel/gradle/tmp/boost-asio/client-0/src/main/headers
 /Users/daniel/gradle/tmp/boost-asio/common/src/main/headers
 /usr/local/Cellar/boost/1.66.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
```

When using the `-nostdinc` flag, the compiler uses the include root in the order specified by the command line:

In 4.6:
```
  /Users/daniel/gradle/tmp/boost-asio/client-0/src/main/headers
 /Users/daniel/gradle/tmp/boost-asio/common/src/main/headers
 /usr/local/Cellar/boost/1.66.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
```

In 4.7:
```
 /Users/daniel/gradle/tmp/boost-asio/client-0/src/main/headers
 /Users/daniel/gradle/tmp/boost-asio/common/src/main/headers
 /usr/local/Cellar/boost/1.66.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include
```

From the debugging @big-guy and I did, 4 things would need to be taken into consideration/act upon (they are not mutually exclusive):
1) Use `-nostdinc` and take the ownership of the command line argument completely. We can avoid sneaky compiler behavior as well as ensure cache correctness/reproducibility.
2) Control when Mac OS SDK platform should be added as a dependency to a native project. It seems that Mac OS SDK plaform may be harmful in some case. The build autor should be able to decide when to depend on the SDK. It ties a bit into the next point.
3) Understand how Mac OS X SDK platform should be used and if there is any gotcha that Gradle needs to handle. There is a chance we overlooked some additional configuration needed to use Mac OS SDK platform. We should double check the use cases and how to address them.
4) Find out why clang reorder include root when `-nostdinc` is not used. The observation seems to force all system include at the end of the command line which causes Mac OS X SDK platform include root to become first in line for header resolution.

**Comment by lacasseio** [comment]
@adammurdoch The build worked for you as the wrapper is set to 4.2.1 for convenience when doing manual tests. I updated the build script to use a workaround in order to move forward with the profiling (use `-nostdinc` flag). You should be good for running the profiling without any issue.

**Comment by adammurdoch** [comment]
I wasn't using the wrapper version. I was using a Gradle version I built yesterday.

**Comment by big-guy** [comment]
We'll follow up what to do with this in https://github.com/gradle/gradle-native/issues/564
