### ISSUE TITLE
Add samples for C++ builds

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#57]
I think a good way to start documenting and gathering feedback on the new C++ plugins would be to add some public samples, similar to those we have added for Swift.

**Comment by lacasseio** [comment]
Maybe we could add them in the Swift sample repository as it's totally legal to mix the two together. Any thought? I can do that tomorrow.

**Comment by adammurdoch** [comment]
Yeah, I would just add them all in the same repo for now.
