### ISSUE TITLE
Replace software model plugins with new plugins in Gradle Guides

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#577]
We have guides for building C and C++ executables and C++ libraries on https://gradle.org/guides/

As they are written, they use the software model. We should update the guides to use the new plugins.

**Comment by big-guy** [comment]
What are we going to do for the C guide?

**Comment by lacasseio** [comment]
I think the C guide would look weird if we port it. Instead, we should work on adding C support in my opinion.

**Comment by big-guy** [comment]
We can also see if we can retire it/hide it for now

**Comment by lacasseio** [comment]
We can remove the C guide from the index here: https://github.com/gradle/dotorg-site/blob/gh-pages/_data/guides.yml

**Comment by lacasseio** [comment]
Hiding C executable guide PR is opened.

**Comment by lacasseio** [comment]
Converted guide PR: https://github.com/gradle-guides/building-cpp-libraries/pull/12 and https://github.com/gradle-guides/building-cpp-executables/pull/4.

The PR still points to software model user guide chapiters.

**Comment by zosrothko** [comment]
> 
> 
> We can also see if we can retire it/hide it for now

Please put all documentations of the software model plugins ('c', 'cpp', cpp-unit-test' in a accessible directory and make a link in the documentation of the new cpp plugins
