### ISSUE TITLE
Add test coverage for the native samples

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#58]
Add some automation to ensure that the samples continue to work as we make changes to Gradle.

**Comment by lacasseio** [comment]
The [simplistic test](https://github.com/gradle/native-samples/tree/master/samples-dev) in the sample repo helps prevent breakage between Gradle version. Should we rescope this issue into something more concrete or close it?

**Comment by adammurdoch** [comment]
We're missing a few things:

- Windows coverage (for the C++ parts).
- A CI build that runs these tests on any change to the samples
- Ideally, a CI build that runs these tests on any change to the build tool (or some subset of the build tool, eg the native plugins).
- Do the above on MacOs.

We can split these out into separate issues and maybe add an epic over the top and close this issue.

**Comment by lacasseio** [comment]
There's a lot of discussions that can take place with regards the listed test coverage. I will convert this issue to an epic and move it to future until we decide to do the work.

**Comment by eljobe** [comment]
I'm wondering if we should go ahead and bite the bullet on this. It seems like one of those infrastructure projects that if we don't do soon-ish, it will become a "big project" that we end up not doing. As we add more and more samples, it seems like this is going to feel larger and more ominous.  I advocate for moving it to the "Soon" column.

**Comment by big-guy** [comment]
We now run some basic checks on the native samples.
