### ISSUE TITLE
Improve the grouping of C++ compiler log output on console

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#584]
The work in #436 improves the Gradle console so that log output of a task is grouped and shown with a header that identifies the task from which the log output came from, for all console modes.

However, the grouping implementation can still lead to interleaving of task outputs because the output of a task is buffered only for a very short period. This was an existing issue with the rich and verbose consoles that the plain console now inherits. Note that when the output is interleaved, a header is added to identify which task the output came from, so the goal of #436 is satisfied but the could be improved further (hence this separate issue).

Here's an example of the interleaving:

```

> Task :compileDebugCpp
/Users/adam/gradle/test-projects/cpp/src/main/cpp/appimpl1api.cpp:41:6: error: use of undeclared identifier 'AppImpl1Api'
void AppImpl1Api::doSomething() {
     ^
1 error generated.


> Task :lib1api1:compileDebugCpp
/Users/adam/gradle/test-projects/cpp/lib1api1/src/main/cpp/lib1api1impl1api.cpp:40:6: error: use of undeclared identifier 'Lib1Api1Impl1Api'
void Lib1Api1Impl1Api::doSomething() {
     ^
1 error generated.

/Users/adam/gradle/test-projects/cpp/lib1api1/src/main/cpp/lib1api1impl2api.cpp:39:6: error: use of undeclared identifier 'Lib1Api1Impl2Api'
void Lib1Api1Impl2Api::doSomething() {
     ^
1 error generated.


> Task :compileDebugCpp FAILED
/Users/adam/gradle/test-projects/cpp/src/main/cpp/appimpl2api.cpp:39:6: error: use of undeclared identifier 'AppImpl2Api'
void AppImpl2Api::doSomething() {
     ^
1 error generated.


> Task :lib2api:compileDebugCpp
/Users/adam/gradle/test-projects/cpp/lib2api/src/main/cpp/lib2apiimpl2api.cpp:39:6: error: use of undeclared identifier 'Lib2ApiImpl2Api'
void Lib2ApiImpl2Api::doSomething() {
     ^
1 error generated.


> Task :lib1api1:compileDebugCpp FAILED
```

The implementation could buffer for longer, particularly when there is little output buffered for a task and there is other activity happening.

**Comment by ghale** [comment]
I've tried a few different things:

For comparison, this is what the output looks like on master now (2s flush timeout):

asciinema: https://asciinema.org/a/bPxEqY0wCSnfEBz5U4igp9aFE
build output: https://gist.github.com/ghale/619e808b5fd50af7b30b25ae7323db44

This is the same build, but with a dumb 30s flush timeout:

asciinema: https://asciinema.org/a/tbPrHeAllyKhDQTPnoN2LkvkX
build output: https://gist.github.com/ghale/e280f0a511498948efa781c36883ef11

This is with an approach where we have a "foreground" task.  This allows a task to take the foreground and start writing output.  Another task cannot take the foreground unless a high watermark timeout expires or a task completes:

asciinema: https://asciinema.org/a/agXRacptxOLO5eN0B3fGUxG8V
build output: https://gist.github.com/ghale/f6baf27fb3cb9d4ce1e5b77163c093ca

Both the 30s timeout and the foreground task approach group the output quite well, but the foreground task feels a lot less choppy than the 30s timeout, and the choppiness gets worse the longer the tasks run.  I want to do some more testing with it, and I think there's some more I can do with it to make the grouping better, but this seems like the right direction.

**Comment by ghale** [comment]
These improvements were implemented in https://github.com/gradle/gradle/pull/4789.
