### ISSUE TITLE
stderr is no longer used for the final 'build failure' message at the end of the build

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#597]
The rich console stopped doing this awhile ago, I think.  With the plain console using the same infrastructure, it appears we no longer put out the "What went wrong" messages to stderr at all.

**Comment by adammurdoch** [comment]
This is fixed (to some degree) in https://github.com/gradle/gradle/pull/4887

**Comment by adammurdoch** [comment]
This is done enough for 4.7. The build failure ends up on stderr when using the plain console. All of the other error output still goes to stdout, like the other consoles.
