### ISSUE TITLE
Apply lazy task creation and configuration to the gradle/gradle build and measure the effect

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#602]
Take the result of #600 and change the `gradle/gradle` build to use the new APIs for the tasks that it creates or configures. Measure the result.

This issue shouldn't change any of the Gradle plugins to use the new APIs, that should be done as a separate piece of work. This issue may, however, need some fixes to the implementation that comes out of #600.

**Comment by big-guy** [comment]
I collected our data for the lazy task configuration here: https://docs.google.com/document/d/14FEbQ9zLVSdr9svvW5jm8rH-xKC3D8rEpjo0ueOlKbQ/edit#heading=h.7w3t9cf7lk26

I was very skeptical after the initial round of changes showed very little improvement (<5%) and seemed to have plateaued when increasing the number of tasks that were never configured.

However, after Gary and I made some additional changes, we were avoiding more than 50% of the tasks in the gradle/gradle build and saw a bigger impact (14%). I think this is big enough that we should continue this work and incorporate the changes from the spike into master. I'd like to see the impact to an Android build, but I think this can be worked in parallel now.
