### ISSUE TITLE
Apply lazy task configuration to all tasks used by the Java plugin

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#603]
With the changes in #600 the Java plugins lazily create and configure the `processResources`, `compileJava` and `classes` tasks of each source set.

We should continue on with this to update the Java plugin (and the base plugins it uses) to use lazy configuration for all tasks that it creates or configures (e.g. `jar`, `test`, `javadoc`, the lifecycle tasks).

This issue should change only the Java plugin, or perhaps also the Java library plugin. Other plugins should be split out into other issues.

**Comment by big-guy** [comment]
https://github.com/gradle/gradle/pull/5170

There are some tasks that aren't lazy yet (`assemble`, `check`, `buildNeeded`, `buildDependents`) that aren't possible with our current API.

`jar` is blocked by #644.  `test` is being eagerly configured from `configureEachLater` [here](https://github.com/gradle/gradle/pull/5170/files#diff-3c55da711188fd617ee234253a70b6daR418).
