### ISSUE TITLE
unexpected native library version loaded. expected 21 was 25.

### ISSUE THREAD

**Issue by LinuxRocks2000** [gradle/gradle-native#604]
when i try to compile, it gives this error message:
Android Studio project detected
ANDROID_HOME=/usr/lib/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
studio

FAILURE: Build failed with an exception.

* What went wrong:
Unexpected native library version loaded. Expected 21, was 25.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
my operating system is kubuntu 17.10.1

**Comment by big-guy** [comment]
Hi @LinuxRocks2000,

This is the issue tracker for issues related to developing native support (C++, Swift, etc) for Gradle.

Which version of Gradle are you using (`gradle -v`)? I suspect you're on an old version (4.6 is the latest).  I would recommend installing the [latest](https://gradle.org/install/) via SDKman! or manually.

**Comment by LinuxRocks2000** [comment]
please reopen if possible.

**Comment by big-guy** [comment]
@LinuxRocks2000 Please try installing Gradle manually to see if there is a difference from our official repo and the ubuntu repos.

**Comment by LinuxRocks2000** [comment]
i've done that before. i think it was openjdk causing the error, i have oracle jdk now and i'm trying to get it to work.
