### ISSUE TITLE
Improve efficiency of `TaskContainer`

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#605]
The implementation of the new methods in #600 wasn't intended to be particularly efficient (and so isn't), but will need to be for the goal of reducing configuration time by doing less work managing tasks.

We should profile and optimize the `TaskContainer` implementation in order to get the best result from this effort. We should do this a few times, e.g. at the same time as #602.

**Comment by big-guy** [comment]
Find newer issue for performance profiling and close this one
