### ISSUE TITLE
Provide the real public API for lazy task creation and configuration

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#606]
The API in #600 was intended to be a placeholder for a real API. We should design the real API and refactor the existing methods (ideally, just some renames and a few conveniences) before rolling this out to too large an audience. We should also make this clear when rolling this out initially for people to look at.

The focus of this issue should be the _API_, rather than the _DSL_. Making the DSL work well is #626.

- Define a task with name and type, optional configure action, optional constructor args.
- Locate a task by name without realizing it.
- Apply configuration to all task with type as they are realized.

Ideally, the implementation will continue to mostly be provided by general purpose features on `DomainObjectCollection` and friends, rather than a task specific solution.

**Comment by big-guy** [comment]
https://docs.google.com/document/d/1xJJatBQE8AKdYGXmE0oeZ08frAaHZ33luYLK3Y1ywNA/edit#
