### ISSUE TITLE
Fix implementation of lazy task creation and configuration

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#607]
The changes in #600 were intended to be a very rough initial implementation of lazy task configuration. There are a number of issues with the implementation that we should fix:

- Finish implementing support for elements are added using `addLater()` or `createLater()` on all of the methods on `DomainObjectCollection` and subtypes. 
- Add validation to `getByNameLater()` when the task is not known.
- Test error handling and reporting when deferred creation or configuration of a task or domain element fails when it is queried, e.g. constructor fails, configuration action fails, etc.
- Correctly handle the case where a `Provider<Task>` returned from `createLater()` or `getByNameLater()` is queried again after task creation fails.
- Insertion order should be retained when an element is added using `DomainObjectCollection.addLater()`, particularly for list subtypes.
- Fix `CompositeDomainObjectSet` so that it does not use the eager APIs to listen for changes in the member collections, as this breaks the laziness.

This issue could probably be split up into a few smaller issues. It's really just a bucket of issues.

**Comment by big-guy** [comment]
- Support `Provider<T> tasks.createLater(String name, T type)` for tasks that do not have a configuration action.
