### ISSUE TITLE
Change all Gradle core plugins to use lazy task configuration

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#608]
This is just a placeholder, we should split this up into more bite sized chunks, e.g. the IDE plugins, the code quality plugins, the JVM plugins, the native plugins.

Software model plugins can be excluded.

When changing the native plugins, we should attempt to unify the approaches and APIs used for laziness for tasks and laziness for binaries.

**Comment by lacasseio** [comment]
Let's close this epic but leave the native specific issue open for lazy APIs.
