### ISSUE TITLE
compiling cpp/simple-library on linux

### ISSUE THREAD

**Issue by vittali** [gradle/gradle-native#621]
I download https://github.com/gradle/native-samples/tree/master/cpp/simple-library on a Linux Ubuntu 16.04 64 machine with gradle 4.6.

```
$ cd ./simple-library
$ ./gradlew check
```
result:
```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/p/Downloads/gradle/simple-library/build.gradle' line: 40

* What went wrong:
Execution failed for task ':compileDebugCpp'.
> Could not find method get() for arguments [] on Tool chain 'gcc' (GNU GCC) of type org.gradle.nativeplatform.toolchain.internal.gcc.GccToolChain.
```
scan: https://gradle.com/s/fp2ts5gesciqo

**Comment by big-guy** [comment]
We update the samples here to work with nightly or RC versions of Gradle as the new plugins can change from time to time.  In this case, there were API changes between 4.6 and 4.7, so the sample only works for 4.7. 

I think it should work if you ran with `./gradlew` (which is 4.7-rc-1) and not the version of Gradle you have installed.

**Comment by vittali** [comment]
Yes, this works after:

```
$  gradle wrapper --gradle-version=4.7-rc-1
```

Thanks !
