### ISSUE TITLE
Add task to run installed native executable

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#629]
@ThadHouse commented on [Sat Apr 14 2018](https://github.com/gradle/gradle/issues/5047)

I want to run a native executable installed by the install task. Prior to 4.7, I could create another exec task that depended on the installed task whose commandLine was set to the runScript property of the install task. However I realize that that method was internal, and in 4.7 that was removed. It looks like runScriptFile could work, but I can't figure out how to actually get the property out of what that returns in a groovy scripts. Plus, it seems like I shouldn't need internal methods to create a run task. Either one should be there already, or there should be a public way to get the created run script.

**Comment by big-guy** [comment]
dupe #440 ?

**Comment by lacasseio** [comment]
The issue is indeed a duplication of #440.
