### ISSUE TITLE
Convert JVM IDE plugins to use lazy task API

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#630]

**Comment by lacasseio** [comment]
The JVM IDE plugins are converted here: https://github.com/gradle/gradle/tree/lacasseio/lazy/ide

**Comment by lacasseio** [comment]
Parked PR: https://github.com/gradle/gradle/pull/5315

**Comment by lacasseio** [comment]
Split out native IDE plugins lazy task API conversion to https://github.com/gradle/gradle-native/issues/659

**Comment by lacasseio** [comment]
This is ready for review.

**Comment by lacasseio** [comment]
Thanks @big-guy for pushing this over the finishing line!
