### ISSUE TITLE
Diagnostics when lazy configuration actions fail

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#641]
- Test error handling and reporting when deferred creation or configuration of a task or domain element fails when it is queried, e.g. constructor fails, configuration action fails, etc.
- Correctly handle the case where a Provider<Task> returned from createLater() or getByNameLater() is queried again after task creation fails.

**Comment by lacasseio** [comment]
PR open for review: https://github.com/gradle/gradle/pull/5383

**Comment by big-guy** [comment]
I cherry-picked this to release
