### ISSUE TITLE
Fix concurrency issues in dependency resolution that are made worse by lazy task configuration

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#651]
Issue https://github.com/gradle/gradle-private/issues/1145 exposes a bunch of pre-existing concurrency issues in the implementation of composite builds and dependency resolution, where the project state is accessed and mutated by multiple threads.

Initially, the test exposed some pre-existing concurrency issues that were exposed by shuffling around how the IDE plugins share stuff across project boundaries, where project state mutation moved from task graph calculation (single threaded) to task execution (multiple threads). Since then, however, the same test has exposed several more pre-existing issues that were exposed by deferring task configuration, for the same reason.

I've added this issue so we can better track the fixes for these concurrency issues, as the work affects velocity (it's not a small amount of work) and has also effectively become part of the lazy task work (it's basically a blocker to further laziness).

**Comment by big-guy** [comment]
@adammurdoch do you think https://github.com/gradle/gradle/pull/5272 fixed the remaining concurrency problems so we could close this?

**Comment by adammurdoch** [comment]
I think so. I've just parked this in 'review' for now to keep an eye on the test and see whether it is still failing or not.

**Comment by adammurdoch** [comment]
8 days without a failure is long enough. I'm going to close this, we can open new issues if there are new failures.
