### ISSUE TITLE
Support `Property` setter generation for unusal capitalization like `cCompiler`

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#652]
### Expected Behavior

The generated setter for properties like `cCompiler` of type `Property` allow Groovy code to work properly:
```
cCompiler = "some-value"
```

### Current Behavior

The current generator code, simply `StringUtils.capitalize` the property name which creates a setter named `setCCompiler`. The Groovy property named `cCompiler` would generate a getter named `getcCompiler` which will cause an issue for Groovy script like:
```
cCompiler = "some-value"
```

Instead, we need to either use `CCompiler = "some-value"` or `cCompiler.set "some-value"`

### Context

This issue was discovered while working on PR https://github.com/gradle/native-samples/pull/14.

**Comment by lacasseio** [comment]
The work for this issue has been parked due to lack of time: https://github.com/gradle/gradle/pull/5216

**Comment by lacasseio** [comment]
The PR is still ready for another round of review if we want to push this through.

**Comment by big-guy** [comment]
Thanks for noticing this Daniel.  I merged your PR
