### ISSUE TITLE
4.7 regression: Easy to find failure messages for individual tasks in a failed build

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#653]
Before 4.7, redirecting stderr to a file would produce a file with the stderr of every task and the overall build failure.
After 4.7, redirecting stderr to a file would produce a file with only the overall build failure.  The stderr from each task is written to Gradle's stdout and grouped/buffered.

There's no simple way to get the pre-4.7 behavior back (see https://github.com/gradle/gradle/issues/4947).

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/5346

**Comment by ghale** [comment]
I think this is ready for a final review.  I've created follow up issues for some of the items identified during this work:
 
#667 
#668 
#669
#670

**Comment by adammurdoch** [comment]
We should also change the sample running to set the magic properties to route the error output into the userguide output.

**Comment by ghale** [comment]
Good point.  I just switched it back to its previous behavior, but we should test the stderr output as well - #672
