### ISSUE TITLE
Migrate sample plugins from Groovy to Java

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#655]
Part of this issue is to decide if Kotlin would be a good fit for the sample plugin's code.

### Expected Behavior

`native-samples` repo should be following Gradle's own best practice when it comes to the various sample plugins.

### Current Behavior

All `native-samples` plugins are all in Groovy when we recommend using Java.

### Context

See [this code review comment discussion](https://github.com/gradle/native-samples/pull/12#discussion_r185131827).

**Comment by big-guy** [comment]
Use Java

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/native-samples/pull/28
