### ISSUE TITLE
Investigate composite build related regressions

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#657]
I think we introduced these:
https://github.com/gradle/gradle/issues/5167
https://github.com/gradle/gradle/issues/5168

None of these builds look particularly special, so I'm not sure why our integ tests are OK.  Maybe we need a "IntelliJ-like" import test?

**Comment by big-guy** [comment]
Create new issues as we find problems.

**Comment by Vampire** [comment]
Do you buy me the licence? ;-)
Actually I have to upgrade soon anyway for being able to use Java 9+ and I can work around it until then.
