### ISSUE TITLE
Reuse dependency analysis for source file from previous compilation

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#658]
Rather than calculate the include file dependency graph of a source file each time the compile task is run, attempt to reuse the analysis for a source file from the previous compilation.

Some experiments with this approach show some nice potential improvements with the boost-asio test project.

**Comment by adammurdoch** [comment]
Some results from this branch: https://github.com/gradle/gradle/tree/am/cpp-skip-visit for the boost-asio project:

|Scenario                                      |branch|master|4.7       |4.2.1|
|-------------------------------|-------|-------|-------|-----|
|assemble                                     |1.03s   |4.78s  |4.93s  |0.67s|
|assemble (no magic flag)          |0.99s   |9.96s  |9.99s  |0.68s|
|clean assemble                           |35.91s |37.50s|38.05s|41.10s|
|clean assemble (no magic flag)|38.04s |44.39s|47.41s|46.74s|
|assemble + source file change |2.90s    |6.69s  |6.86s |8.41s  |
|assemble + header file change |14.07s   |16.94s|15.88s|42.46s|
|clean assemble + cache            |3.32s    |7.48s   |8.49s |49.73s|

This is quite a nice improvement. The branch is much faster than 4.7 in all scenarios, and much faster then 4.2, except slightly slower in the fully up-to-date case.

The downside is that the performance tests for 'nativeMonolithic' have regressed slightly (~300ms for the non-parallel case). I think we could probably live with this regression for a while and merge the changes.

**Comment by lacasseio** [comment]
Those are amazing results. I also think we can live with a small regression for now.

**Comment by adammurdoch** [comment]
Changes are merged: https://github.com/gradle/gradle/pull/5306
