### ISSUE TITLE
Introduce a test runner for the various console attachment configurations

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#668]
Right now, we have some abstract console tests that test the same behavior with plain, rich and verbose consoles.  We also have different console attachment scenarios (i.e. console not attached, console attached to both stdout/stderr, console attached to stdout only).  We have subclasses of the abstract classes for each permutation, but this is turning into a lot of unique subclasses.  We should probably introduce a test runner for the various console attachment scenarios, so that each test is run with each scenario and we only have subclasses for the different console types (plain, rich, verbose).

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/5399

**Comment by lacasseio** [comment]
PR has been merged, closing.
