### ISSUE TITLE
Flush output before switching between stdout/stderr

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#670]
When we switch from writing to standard output to writing to standard error (or vice versa), we should attempt to flush the current stream before switching to the other in an effort to avoid interleaving when both are attached to the same file handle.

**Comment by big-guy** [comment]
Spike to see if this helps

**Comment by etiennestuder** [comment]
@big-guy @ghale I'm not sure from the thread on this issue if it got solved our only spiked? The issue is affecting build scans quite a bit - and it is also breaking the TeamCity plugin for build scans.

**Comment by ghale** [comment]
@etiennestuder We did some preliminary spiking on this and discovered that the streams were already being flushed on each write.  In other words, flushing on the Gradle side of the pipes has little to no effect.

**Comment by alekseyp555** [comment]
Not all std err messages gradle catch from error stream. How to we can resolve it?  gradlew testTask -Ptarget=local cleanTest test 1>out.log 2>err.log
