### ISSUE TITLE
Implement changes for proposed lazy task API

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#674]
implement changes from #606

Namely:

- Use `configureEach {}` and `withType(...).configureEach {}` instead of separate `configureEach` methods.
- Keep `addLater()`
- Change `getByNameLater` to `get`
- Keep `createLater` for now

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/gradle/pull/5412

**Comment by big-guy** [comment]
This PR uses the new methods: https://github.com/gradle/gradle/pull/5435

**Comment by big-guy** [comment]
PR to remove unused API methods: https://github.com/gradle/gradle/pull/5447/files

**Comment by adammurdoch** [comment]
We shouldn't consider this done without implementing a replacement for `get(class, name)` or at least splitting out a new issue for this (and implementing it soon).

**Comment by big-guy** [comment]
`get(type, name)` is now `withType(type).named(name)`
