### ISSUE TITLE
Avoid polluting the action set with task specific action with lazy task API

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#678]
### Expected Behavior

Avoid polluting the action set with action specific to a task.

### Current Behavior

[The execution order of lazy task creation is now consistent with the behavior of eager task creation.](https://github.com/gradle/gradle/pull/5320) The fix is not ideal since it means that we create an action set that is proportional in size to the number of tasks and each of those actions will be iterated over for every realized task, even though that action is known to only apply to a single task.

### Context

See https://gradle.slack.com/archives/C09LZKUCB/p1526484206000351

### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment]
I haven't given much thought, but another alternative could be to keep an action set on each `TaskProvider`. When the provider is realized, we execute those actions and ignore the global action set. Once the `Task` is part of the eager `TaskContainer` all new actions would be executed on the task. The `TaskProvider` can now be safely removed with all of this provider specific action. In the case of task overwriting, we can remove the `TaskProvider` instead of keeping a `removed` flag to prevent its action from executing.

I don't think both solutions are mutually exclusive. We could have a little bit of both.

**Comment by oehme** [comment]
The problem with that is that it doesn't keep the order of execution intact. If I have alternating withType().configure() and get().configure() calls I expect them to be in that order. That wouldn't work with separate sets for named and typed actions. 

Or maybe I misunderstood you and you mean coyping all withType actions to the provider. That would consume even more resources I'm afraid.

**Comment by lacasseio** [comment]
I was referring to that second part "copying all withType actions to the provider". I think it would consume more resource the least tasks are realized. The more task we realize the more things can be garbage collected.

Is there a reason we use an `ImmutableActionSet`?

**Comment by oehme** [comment]
We use an ImmutableActionSet because it is almost always the right choice - few additions, many accesses. But with the recent changes we now have lots of additions, so it would probably be better to have a mutable implementation, based on a LinkedHashSet.

**Comment by lacasseio** [comment]
The current logic always queues up the configuration action with appropriate logic to only affect the specific task. Some improvement can be done to reduce the amount of task queue up to the global task action set when we know the task is already realized. Both task provider - `ExistingTaskProvider` and `TaskCreatingProvider` - can shortcut the global task action set when the task has been realized. We could consider this as an improvement.

**Comment by oehme** [comment]
Yes, though the goal is to have them all be lazy. Consider my suggestion above about changing the data structure from copy-on-write to mutable.

**Comment by lacasseio** [comment]
You are right, your suggestion is better, I think both solutions could work in tandem. I think there will always be an eager task at least for a while. Let's move forward with your suggestion, then measure to see if it would help to improve further.

**Comment by adammurdoch** [comment]
I'll take a look at this.

**Comment by lacasseio** [comment]
Excellent @adammurdoch. I though it was going to be a quick fix but my initial implementation proved that your expertise would be a good fit for it.

**Comment by adammurdoch** [comment]
Some improvements here: https://github.com/gradle/gradle/pull/5679

**Comment by adammurdoch** [comment]
I think we can close this. There are more improvements we could and should make to this infrastructure but we should do this as separate issues.
