### ISSUE TITLE
Move `register` to `NamedDomainObjectContainer` and `PolymorphicDomainObjectContainer`

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#680]
This allows other containers to start to use this

**Comment by big-guy** [comment]
Also move `named(...)`

**Comment by big-guy** [comment]
Beware of the build operations (should stay in Task container)

**Comment by adammurdoch** [comment]
We also need to move the validation that has been or is being added to task container but isn't specific to tasks (deprecate calling remove or add on these containers, don't call project lifecycle hooks from configuration actions, etc). Probably best to do this as a separate issue.

**Comment by big-guy** [comment]
Yes, I think the plan was to do this for tasks first and then the other containers (if it didn't happen automatically)
