### ISSUE TITLE
Reserve the `application` and `java` project namespaces before Kotlin DSL 1.0 is released

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#681]
The Kotlin DSL adds a project extension for each project convention that a plugin adds. The Java plugin adds a `java` convention, and the Application plugin adds a `application` convention, so these end up as extensions in the kotlin DSL. After Kotlin DSL is released, we won't be able to replace these with something else.

This conflicts with a couple of things we'd like to do:

- Application plugins, of any domain, use the `application` extension for the main component model.
- A property/provider centric model for these.

Before we release Kotlin DSL 1.0, we should add some placeholder extensions for the Java and Application plugins that we can later evolve to do the above, as it will be more difficult to do this in a backwards compatible way later.

I don't think we care about the namespaces that the other plugins add, they can be retired later.

**Comment by big-guy** [comment]
need to do this in 4.10
