### ISSUE TITLE
Jar builds fine on Mac OS, tests fail on Ubuntu

### ISSUE THREAD

**Issue by bondibox** [gradle/gradle-native#684]
I am working with tronprotocol/java-tron master branch. It specifies JDK8 which I am using. Every few days I will delete ~/.gradle and reclone the repo. Once in a while it won't build, with failed tests. Meanwhile the same process builds fine on my mac. I have tried new Debian builds and the recommended Ubuntu but it is not a problem specific to the distribution or linux build.

**Comment by lacasseio** [comment]
Thank @bondibox for your question, however, the issue trackers are specifically reserved for feature requests or bug reports with steps to reproduce. This issue is a question that would better be asked on the [user forum](https://discuss.gradle.org/). It would be important that you include, in your forum post, the reason why you require to delete the `~/.gradle` folder.

**Comment by bondibox** [comment]
I thought the steps to reproduce were obvious: 
create new user / delete current .gradle dir. 
JDK8. 
Clone Java-Tron. 
./gradle build. 

Meanwhile the bug reports are piling up over at the java-tron repo all from users running Ubuntu.

It was explained to me on Twitter that there are many reasons why you could have doubted my assessment, among them if I had deleted .gradle while the daemon is running. If I used mavenLocal(), or if I used hardcoded paths to files.

Well, that's nice of you all to *assume* I'm an idiot, instead of taking the opposite tack.

I reported a problem that java-tron won't build and the problem is specific to Ubuntu. Is it too much to ask that someone try building this on Ubuntu? You know, just in case I'm right?

**Comment by lacasseio** [comment]
Thank @bondibox for the kind word toward the Gradle team. I would like to take this opportunity to direct you to [our code of conduct](https://gradle.org/conduct/) as well as [our issue template](https://raw.githubusercontent.com/gradle/gradle-native/master/.github/ISSUE_TEMPLATE.md) for your next interaction on our issue tracker.

Gradle is a build tool and will build, and in your case, test the software as it's written. As originally stated the issue expressed here is merely a software bug in the `java-tron` project. Following the issue template or even posting a question on the user forum would be more beneficial for both parties to have a clear solution. That being said, I took the time to look into the `java-tron` software bug exposed and finding a solution.

To reproduce the bug, I assume the environment is an Ubuntu 16.04 virtual machine configured as a single processor. Given that, I can reproduce the failure originally state with a root nested exception showed in the following call stack. Note that all test failures fail with the same exception.
```
                    Caused by:
                    java.lang.IllegalArgumentException
                        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
                        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
                        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
                        at org.tron.core.db.Manager.init(Manager.java:289)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
                        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
                        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
                        ... 41 more
```

By using some debugging 101 techniques, we can see the failure happens [during the creation of an `Executor` in `Manager.init()` call](https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/db/Manager.java#L288-L289). Continuing with our debugging 101, we see that the thread pool tries to be configured with [a value calculated in `Args`](https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/config/args/Args.java#L353-L354). Given the Ubuntu virtual machine has only a single CPU, `Runtime.getRuntime().availableProcessors()` will rightfully return 1. Dividing 1 by 2 in whole number math happens to result in 0. This number is passed to the thread pool creation and, as the call stack above and the [JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool(int)) shows, it results in an `IllegalArgumentException`.

There are several steps to move forward:
1) Fill an issue with `java-tron` to correctly handle the case where only 1 processor is reported as available
2) Increase the number of processor/core of the Ubuntu virtual machine

I hope this helps unblock with the non-Gradle related issue expressed here.
