### ISSUE TITLE
Update Gradle guides for lazy task configuration

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#700]

**Comment by big-guy** [comment]
- Defer other Gradle guides
- "How to implement a plugin" needs to use new API
- Need to warn what the minimum version of Gradle is required to use new API
- Need to be stable

**Comment by big-guy** [comment]
new issue+7

**Comment by ghale** [comment]
PR for implementing-gradle-plugins: https://github.com/gradle-guides/implementing-gradle-plugins/pull/23

**Comment by ghale** [comment]
PR for writing-gradle-tasks: https://github.com/gradle-guides/writing-gradle-tasks/pull/13
