### ISSUE TITLE
Update built-in samples to use lazy task configuration where it makes sense

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#701]
in the gradle/gradle repo

**Comment by lacasseio** [comment]
I converted the Groovy samples and was going to look over the Kotlin samples now. There some tricky conversion that we will need to make a decision. I will comment in the PR https://github.com/gradle/gradle/pull/7976.

**Comment by adammurdoch** [comment]
I would start with only the samples that show how to implement a plugin. We could probably also stop there for now.

**Comment by lacasseio** [comment]
Well, I already went through all the samples. What are we expecting here to be converted to lazy configuration?
