### ISSUE TITLE
`tasks.all {}` runs multiple times for the same lazy created task

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#707]
```
class Foo extends DefaultTask {}
tasks.create("foo", Foo) {
    tasks.createLater("bar", Foo)
}
tasks.all {
    println "OK " + path
}
```

`gradle help` will print:
> OK :bar
> OK :bar
> OK :foo
> OK :help

`:bar` is configured twice.

The all eager version works (`OK` is printed once per task):
```
class Foo extends DefaultTask {}
tasks.create("foo", Foo) {
    tasks.create("bar", Foo)
}
tasks.all {
    println "OK " + path
}
```

Another variation is wrong as well:
```
class Foo extends DefaultTask {}
tasks.createLater("foo", Foo) {
    tasks.createLater("bar", Foo)
}
tasks.all {
    println "OK " + path
}
```

I've also confirmed that this is happening with 4.8-rc-2 with:
```
apply plugin: 'java'

tasks.all {
    println "OK " + path
}
```
It seems like this is only a problem with `tasks.all {}`, configureEach and withType appear to work as expected.

**Comment by adammurdoch** [comment]
There's a fix on this branch: https://github.com/gradle/gradle/tree/am/lazy-task-iteration

I didn't merge it today, someone might want to pick this up and maybe get it merged if there's going to be an RC-3.

**Comment by lacasseio** [comment]
This is merged in the release branch. If CI is all good ([see comment on PR](https://github.com/gradle/gradle/pull/5552#issuecomment-392532573)) we can merge back in master.

**Comment by adammurdoch** [comment]
@lacasseio thanks for merging this. Can we close this issue now?

**Comment by big-guy** [comment]
Yep, release is green and it's in master.
