### ISSUE TITLE
Failure report during eager task creation/configuration should be as useful as for lazy task cases

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#711]
### Expected Behavior

```
* What went wrong:
A problem occurred configuring root project 'lazy-failure'.
> Could not create task 'myTask' (CustomTask)
  > Received null for CustomTask constructor argument #1
```

### Current Behavior

Given the following build script:
```
import javax.inject.Inject

class CustomTask extends DefaultTask {
    final String message
    final int number

    @Inject
    CustomTask(String message, int number) {
        this.message = message
        this.number = number
    }

    @TaskAction
    void printIt() {
        println("\$message \$number")
    }
}
```

Eager task failure: `create('myTask', CustomTask, null, null)`
```
* What went wrong:
A problem occurred evaluating root project 'lazy-failure'.
> Received null for CustomTask constructor argument #1
```

Lazy task failure: `createLater('myTask', CustomTask, null, null)`
```
* What went wrong:
A problem occurred configuring root project 'lazy-failure'.
> Could not create task 'myTask' (CustomTask)
```

Because the realization is done through a provider, an additional exception is inserted in the stack. The [first exception is always shown regardless of its type, however, subsequent exceptions in the stack will only be shown if it's annotated with `@Contextual`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/exceptions/LocationAwareException.java#L148-L172). Exceptions thrown [here](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java#L241) and [here](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java#L241) are lost in the console output with lazy task configuration.

Note that build scans display the whole stack trace which is not affected by this issue: https://e.grdev.net/s/mrualunw7sp2w A possible solution could be to remove this `@Contextual` processing and show the console exactly how build scans do it.

### Context

See https://gradle.slack.com/archives/D375FG4UT/p1527170262000186

### Your Environment

 * Build scan URL:

**Comment by adammurdoch** [comment]
This is fixed in https://github.com/gradle/gradle/pull/6090.
