### ISSUE TITLE
How to customize compiler configurations and source locations in the new C++ plugin.

### ISSUE THREAD

**Issue by goldolphin** [gradle/gradle-native#712]
The new C++ plugin is good for me especially for its integration with maven publishing，thanks for the great job!
However, I cannot find any documents or examples about customizing compiler configuration and source locations. Could you please provide an example?
Here is my build.gradle with old cpp plugin, hope to know how to migrate to the new plugin.

```
plugins {
    id 'cpp'
    id 'maven-publish'
}

group = 'com.example'
version = '0.0.1'

publishing {
    repositories {
        maven {
            url = '../repo'
        }
    }
}

project.buildDir = './gradle-build'

model {
    toolChains {
        clang(Clang) {
            eachPlatform {
                cppCompiler.withArguments { args ->
                    for (int i = args.size() - 1; i >= 0; i--) {
                        if (args[i].equals("-I") && args[i+1].startsWith("/Library/Developer/CommandLineTools/SDKs")) {
                            args.remove(i + 1);
                            args.remove(i);
                        }
                    }
                }
            }
        }
    }
    binaries {
        all {
            cppCompiler.args "-std=c++11", "-Wno-deprecated-declarations"
            if (toolChain in Gcc) {
                cppCompiler.args "-O", "-DHAVE_PTHREAD", "-Wall", "-Werror", "-Wwrite-strings", "-Woverloaded-virtual", "-Wno-sign-compare", "-Wno-error=unused-function", "-Werror=non-virtual-dtor"
                cppLinker.args "-lpthread"
            }
            if (toolChain in Clang) {
                cppCompiler.args "-g", "-O0", "-DHAVE_PTHREAD", "-Wall", "-Werror", "-Wwrite-strings", "-Woverloaded-virtual", "-Wno-sign-compare", "-Wno-error=unused", "-Werror=non-virtual-dtor"
            }
        }
    }
    components {
        myModule(NativeLibrarySpec) {
            sources {
                cpp {
                    source {
                        srcDir "src"
                        include "**/*.cc"
                    }
                    exportedHeaders {
                        srcDir "src"
                        include "**/*.h"
                    }
                }
            }
        }
    }
}
```
@adammurdoch @big-guy pardon me for disturbing you guys, but I need some help.

**Comment by lacasseio** [comment]
Thanks @goldolphin for this issue. I feel this issue is already fixed with the new plugins and should be considered as a question. The documentation part is currently lacking and is tracked under another issue. At the moment, the documentation is fully executed through the [native-samples project](https://github.com/gradle/native-samples). I suggest you have a look at [this particular sample](https://github.com/gradle/native-samples/tree/master/cpp/swift-package-manager) to answer your question regarding source location. Don't hesitate to open issue for features you want to see in the new native plugins.

**Comment by goldolphin** [comment]
Thanks @lacasseio , I'll have a try. About compiler arguments, is there any samples?

**Comment by lacasseio** [comment]
I suggest you have a look at [this sample](https://github.com/gradle/native-samples/tree/master/cpp/simple-library).

**Comment by goldolphin** [comment]
@lacasseio Thank you very much.
