### ISSUE TITLE
Prepare lazy task API for 4.9 release

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#714]
This issue is a placeholder for the work we should try to get done for 4.9:

- A sample project with numbers, e.g. `gradle/gradle` or `perf-enterprise-large` or both.
- Make the feature visible to people in some form, yet to be determined.
- Not stable in 4.9 (so don't update all of the documentation and samples) but we wouldn't expect API to change much.
- Mention it is already being used in 4.8/4.9 (via the Java plugins).
- Instructions how to start using, and diagnose.
- Mention use cases: improving performance, can do validation in configuration blocks, etc.
- Make clear not for Android yet.
- Highlight build scans as a way to diagnose issues.

**Comment by big-guy** [comment]
- Release notes
- Convert google doc to public notes
- Sample with demonstrating improvements with lazy task configuration

**Comment by big-guy** [comment]
@gradle/native could someone take a look at the user chapter https://github.com/gradle/gradle/pull/5665?

You can run this locally with `gradlew userguideHtml` and opening `subprojects/docs/build/docs/userguide/avoiding_task_configuration.html`

I'll fill in the blog post tomorrow.

**Comment by lacasseio** [comment]
I added some comments.

**Comment by big-guy** [comment]
@lacasseio could you comment on https://github.com/gradle/blog/pull/176/files
