### ISSUE TITLE
Build author defines the source files of a Swift component

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#72]
Allow the Swift source files of a Swift executable or library to be defined in the build script, overriding the convention for where the source files can be found.

The customizations should be used both for compiling the component and by the Xcode project generation.

Add a sample to demonstrate this feature.

Test coverage:

- Can replace the convention
- Can add individual files.
- Can add directories.
- Two projects can share the same source directories.
- Ignores source files that are not swift source files.

**Comment by adammurdoch** [comment]
I'm proceeding for now using option 1 from the [design doc](https://docs.google.com/document/d/1lqxwe5e5-bFDuSi6OJdBPOfI-flwOVFMh4tmbNXBYXI/edit), on the assumption that it will be relatively easy to rework this to any of the other options.

**Comment by lacasseio** [comment]
I also think it's a good start for the direction we want to go. Thanks for putting the design doc together.

**Comment by adammurdoch** [comment]
I'm considering this done for now. Split out #105 for some later improvements.
