### ISSUE TITLE
Public API to allow plugins to define outgoing artifacts using the outputs of lazy tasks

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#723]
This should check that the task has exactly one output file and should defer resolution until `PublishArtifact.getFile()` is called.  This should work for tasks other than AbstractArchiveTask

**Comment by big-guy** [comment]
maybe the same as #760

**Comment by big-guy** [comment]
@ghale take a look to see if this can be closed.

**Comment by big-guy** [comment]
dupe of #760
