### ISSUE TITLE
Disallow adding a task or provider directly to a task container

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#729]
`DefaultTaskContainer` should own the lifecycle of all tasks it contains.  It should be 
 an error to call `addLater(Provider)`, `add(Task)` and `addAll(Collection<Task>)` on `DefaultTaskContainer`.

**Comment by big-guy** [comment]
This is a problem across many container types that do work vs describe data.

General rule:
If you have a create, shouldn't have an add.
If you have an add, shouldn't have a create.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/6041

Note that there is an issue with kotlin 1.2.41 where a task is being added using `tasks.add()`: https://github.com/JetBrains/kotlin/blob/1.2.41/libraries/tools/kotlin-sam-with-receiver/src/main/kotlin/org/jetbrains/kotlin/noarg/gradle/SamWithReceiverSubplugin.kt#L57  This issue is fixed in kotlin 1.2.60.  I've spoken with the kotlin-dsl guys and they are planning to integrate the latest kotlin-dsl (0.19.x, which uses kotlin 1.2.60) into Gradle before 4.10.  I've added a workaround for now that prevents us from throwing an exception in this case.  Once the new kotlin-dsl version is integrated, we should be able to just remove the workaround.
