### ISSUE TITLE
Make DefaultArtifactPublicationSet lazy

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#730]
We create `Jar` tasks and friends lazily now, but `DefaultArtifactPublicationSet` immediately realizes it when the artifact is added.  `DefaultArtifactPublicationSet` needs to be more lazy so that it only realizes the tasks when the default artifact is actually needed.

**Comment by ghale** [comment]
So, in looking at the current implementation of `DefaultArtifactPublicationSet`, I'm finding the rules it applies to be confusing.  I want to try to nail down what we think it should do.  Here's what it does today:

When an artifact is added directly to the `DefaultArtifactPublicationSet`:
- If no artifact has been added, then the artifact A is added to archives configuration (archives == [A]) and A becomes the "default" artifact.
- If the artifact being added is an ear E:
  - always replace the default artifact: archives == [E], default == E
- If the artifact being added is a war W:
  - If the default artifact is something other than a jar, ignore: archives == [A], default == A
  - If the default artifact is a jar, then replace: archives == [W], default == W
- If the artifact being added is a jar:
  - If there is already a default artifact, ignore: archives == [A], default == A
- If the artifact is something other than a jar/war/ear O:
  - always add: archives == [A,O], default == A

So, ear always replaces everything.  War can replace a jar, but nothing else.  Jar can never replace anything.  Other never replaces anything, but it always gets added unless it is added before an ear (in which case it gets replaced).  This last part seems wrong to me.

To make things more confusing, it behaves differently if artifacts are added directly to the archives configuration rather than to the `DefaultArtifactPublicationSet`:

When an artifact A is added to the archives configuration, it is first added to the archives configuration (archives == [A]) and then a rule fires to add it to the `DefaultArtifactPublicationSet`:
- If no artifact has been added to `DefaultArtifactPublicationSet`, then the artifact A becomes the "default" artifact.
- If the artifact being added is an ear E:
  - always replace the default artifact: archives == [E], default == E
- If the artifact being added is a war W:
  - If the default artifact is a jar, then replace: archives == [W], default == W
  - If the default artifact is something other than a jar, do nothing: archives == [A,W], default == A
- If the artifact being added is a jar J:
  - If there is already a default artifact, do nothing: archives == [A,J], default == A
- If the artifact is something other than a jar/war/ear O:
  - always add: archives == [A,O], default == A
  
So, ear always replaces everything.  War can only replace a jar, but it always gets added.  Jar can never replace anything, but always gets added.  Other never replaces anything, but it always gets added unless it is added before an ear (in which case it gets replaced).

And then there are other more complex cases that are strange (add two "other" artifacts and then an ear artifact, which results in the ear and only the second "other" artifact being in the archives configuration).

I think the above sort of follows the idea that applying multiple plugins (i.e. java, war, ear) just does the right thing, and adding to archives usually just adds an additional artifact, but I find the "ear replaces everything" part odd.  It seems like ear should only replace war or jar, but not anything else.

In any event, I want to ensure that this is the behavior we want (or discuss what it should be) before trying to replicate it in a lazy manner.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/5864

There are still some test failures that I'm working through, but I wanted to get this out for review.  The most questionable change in here is that when using `all()` or `withType()` we now don't fire those rules until the provider is realized (instead of immediately when the provider is inserted).  This is because we want `DefaultArtifactPublicationSet` to be evaluated lazily, but there is an `all()` rule set up on the artifact container which causes the default artifact to be evaluated and realized immediately when inserted (in turn causing the `Jar` task to be realized).  The question is whether removing this eager realization is the right thing to do.  It does break things that rely on this immediate execution (for instance the use case of "I want to create a task for every task of some other type and then reference those tasks in some eager way"), but I think there are reasonable workarounds for those cases.

If we feel like we need to keep the current behavior (i.e. immediate realization of providers when `all()` or `withType()` is used) then we'll need to rethink `DefaultArtifactPublicationSet` and allow it to be realized in some way without realizing the `Jar` task.

Thoughts?

**Comment by ghale** [comment]
Actually, after rethinking this, I realize that the change to `all()` and `withType()` are not necessary after all - we can simply change the `all()` rule in question to a `configureEach()` rule.  Not sure why that didn't occur to me before, but I've reverted those changes to their previous behavior.

**Comment by ghale** [comment]
This is ready for review.  

There is a minor performance regression (30-40ms) on the "get IDE model for largeMultiProjectJava for eclipse/IDEA" tests.  This is due to the change to make `DefaultRootComponentMetadataBuilder` use `ProjectState` to acquire mutable access to the project when resolving its artifacts to avoid concurrent realization of the jar task when other projects are also reaching in to resolve the project's artifacts.  This is something we were always doing unsafely before this change, but because nothing mutable was happening during artifact resolution (i.e. resolving an artifact would not result in task realization) this was not an issue.  Since the regression is minor and we know what is causing it (thread safety) I'm inclined to just accept it.

@big-guy Can you take a look when you have a chance?

**Comment by ghale** [comment]
After discussing with @big-guy, we're going to break these changes up into smaller increments to make it easier to review/improve.  The first two sets of changes:

https://github.com/gradle/gradle/pull/6054 - Fix a concurrency issue with resolving configurations at execution time
https://github.com/gradle/gradle/pull/6055 - Retain iteration order in domain object collections

**Comment by big-guy** [comment]
@ghale I merged the concurrency PR.  Once the new nightly is out, can we follow up with https://github.com/gradle/gradle/issues/5961 and see if it's fixed?

**Comment by ghale** [comment]
Cool.  Will do.

**Comment by ghale** [comment]
There's still some test coverage to add, but the next PR is ready to start reviewing:

https://github.com/gradle/gradle/pull/6148 - Allow domain object collections to accept providers of `Iterable`

**Comment by ghale** [comment]
Next PR: https://github.com/gradle/gradle/pull/6252 - Allows providers to have changing values

**Comment by ghale** [comment]
Finally: https://github.com/gradle/gradle/pull/6387 - Make `DefaultArtifactPublicationSet` use a lazy provider

**Comment by mkobit** [comment]
I know it isn't entirely related, but I just went down the extremely surprising behavior described at https://github.com/gradle/gradle-native/issues/730#issuecomment-395493684 . I was trying to understand why `assemble` ran my other artifact's tasks even though I didn't attach it to `archives` or `assemble`. I wrote it up as a forum post at https://discuss.gradle.org/t/why-does-assemble-run-my-task-when-it-is-not-attached-to-the-archives-or-default-configurations/28718/3 before finding this.

**Comment by ghale** [comment]
@mkobit Just to close the loop on that comment, in the near future we'll be retiring `DefaultArtificaPublicationSet` and it's not-so-intuitive rules along with the publishing mechanisms in `BasePlugin` in favor of the ivy-publish/maven-publish plugins, so this behavior will just go away.  For the short term, we'll keep the legacy behavior since it's been there for some time and some logic may be depending on it (regardless of its confusing logic).

**Comment by mkobit** [comment]
Thanks @ghale for the follow up. Looking forward to some more alignment for publishing and cross-project dependencies.

**Comment by oesolutions** [comment]
@ghale, IMO the behaviour demonstrated in the forum post by @mkobit makes sense. I've written many a build that relies on the fact that the `assemble` task causes the artifacts of **any** configuration to be generated, ie their tasks are executed. Are you suggesting that this behaviour will evolve into something solely based on `publishing`?

**Comment by ghale** [comment]
Yes, we plan to improve the publishing plugins so that there aren't any gaps and deprecate the whole legacy publishing infrastructure and mechanisms.  I'm not sure what that would mean for the `assemble` task (if anything).  I don't have a ton of insight into what is planned here just because I've only been on the edges of the conversation.  @oehme Can you provide a little more detail into what the plans are (perhaps on https://github.com/gradle/gradle/issues/4612)?

**Comment by oesolutions** [comment]
OK, I thought "legacy publishing" would only relate to the `uploadArchives` task and `archives` configuration, but it sounds like it may also includes artifacts of other configurations, which are used when resolving project dependencies (in my mind I didn't consider that to be "publishing").
