### ISSUE TITLE
`Task#getDependsOn().remove(Task)` regression in Gradle 4.8

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#738]
See https://github.com/gradle/gradle/issues/5730

In a nutshell, because lots of core task were converted to use lazy task configuration, the task dependencies are now `TaskProvider` instead of `Task`. Given previous code such as:
```
Task a = tasks.getByName("a")  // now created via TaskContainer#register`
Task b = tasks.getByName("b")  // now depends on 'a' via TaskProvider
b.dependsOn.remove(a)
```
The task dependency will no longer be removed. This consist of a regression in 4.8 at the same time as relying on the internal implementation of how task 'a' is created and wired with 'b'.

**Comment by big-guy** [comment]
`Task.getDependsOn()` returns a `Set<Object>` -- so I think users were always at the mercy of however we wired things together.  e.g., this sort of thing wouldn't work either:

```
b.dependsOn a.outputs
b.dependsOn.remove(a)
```

I think some options are...
1) Deprecate/prevent modifying dependencies via `getDependsOn`
2) Make `getDependsOn` return `Set<Task>` so you can at least reliably know what you're removing it.
3) Make removal "smarter" and try harder to remove what "someone meant".  There be dragons.

**Comment by big-guy** [comment]
`remove(Task)` should work when there's a `TaskProvider` that provides the given task.

We should deprecate this behavior.

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/gradle/pull/5970
