### ISSUE TITLE
Demonstrate API only (aka header only) library

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#739]
This sample should demonstrate:
* How to build one ([no building should be required](https://github.com/gradle/gradle-native/issues/447))
* How to publish the library
* How to consume the library

**Comment by big-guy** [comment]
Short of implementing #447

**Comment by lacasseio** [comment]
A sample has been [written here](https://github.com/gradle/native-samples/tree/lacasseio/header-only-library/cpp/header-only-library).
