### ISSUE TITLE
Allow projects to be built from Xcode when `gradle` executable is not in the path

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#74]
I don't have the `gradle` executable in the `PATH` that is used by Xcode when it builds a project, which means that the build fails and I have to manually configure Xcode the point to whichever Gradle installation I want it to use.

It would probably be better to configure Xcode to use the absolute path to whichever Gradle installation was used to generate the Xcode project file, instead of "whatever 'gradle' you find in the PATH". Another option would be to insist that the project use the Gradle wrapper, and point to this.

**Comment by lacasseio** [comment]
This fix is bundled with PR https://github.com/gradle/gradle/pull/3004.
