### ISSUE TITLE
tasks.withType is not applied from external script if some plugins are applied

### ISSUE THREAD

**Issue by radistao** [gradle/gradle-native#742]
(see https://github.com/radistao/gradle-withType-bug-report for reproducing steps)

### Expected Behavior
`tasks.withType(com.github.spotbugs.SpotBugsTask)` closure must be called during configuration phase ***regardless*** of other included plugins in main script file.

### Current Behavior
`tasks.withType(com.github.spotbugs.SpotBugsTask)` closure is not executed when:
  - _spotbugs_ configuration carried out to an _external script_ (`spotbugs.gradle`)
  **and**
  - some other plugins are included to the classpath in the _main script_ (`build.gradle#buildscript#dependencies`)
  **and**
  - those plugins are not duplicated in the classpath of the _external script_ (`spotbugs.gradle#buildscript#dependencies`)

### Context
  - We can't configure [SpotBugs](http://spotbugs.readthedocs.io/en/latest/gradle.html) plugin (for example, generate HTML reports instead of XML), so that:
    ```
    reports {
        xml.enabled = false
        html.enabled = true
    }
    ```
    is never applied and all the reports are generated as XML files

 - In the same time, there are some notes:
    - we still can call explicit configuration blocks `spotbugsMain`, `spotbugsTest`, `spotbugsTestIntegration` and so on - this works but requires duplication for every sources configuration
    - `tasks.all` works like expected and executed for all tasks, including SpotBugs descendants
    - we can duplicate all plugins configuration in the external script too, but this created redundant code duplication and mess in the external scripts with unrelated plugins including.

### Steps to Reproduce (for bugs)

  - https://github.com/radistao/gradle-withType-bug-report (see the [README](https://github.com/radistao/gradle-withType-bug-report#gradle-external-script-configuration-bug-report) in the repo)

### Your Environment
```
Gradle 4.8.1
Revision:     0abdea078047b12df42e7750ccba34d69b516a22
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64
```
Also reproduced on Ubuntu with `JVM 1.8.0_171`

**Comment by big-guy** [comment]
@radistao did this work before 4.8?

**Comment by radistao** [comment]
@big-guy i didn't try on earlier versions

**Comment by radistao** [comment]
checked on gradle versions 4.5-4.8 - behavior is the same

**Comment by bamboo** [comment]
Because the script plugin `ClassLoader` is isolated from the project buildscript `ClassLoader`, the `java.lang.Class` instances representing the type `com.github.spotbugs.SpotBugsTask` are different, thus the `withType(...)` call won't match anything.

The tasks created by the plugin are defined with the `Class` loaded from the [root buildscript classpath](https://github.com/radistao/gradle-withType-bug-report/blob/master/build.gradle#L8) and the script plugin is using the one loaded from [its own classpath](https://github.com/radistao/gradle-withType-bug-report/blob/master/gradle/spotbugs.gradle#L8).

Tangentially to this discussion, [applying the plugin by id in the script plugin](https://github.com/radistao/gradle-withType-bug-report/blob/master/gradle/spotbugs.gradle#L12) only works because the plugin is already available in the project classpath (due to gradle/gradle#1262).

**Comment by radistao** [comment]
no, the problem not in scripts/classloader/classpath separating: in the commits [e6e9217](https://github.com/radistao/gradle-withType-bug-report/commit/e6e92179b18a38df7dc1cec3de62173ffb92e2de) and [8ac546b](https://github.com/radistao/gradle-withType-bug-report/commit/8ac546b) the files are also separated, and it works fine. The problem appears only when [spring-boot-gradle-plugin](https://github.com/radistao/gradle-withType-bug-report/blob/master/build.gradle#L7) is applied! 

In all code snippets you mentioned above (from the repository master) **work like expected**, but  if `spring-boot-gradle-plugin` is not included **in all scripts** - `spotbugs-gradle-plugin` doesn't work

**Comment by big-guy** [comment]
@bamboo could we move this to gradle/gradle?

@oehme does this look suspicious?

**Comment by bamboo** [comment]
@big-guy 👍

**Comment by oehme** [comment]
As @bamboo correctly noted, this is due to the classpath separation between script plugins and the project build scripts. This only worked accidentally in your first case, because both scripts had the exact same classloader hierarchy and thus our classloader caching gave them the same classloader. This is a performance optimization and nothing to be relied on. 

In short: You cannot use `buildscript` like this, the classloader separation won't allow that. Instead, put that external dependency (spotbugs) into the `dependencies` block `buildSrc/build.gradle` and it will be in the highest classloader in the hierarchy and visible to every script.

**Comment by radistao** [comment]
@oehme @bamboo 
not sure this works, i tried in this commit: https://github.com/radistao/gradle-withType-bug-report/commit/03d31f9c57eb39919f3974961d361f86c84682f3

now it complains:
> ...gradle-withType-bug-report/gradle/spotbugs.gradle' line: 7
>
> * What went wrong:
> A problem occurred evaluating script.
> Could not get unknown property 'com' for root project 'test-spotbugs' of type org.gradle.api.Project.

Which means now `SpotBugsTask` is not available at all. Note: **`com.github.spotbugs.SpotBugsTask`** doesn't work for the same reason.

**Comment by oehme** [comment]
You are still putting the dependency in the root project, which I explained doesn't work. If you want it to work from a script, then *everything* about spotbugs needs to be there, including the dependency declaration. Als you can't use plugin IDs in script plugins, you'd have to use the class name.

That's why I gave you the more convenient option of putting it in buildSrc, because then it's just visible everywhere.

**Comment by radistao** [comment]
> you are still putting the dependency in the root project, which I explained doesn't work.

but i thought you mentioned above:
>Put spotbugs plugin dependency into the dependencies block of buildSrc/build.gradle

Sorry for annoying, i'm completely confused now ((

My question is:
Is there a way (with old or new plugins dependencies management) to configure plugins in separate files/scripts _without duplication unrelated plugins_ in those scripts?
So, for example, what could be done in the example repository i attached to configure the spotbugs plugin and make it independent from spring-boot one?  Could you give a code snippet?

Thanks a lot.

**Comment by oehme** [comment]
Yes, there are two ways, exactly as I described above.

1. Put all spotbugs configuration into the spotbugs script. This includes the `buildscript` dependency. Then you cannot reference it from anywhere else.
2. Put the spotbugs plugin dependency into the `dependencies` block of [**buildSrc**](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources) (NOT your root project). Then it'll be visible to everyone.

**Comment by radistao** [comment]
ah, sorry, i misunderstood these are 2 options, not 2 steps of the same option.

Ok, then is it correct first option?
https://github.com/radistao/gradle-withType-bug-report/commit/68b271390f8f5abd5a96a7eda82008726b29afd2

>Put all spotbugs configuration into the spotbugs script. This includes the buildscript dependency. Then you cannot reference it from anywhere else.

I put everything related to spotbugs to `spotbugs.gradle`. But i still have:

> gradle-withType-bug-report/gradle/spotbugs.gradle' line: 11

> * What went wrong:
> A problem occurred evaluating script.
> Plugin with id 'com.github.spotbugs' not found.

**Comment by oehme** [comment]
You can't use plugin IDs in script plugins, you'd have to use the class name. That's why I gave you the more convenient option of putting it in buildSrc, because then it'll work as desired.

**Comment by radistao** [comment]
>you'd have to use the class name

How to do this in the script file?

**Comment by oehme** [comment]
`apply plugin: com.foo.Bar //look the name up in the spotbugs source code`

As I said, I recommend the buildSrc solution.

**Comment by radistao** [comment]
> apply plugin: com.foo.Bar //look the name up in the spotbugs source code

but that's exactly how i'm trying to apply it in the version i mentioned above:
https://github.com/radistao/gradle-withType-bug-report/blob/68b271390f8f5abd5a96a7eda82008726b29afd2/gradle/spotbugs.gradle#L11

and this causes the error on line 11:

> Plugin with id 'com.github.spotbugs' not found.

**Comment by radistao** [comment]
@oehme 
ok, i also tried the suggestion with `buildSrc/build.gradle` config:

https://github.com/radistao/gradle-withType-bug-report/blob/18ceb779bd29ed24bb5e148d66c776d1351b7eb6/buildSrc/build.gradle

https://github.com/radistao/gradle-withType-bug-report/blob/18ceb779bd29ed24bb5e148d66c776d1351b7eb6/gradle/spotbugs.gradle

Now this causes the error:

>Script '/gradle/spotbugs.gradle' line: 9
> * What went wrong:
> A problem occurred evaluating script.
> Could not get unknown property 'com' for project ':buildSrc' of type org.gradle.api.Project.

and no matter where i include `apply plugin: 'com.github.spotbugs'` line: in the `buildSrc/build.gradle` or `gradle/spotbugs.gradle` - the result is the same.

**Comment by oehme** [comment]
You're still using the plugin ID. The class name is `com.github.spotbugs.SpotBugsPlugin` and class names are written without quotes.

For the buildSrc alternative: I didn't say move all the logic there, I just said move the spotbugs dependency there.

```
//buildSrc/build.gradle
repositories {
  gradlePluginPortal()
}

//this will make it visible to all scripts in your build, as well as code in buildSrc
dependencies {
  compile "gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:1.6.2"
}
```

**Comment by radistao** [comment]
OMG, finally this works if plugin is defined in `spotbugs.gradle`:

`apply plugin: com.github.spotbugs.SpotBugsPlugin`

**Thanks a lot!**

But still can't configure "global" plugins applying from `buildSrc`. Now i have all plugins defined in [`buildSrc/build.gradle`](https://github.com/radistao/gradle-withType-bug-report/blob/939cec457aea6d1bd8b9d778e9e5ef5281759276/buildSrc/build.gradle) and trying to apply them in [`spotbugs.gradle`](https://github.com/radistao/gradle-withType-bug-report/blob/try-buildSrc/gradle/spotbugs.gradle#L1-L5):
```
// tried all of these:
//apply plugin:  com.github.spotbugs
//apply plugin: 'com.github.spotbugs'
//apply plugin:  com.github.spotbugs.SpotBugsPlugin
//apply plugin: 'com.github.spotbugs.SpotBugsPlugin'
```

Neither of them work throwing exception:  <code><i>com</i> (or <i>'com.github.spotbugs[.SpotBugsPlugin]')</i> not found</code>

**Comment by oehme** [comment]
Please paste the code for buildSrc exactly as I showed. No buildScript block around it. buildSrc is a special project that provides build logic. So plugin dependencies are normal project dependencies for it.

**Comment by radistao** [comment]
ah, my bad again - sorry.

Now i see the picture, thanks a lot for the support!

**Comment by asarkar** [comment]
For anyone stumbling across this thread, note that the following works even if you're using an external buildscript file
```
tasks.matching { it.name.startsWith("spotbugs") }.each { }
```
