### ISSUE TITLE
Fix `dependsOn tasks.withType(...)` triggering creation of all tasks

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#745]
https://github.com/gradle/gradle/issues/5827

**Comment by big-guy** [comment]
Integration test where we iterate over a filtered task container and it should not force all tasks to be created.

**Comment by lacasseio** [comment]
PR https://github.com/gradle/gradle/pull/5937 fix strictly this use case. We may want to discuss this a bit further to ensure we can fix this more globally.
