### ISSUE TITLE
Provide convenience methods for setting default values for inputs/outputs

### ISSUE THREAD

**Issue by melix** [gradle/gradle-native#747]
### Context

When giving the provider API a try, in the [plugin to report incubating APIs](https://github.com/melix/gradle-incubating-plugin), I was surprised to find that it wasn't obvious how to set a default value for an output directory, or an input file. I liked the fact that I could set all my properties as "final not null", but doing so proved to be a challenge if you also want to set a default value.

So, I found a pattern (in Kotlin) that was kind of doing what I need, and wondered if we couldn't do better:

```
    @OutputFile
    val htmlReportFile = newOutputFile().also {
        it.set(project.layout.buildDirectory.file("reports/all-incubating.html"))
}
```

The use of `also` lets me get the result of the `newOutputFile()` call, and immediately set the default value provider, but I think we should probably have a way to do it directly. Something like:

```
@OutputFile
val htmlReportFile = newOutputFile(project.layout.buildDirectory.file("reports/all-incubating.html"))
```

and probably also with an explicit provider:

```
@OutputFile
val htmlReportFile = newOutputFile {
   // lazy provider
}
```

The same is needed for input files, but inputs/outputs in general: look at this code too: https://github.com/melix/gradle-incubating-plugin/blob/master/src/main/kotlin/org/gradle/plugins/incubating/IncubatingApiAggregateReportTask.kt#L19-L22

Is there a better pattern? I think if there's a better one it needs to be documented right now, because it wasn't obvious to me, just reading the documentation.

**Comment by lacasseio** [comment]
@melix It seems that [`Property#convention`](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html#convention-T-) solve your use case. Reopen an issue on [`gradle/gradle`](https://github.com/gradle/gradle) if you think otherwise.
