### ISSUE TITLE
Group source files by role in generated Xcode projects

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#75]
Currently, the Xcode generation adds every source file, including headers and the build scripts, in an ungrouped list as children of the Xcode project.

Instead, I think it would be clearer to group the files by their role within the project - eg `Source`, `Headers`, `Build`, etc.

**Comment by adammurdoch** [comment]
This is also useful when creating new files from Xcode, as (it looks like) a directory can be associated with a group and new files default to being created in this directory. Right now, creating a new source file default to adding the new file to the project directory, where Gradle won't see it.

**Comment by lacasseio** [comment]
I went with a strictly grouping strategy as opposed to trying any automatic grouping based on the directory. A user can add files directly to the different group, chose the on-disk location, and append them to the indexing target.
