### ISSUE TITLE
Evaluate usefulness of mentioning `-Dorg.gradle.internal.tasks.stats` in userguide

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#751]
Regarding the [_How do I know if it’s working?_ section](https://docs.gradle.org/nightly/userguide/task_configuration_avoidance.html#sec:how_do_i_know_its_working) of the new chapiter.

@etiennestuder asked:
> Do we need this or can we fully rely on build scans instead?

From @lacasseio personal experience when converting `gradle/gradle` build:
> The build scans don't give the same level of statistics. We should evaluate how useful are those stats during the migration. Personally, I haven't used those stats.

@big-guy Do you think we could use the [build scan stats configuration performance tab](https://scans.gradle.com/s/byuclqvfuirni/performance/configuration#summary-task-totals)?

If we found those not useful, we should remove or alter the section to prevent mentioning it.

**Comment by lacasseio** [comment]
@etiennestuder Do you know if the GE team found those stats useful?

**Comment by big-guy** [comment]
My take is to leave this in for 4.9 so we can nudge people in the right direction and then remove it

**Comment by lacasseio** [comment]
Sounds good, we can evaluate this for the next release. I would still want to keep this open to get feedback from GE, then we can open another issue for 4.10.

**Comment by breskeby** [comment]
I didn't found the stats very helpful to be honest. What helped was the general list of task types that have been realized. For example when when seeing checkstyle tasks being realized, I knew I need to revisit our code quality logic in the build. Another example was that it showed Delete tasks being realized. That helped me to narrow down a problem in our clean task custom ordering issue. 
I think you guys have more experience with this and I don't see harm to leave it for now. In general we should try to push people to use build scans to narrow down task creation issues and provide feedback of if _that_ helped them. IMO there's no harm for keeping the property in cases where build scans are not available, but I would not add this flag to any official documentation.

**Comment by ldaley** [comment]
I haven't found any need for those stats, with access to build scans.

**Comment by lacasseio** [comment]
Great thanks for the feedback.

**Comment by breskeby** [comment]
@oehme would be great if you can provide some feedback if you think this is good to go to be merged into master.

**Comment by mark-vieira** [comment]
I didn't even know this flag existed. I used build scans exclusively for debugging and tracking down regressions.

**Comment by breskeby** [comment]
yes
