### ISSUE TITLE
Demonstrate how to export macros for libraries

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#755]
Exporting macros is something library authors sometimes depends on. Although not supported out of the box, it is possible to expose and publish macros.

**Comment by lacasseio** [comment]
Here are some steps required to demonstrate this capabilities:
- Create a task for each variant that will generate the exported macro manifest. Each task should be configured with the macros required to be exported. The input of this task would be the macros and anything that is related to variant. The output should be a file containing the macros values (could be just a simple command line snippet representing the macros, i.e. `-Dmacro1=value1 -Dmacro2 ...`. This result should be exposed via a getter.
- Wire the generated command line snippet to the right compile task. You don't need to add a dependency. You only depend on the configuration of the task when you are in the same build.
- Add a resolve and consume configuration for the exported macro for each variant. Make sure you add set the usage as something like exported macros. One will be wire to the task that generates the file containing the command line snippet of the exported macros. The other configuration will be used to consume the other exported macro files.
- Wire the consume configuration to the right compile task. You will need to add a dependency on the configuration from the compile task in case you use composite build so the task dependencies are correctly wired in.
- Add an artifact to publish command line snippet files together with the other artifacts.

**Comment by amz-shahji** [comment]
Not all macros are "exported" and should/need to be transitive. Need to define "publicMacros" (similar to public and private headers).

The solution outlined is kind of opaque to the consumer. The user never sees the macro being appended to the command line. How about generating a prefix header file which is included on the command line. The generated prefix header can be part of the published headers package and that way user has visibility into what the exported macros are (especially, in VS projects). At the consumer front, a new header file could be generated which includes all the other dependent prefix files (and its own public macros). This newly generated file could be used as the prefix file for its own build.

Thoughts?

**Comment by amz-shahji** [comment]
@lacasseio Any thoughts on the prefix header suggestion? Pros/Cons?

**Comment by lacasseio** [comment]
For the prefix header, it's just a matter of taste at that point. The idea is to have a producer and a consumer. The producer side could be modeled as a custom DSL that automatically adds the macros back to the binary (either through a prefix header or directly on the `CppCompile` task) and publishes the file (or other means). The consumer can then either consume the published values and generate a prefix header or pass them to the `CppCompile` task. The transitivity can be worked out through the dependency management using resolution strategies.

The strategy used prefix header or command line arguments are just implementation details at this point.

**Comment by lacasseio** [comment]
This issue is all about demonstrating how exporting macros can be done at the moment aimed toward a specific use case around why you would want to export macros to consumers. The use case is yet to be established. We can use this issue to establish the various use case for such a feature.

We won't start working on a core feature until we have a demonstrable sample with a good use case. There are currently at least 2 different ways to implement this feature but they lack *what* we are trying to achieve here. Why exporting the macros is important. Let's work on 1) answering those questions, 2) write a sample to show where Gradle is lacking to solve the use cases and 3) move forward with an implementation recommendation.

**Comment by amz-shahji** [comment]
@lacasseio More information (and answers) here on an initial pull request with a proposal for basic DSL change. https://github.com/gradle/gradle/pull/7611

Could we please get some input on this so we can move forward. Its been blocked for more than a week now. This is a blocker issue for us which we cannot solve with an external plugin implementation, at least not without replicating lot of the dependency logic from gradle. This issue needs Gradle API support.

**Comment by lacasseio** [comment]
I wrote a [quick sample to demonstrate transitive macro export from libraries](https://github.com/gradle/native-samples/tree/lacasseio/public-macros/cpp/publish-macros). By no means it's a complete solution but this should show a direction to move forward as an external plugin. Unfortunately, the sample does use some internal API which is been identified as where we should concentrate our effort since it's being a recurrent pattern with early adopters. The internal APIs are only needed for publication inside a binary repository. Within source dependencies, composite build or multi-project build, this publication internal API is not required. It was added for the sake of completeness.

The concept of public/private macros seems, at this stage, more of an escape hatch to the core issue and use cases exposed on the PR. We may end up implementing macro scoping, however, at the moment, we don't have enough design information to move forward with such implementation. We understand those use cases used to be solved by exporting macros with other build systems, however, we rather get to the bottom of the core issue than providing the same solution as other build systems. That doesn't mean you can't export macros as you would with other build systems. The sample demonstrates this particular solution. More work would need to be accomplished to be usable in all the exposed use cases which are outside the demonstration.

We can work together on improving the sample to demonstrate what you require specifically for exporting macros from libraries. Such feature won't be added as it is demonstrated in the sample.

**Comment by amz-shahji** [comment]
@lacasseio - Your sample was a very good demonstration of how to extend gradle. Appreciate your time in putting this together.

As you already mentioned in your comment above, that the sample is not complete in anyway. Our immediate blocker is to publish different set of macros for static vs. shared linkage and debug vs. release build types. So, is there an example plugin or any documentation that I can use as a guide to extend your implementation. For sake of completeness, I need to account for the following -

* Configuration
* Target OS
* Target Arch
* Build Type
* Library linkage
* Flavor - are these supported with the new software model?
* Selected compiler (Clang vs. MSVC) and SDK

Appreciate some pointers on where/how to get started.
