### ISSUE TITLE
Disallow the use of `afterEvaluate`-like hooks from any lazy configuration action

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#768]
We're currently preventing this for task actions only.

**Comment by big-guy** [comment]
We should do this for artifacts

**Comment by big-guy** [comment]
Allow allprojects/subprojects

**Comment by ghale** [comment]
I've got a first round of changes here: https://github.com/gradle/gradle/pull/6437

This deliberately only addresses adding checks for other project-related hooks.

**Comment by ghale** [comment]
@lacasseio Do you mind taking a look at the PR above ☝️ ?

**Comment by lacasseio** [comment]
The PR is merged, is this done enough to considered closing?

**Comment by ghale** [comment]
No, there is also the work to pull these checks up so that they get called for any lazy action and other types.  This is likely going to be a bunch of little changes, so I wanted to split that off as a separate set of changes.

**Comment by big-guy** [comment]
Find other issue about Gradle methods-- that should be done.  this is not started

**Comment by big-guy** [comment]
@lacasseio if you've started this, please assign/move it, thanks!

**Comment by lacasseio** [comment]
PR https://github.com/gradle/gradle/pull/6939
