### ISSUE TITLE
Add support for architecture/platform as a variant in new plugins

### ISSUE THREAD

**Issue by iskiselev** [gradle/gradle-native#777]
Is it possible to build for different architectures/platforms/flavors with new cpp-application plugin?
For example, how it is possible to create x86/x64 build on windows for [sample application](https://github.com/gradle/native-samples/tree/master/cpp/application)?

**Comment by k-mack** [comment]
I was looking to build x86 and x64 variants as well; but AFAICT from the [CppApplicationPlugin](https://github.com/gradle/gradle/blob/v4.9.0/subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppApplicationPlugin.java) and [DefaultToolChainSelector](https://github.com/gradle/gradle/blob/v4.9.0/subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/toolchains/DefaultToolChainSelector.java), the platform is equal to the host platform and is not configurable yet.

Actually, @big-guy touched on this in a post on the forum (see https://discuss.gradle.org/t/alternate-toolchain-with-the-new-native-plugins/27765/2).

**Comment by lacasseio** [comment]
In fact, everything that is related around variants of an application or library is important use cases. The architecture will be the first one but in the future, variants will be extensible and individually modeled. We feel it's much stronger to offer a way to model a variant than relying on simple strings.

**Comment by adammurdoch** [comment]
I think there are 2 basic approaches to modelling this:

1. A component has two separate properties: a set of target operating systems (+versions) and a set of target architectures and by convention we create binaries for the each member of the cross product of OS x architecture.
2. A component has a single property that represents the set of target machines, where a target machine is a domain object that defines an operating system (+version) and architecture and by convention we create binaries for each target machine.

I'd probably go with option 2, as I think many components do not target every combination of OS + architecture, and because this option allows more specific details about the machine to be added later.

Given this, there are 2 basic options for the DSL/API:

1. Use a `SetProperty<TargetMachine>` and some factory methods.
2. Use a `DomainObjectContainer<TargetMachine>` and some registration methods (or perhaps factory methods instead).

Some examples:

```
// A SetProperty + factory methods
application {
    targetMachines.add(machines.windows.x64)
    // Maybe there are some DSL conveniences, but these should be mixed in for all set properties rather than ad hoc
    targetMachine machines.windows.x64
    targetMachines {
        add(machines.windows.x64)
    }
}

// DomainObjectContainer
application {
    targetMachines.windows(Architecture.x64)
    targetMachines.add(OperatingSystem.Windows, Architecture.x64)
    targetMachines.register {
        operatingSystem = OperatingSystem.Windows
        architecture = Architecture.x64
    }
    // or with factory methods
   targetMachines.add(machines.windows.x64)
   // there may be DSL conveniences, but again, these should be mixed in for all containers
}
```

**Comment by adammurdoch** [comment]
We should probably limit this issue to just the building and publishing of binaries of apps and libraries, and split out separate issues for unit testing and IDE import (including tooling model).

**Comment by ghale** [comment]
Thanks for the brain dump, @adammurdoch.  I spent some time looking at this the other day and started writing up some options fairly similar to what you've detailed above.  I think the single property approach is the right one, too.

**Comment by ghale** [comment]
There's a bunch of test coverage I need to add, but a first stab at this is here: https://github.com/gradle/gradle/pull/7545

Feedback is appreciated.

Some assumptions:
- The default architecture when not specified is the current host architecture.  It might make more sense here to just use a convention of "x64".
- User can specify nothing, operating system only or operating system/architecture.  The user can _not_ specify architecture only.
- To build with a toolchain that does not match the current host architecture, the user must explicitly declare the target machine (i.e. we will not automatically discover and use a 32-bit toolchain on a 64 bit host if no 64-bit toolchain is found).
- The cpp-unit plugin implemented operating system support differently than the other plugins - i.e. it didn't iterate over the configured operating systems, it just built for the current host operating system.  I didn't change this yet (it only builds for the first target machine that matches the current operating system), but it seems to that this should be converted to do the same thing as the other plugins: iterate over the target machines and add a variant for each that is buildable.  Is there any reason why I shouldn't do this?

**Comment by ghale** [comment]
As fallout from test coverage and review feedback, I wanted to document a few more assumptions that have been made:
- When selecting the "development binary" we always favor current host/current architecture.  If current host/arch is not targeted at all, then we just select the first variant for the current host.
- We didn't have any platform selection for the Swift toolchain, so it would just return the local toolchain for any target platform it received.  It doesn't seem like cross-platform compiling is a thing with swift right now, so for the short term, I made it only accept current host/current architecture.  The idea is that if the cross-platform use case emerges in the future, we can handle this more intelligently.
- If a dependency does not target the same platform as a consumer is building for (e.g. a consumer building for x64 has a dependency on a library that only targets x86), this results in an error.

**Comment by ghale** [comment]
Ok, I _think_ I've addressed all of the review comments and rounded out the test coverage.  https://github.com/gradle/gradle/pull/7545 is ready for another look.

**Comment by big-guy** [comment]
I think our follow up can happen in the split out issues now
