### ISSUE TITLE
Support generation of accessors for container elements in Kotlin DSL

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#782]
For Kotlin DSL we'd like to be able to generate accessors for the elements of container, for example:

```
tasks.compileJava { ... }
tasks {
    compileJava { ...  }
}
```

Currently there is no API to allow the Kotlin DSL extension generation to query the name and type of each element in a container without realizing each element. We should add an API to allow this.

**Comment by big-guy** [comment]
This is needed for all named containers

**Comment by big-guy** [comment]
PR: https://github.com/gradle/gradle/pull/6142

@adammurdoch Could you take a look at this? I think this may be close enough for getting the TaskContainer to work as we expect, but we need more effort to make any named domain object container to work.

The main problem is that we leak internal types for domain object containers that add directly to the container (via `add(object)`) or containers that use a factory to create instances with the eager APIs.  We lose the information about which type was originally requested and can only see the instance/its implementation type. We also lose this information when a domain object is realized.

It seems like the way to fix this might be to step back from the current domain object collection hybrid of eager/lazy objects and push everything into a collection of Providers that maintain the information we need.  But maybe we treat that as a debt we need to pay down as a separate issue and get this into the Kotlin DSL team's hands now.  WDYT?

**Comment by adammurdoch** [comment]
The problem with leaking internal types is that many of them will be generated as runtime, so if we generate a bunch of Kotlin code from these then that code will not compile.

Instead of leaking internal types, we should do exactly the same thing as the extension container does in this scenario (by extracting this logic somewhere and reusing it): https://github.com/gradle/gradle/blob/1e2fbacd6ffdf07b39d153307824cf5408b15b04/subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultConvention.java#L243

Later, we can make this better by wrapping each element in a provider that can track state like this more accurately.

**Comment by adammurdoch** [comment]
We should merge that logic with the logic in `DslObject`, so that there's only one way to reverse engineer the public type of something.
