### ISSUE TITLE
Disallow registering hooks on the `Gradle` object by lazy configuration action

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#786]
This issue is a follow-up to https://github.com/gradle/gradle-native/issues/734

### Expected Behavior

The following hooks should be disallowed from lazy configuration action:
- [ ] `gradle.beforeProject(Closure/Action)`
- [ ] `gradle.afterProject(Closure/Action)`
- [ ] `gradle.buildStarted(Closure/Action)`
- [ ] `gradle.settingsEvaluated(Closure/Action)`
- [ ] `gradle.projectsLoaded(Closure/Action)`
- [ ] `gradle.projectsEvaluated(Closure/Action)`
- [ ] `gradle.buildFinished(Closure/Action)`
- [ ] `gradle.rootProject(Action)`

We should consider listeners too:
- [ ] `gradle.addProjectEvaluationListener(listener)`
- [ ] `gradle.addListener(listener)`

### Current Behavior

All these hooks can be called from within a lazy configuration action which may create flaky build failure depending on what is executed.

### Open Questions
- Should we disallow adding and removing listener as well?

**Comment by big-guy** [comment]
I think it makes sense to restrict all of those (some of them aren't usable from the build script already, but we should just cover that).

I added the listener taking methods to the list. It seems like we should restrict these too.  Maybe the `removeListener` methods too.

**Comment by big-guy** [comment]
This was done in #768
