### ISSUE TITLE
Initial user guide content for the new C++ plugins

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#802]
Add some initial user guide content for the C++ plugins. The content doesn't necessarily need to be complete or very detailed, just enough to give people some idea of the basic usage and how to solve some common use cases.

**Comment by pioterj** [comment]
The new plugins should also be listed on https://docs.gradle.org/current/userguide/standard_plugins.html.

**Comment by big-guy** [comment]
dupe of #677
