### ISSUE TITLE
CME from lazy task creation when using composite builds

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#804]
Example:
https://builds.gradle.org/viewLog.html?buildId=14825861&tab=buildResultsDiv&buildTypeId=Gradle_Check_Quick_Java8_Oracle_Linux_ide

I've not been able to reproduce this locally, but Gary and I think we've tracked it down to the [`BuildOutputCleanupRegistry`](https://github.com/gradle/gradle/blob/3b15ec768759e3ec9b238bef7becb46e6e3ea39a/subprojects/core/src/main/java/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistry.java#L27) realizing `clean` tasks at the same time as `:ideaModule` and `:buildB:b1:ideaModule` executes.

This blocks 4.10

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/6234

**Comment by ghale** [comment]
Merged and should be in 4.10-rc-1.
