### ISSUE TITLE
Spike initial XCTest integration with Gradle

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#81]
@lacasseio commented on [Tue Aug 08 2017](https://github.com/gradle/gradle-native-private/issues/45)

---

@adammurdoch commented on [Tue Aug 08 2017](https://github.com/gradle/gradle-native-private/issues/45#issuecomment-321117810)

One question I would love an answer for is what options we have to for test discovery. Something that is very, very useful in the JVM domain is that I can simply add a test class into a particular conventional location and that test is then made available for execution from Gradle and the IDE. It would be great to offer this kind of capability in the native domain as well.

**Comment by lacasseio** [comment]
XCTest framework works by compiling a set of source files into a bundle. This bundle can then be executed by passing a filter on which test to execute. If we add a file containing tests within the location that Gradle expect test source sets to be, it will get compiled inside the bundle and will be executed. The only limitation we are having is listing tests which prevent us from running them in parallel. We could use XCTool from Facebook or we could do a bit more research on how to achieve the same by linking additional code just like we do for CUnit. Since the IDE delegate compilation to Gradle, the same behavior will be available.

**Comment by lacasseio** [comment]
The spike as of now is able to build the bundle and execute the test from Gradle. It publishes the result in the build scan. However, the detail view doesn't show test information. It seems to be hard coded to only show JUnit or TestNG result. I tried fudging the requirements to workaround but wasn't able to achieve any meaningful result yet.

**Comment by adammurdoch** [comment]
The bundle approach won't work on Linux though, I think.

I was actually thinking more along the lines of something closer to our JVM test infrastructure, eg inspecting the Swift classes, either the source or object files or some intermediate step, to infer which classes are test cases, and using this information in a launcher app that can run some or all of these tests.

**Comment by lacasseio** [comment]
Support on Linux is really confusing. There is two XCTest framework:
1) `XCTest.framework` installed with Xcode (macOS)
2) [`swift-corelibs-xctest`](https://github.com/apple/swift-corelibs-xctest) a drop in replacement of XCTest API (macOS and Linux)

Both have different ways of building and running.

**Comment by lacasseio** [comment]
This was delivered with https://github.com/gradle/gradle/pull/2722. Closing now.
