### ISSUE TITLE
Investigate Groovy and Kotlin DSLs for domain object containers

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#815]
Let's make a list of the current behaviors and then we can decide how to make them the same/different/etc.

----
The Kotlin DSL adds a number of conveniences for domain object containers that would also make sense for the Groovy DSL.

We should aim to make the DSLs as consistent as possible, where it makes sense to do so.

**Comment by big-guy** [comment]
Is there a list of these conveniences? /cc @eskatos @bamboo

**Comment by ghale** [comment]
This story should cover investigating the differences and deciding on a course of action for each - not implementation.

**Comment by eskatos** [comment]
As of 4.10 we have:

### Containers configuration block

Given any "property" of type `NamedDomainObjectContainer<*>` you can configure it with a block:

```java
interface Something {
  NamedDomainObjectContainer<Some> getSome();
}
```

```kotlin
something.some {
    // lambda with receiver configuring `some`
}
```

This doesn't require any `Action<T>` taking method on `Something`.

### Containers scope string invoke

The configuration block for containers as described above provides a shortcut to `named(name)` as a string invoke operator:

```kotlin
tasks {
    "someExistingName" {
        // lambda with receiver configuring the existing task lazily
    }
    "another"(SomeTaskType::class) {
        // ... 
    }
}
```

----

There's also the delegated properties (the [migration guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#configuring-tasks) demonstrate their usage). But I wonder what would be the Groovy equivalent for consistency.

**Comment by adammurdoch** [comment]
The goal isn't to make the DSLs exactly the same, but just similar where it makes sense to do so.

The first item, where a block is automatically mixed in for each property of type `NamedDomainObjectContainer` would be a good candidate for the Groovy DSL. We should also deprecate using an `Action` taking method in this case (for 6.0)

The second item, where a block is automatically mixed in (dynamically or statically) for each element is already present on the Groovy DSL, but with different semantics. We already decided this inconsistency was worth the cost.

For delegated properties, I can't see a Groovy equivalent that is worth the effort. We could probably make the pattern work in the same way we make `task foo { ... }` work, but I'm not sure why we would.

**Comment by eskatos** [comment]
In 5.0 lazy accessors to containers elements were introduced in the Kotlin DSL.

They can be used for lazy configuration:
```kotlin
plugins {
    java
}

tasks.test {  // use lazy named<Test>("test") {} under the hood
  // this is the 'test' task of type Test
}
tasks {
    test {
        // lazy configuration of the test task
    }
}
```

In the example above, `tasks.test` is a property of type `TaskProvider<Test>`. Other containers (such as `configurations`, `sourceSets`, `distributions` etc..  expose elements of type `NamedDomainObjectProvider<T>`.

It can be used to chain providers:
```kotlin
// ...
    someProperty.set(tasks.test.map { it.workingDir })
// ...
```

Or simply refer to properties by "getting" the provider:
```kotlin
// ...
    someProperty = tasks.test.get().workingDir
// ...
```

**Comment by big-guy** [comment]
As a summary...

I opened #945 for the Action taking method for container properties.  This is a common pattern in our APIs and something that a lot of third party plugins get wrong or omit.

For "Containers scope string invoke" - we have something that's roughly the same. We won't do more for Groovy.
For "delegated properties", we won't add anything special for this.
For "lazy accessors to containers elements" - I think this will just need to be a difference with the Groovy DSL since we're not going to make the Groovy DSL lazy any time soon and there are APIs we could just document as the preferred option in the future.  This is also similar to the difference with the "string invoke" case above.
