### ISSUE TITLE
Cross compiling for arm with 'c' plugin fails at linker 'cpp' plugin does nothing

### ISSUE THREAD

**Issue by eaaltonen** [gradle/gradle-native#818]
### Expected Behavior
"Hello world!" application cross compiles to arm.

### Current Behavior
With the 'c' plugin applied, building the component after calling the linker at `/usr/bin/ld`.
Compiling directly with `arm-linux-gnueabi-gcc <mysrc>` works. I also tried changing to 'cpp' plugin, but that seems to do nothing at all.

### Context
Gradle version 4.9. I tried to get a working example of cross-compiling with the below build configuration
```
apply plugin: 'c'

model {
    toolChains {
        gcc(Gcc) {
            target('arm'){
                cppCompiler.withArguments { args ->
                    args << "-m32"
                }
                linker.withArguments { args ->
                    args << "-m32"
                }
            }
        }
    }
    platforms {
        x64 {
            architecture 'x86_64'
        }
        arm {
            architecture 'arm'
        }
    }
    components {
        app(NativeExecutableSpec) {
            targetPlatform 'x64'
            targetPlatform 'arm'
        }
    }
}
```
with the code for helloworld in `src/app/c`.

### Steps to Reproduce (for bugs)
The above should be sufficient, I think.

### Your Environment
Ubuntu 16.04, I installed packages `gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi` according to
https://askubuntu.com/a/250721/62612

**Comment by lacasseio** [comment]
Thanks @eaaltonen for this question. Cross-compilation is possible with both the software model plugins (your case) and the new native plugins. You will most likely have to replace `-m32` or `-m64` by `-mthumb` for `cCompiler`, `cppCompiler`, `linker`, and `compilerProbeArgs` so Gradle discover the right headers.

Then, you need to change the `cCompiler`, `cppCompiler`, `linker` and `staticLibArchiver` executable to use the one from the cross-compilation tool chains. To do so, you would use something like `cCompiler.executable = 'gcc-arm-linux-gnueabi-gcc'` for the C compiler. You need to do the same for the other one as well. You should also use `gcc-arm-linux-gnueabi-gcc` (if building only C) or `gcc-arm-linux-gnueabi-g++` (if building C and C++) as the linker. By default, Gradle will find the default GCC for the current host and will fail in presence of any cross-compilation directive.

Putting it all together should look like this (disclaimer, I don't have cross-compilers on my machine so I can verify if the code is accurate, but it should give you a good idea on how to solve your issue):
```
apply plugin: 'c'

model {
    toolChains {
        gcc(Gcc) {
            path '/path/to/cross/toolchain/bin'
            target('arm'){
                compilerProbeArgs.removeAll(['-m32', '-m64'])
                compilerProbeArgs << '-mthumb'
                cCompiler.withArguments { args ->
                    args.removeAll(['-m32', '-m64'])
                    args << "-mthumb"
                }
                cppCompiler.withArguments { args ->
                    args.removeAll(['-m32', '-m64'])
                    args << "-mthumb"
                }
                linker.withArguments { args ->
                    args.removeAll(['-m32', '-m64'])
                    args << "-mthumb"
                }
                cCompiler.executable = 'gcc-arm-linux-gnueabi-gcc'
                cppCompiler.executable = 'gcc-arm-linux-gnueabi-g++'
                linker.executable = 'gcc-arm-linux-gnueabi-g++'
                staticLibArchiver = 'gcc-arm-linux-gnueabi-ar'
            }
        }
    }
    platforms {
        x64 {
            architecture 'x86_64'
        }
        arm {
            architecture 'arm'
        }
    }
    components {
        app(NativeExecutableSpec) {
            targetPlatform 'x64'
            targetPlatform 'arm'
        }
    }
}
```

**Comment by eaaltonen** [comment]
Thanks @lacasseio for your reply.

I tried your suggestions with the following build configuration. I have mostly set the paths and names to match the locations of the GCC arm cross compiler packages on Ubuntu.
```
apply plugin: 'c'

model {
    platforms {
        x64 {
            architecture 'x86_64'
        }
        armel {
            architecture 'armel'
        }
    }
    toolChains {
        gcc(Gcc) {
            path '/usr/bin'
            target('armel'){
                compilerProbeArgs.removeAll(['-m32', '-m64'])
                compilerProbeArgs << '-mthumb'
                cCompiler.withArguments { args ->
                    args.removeAll(['-m32', '-m64'])
                    args << "-mthumb"
                }
                cppCompiler.withArguments { args ->
                    args.removeAll(['-m32', '-m64'])
                    args << "-mthumb"
                }
                linker.withArguments { args ->
                    args.removeAll(['-m32', '-m64'])
                    //args << "-mthumb"
                }
                cCompiler.executable = 'arm-linux-gnueabi-gcc'
                cppCompiler.executable = 'arm-linux-gnueabi-g++'
                linker.executable = 'arm-none-eabi-ld'
                //staticLibArchiver = 'arm-none-eabi-ar'
            }
        }
    }
    components {
        app(NativeExecutableSpec) {
            targetPlatform 'x64'
            targetPlatform 'armel'
        }
    }
}
```

Some observations from trying this build:

1. Trying to set the `staticLibArchiver` will fail the build , as it is a read-only property for "object of type `org.gradle.nativeplatform.toolchain.internal.gcc.DefaultGccPlatformToolChain`"

2. Compiling to an object file works, however linking fails (does not fail build). Linker output below.
```
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
```

I tried linking manually by calling `arm-linux-gnueabi-ld -o output <objectfile built by Gradle> /usr/arm-linux-gnueabi/lib/crt1.o /usr/arm-linux-gnueabi/lib/libc.so /usr/arm-linux-gnueabi/lib/crti.o`

This worked, except for the paths in the binary containing `/usr/arm-linux-gnueabi/lib/crt1.o` etc. which should probably have been `/lib/crt1.o`. These files are provided by the package `libc6-armel-cross`. The paths would need fixing, but I gave up at this point due to my lack of experience in cross compiling. It would be great if the new native plugins had improved support for cross compiling.

**Comment by lacasseio** [comment]
Use `arm-none-eabi-g++` or `arm-none-eabi-gcc` as the linker instead.
