### ISSUE TITLE
Fix `ConcurrentModificationException` when using `tasks.withType(ScalaCompile::class.java).configureEach`

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#834]
See https://github.com/gradle/gradle/issues/6558

**Comment by big-guy** [comment]
This appears to be something specific to the Scala plugin, but it's probably also going to be a common misfeature of other plugins.  We should try to make this work and have a safer pattern to recommend.  It's effectively doing something like:

```
allprojects {
   tasks.withType(ScalaCompile).configureEach {
      allprojects {
         for (ScalaCompile task : tasks.withType(ScalaCompile)) {
             // build map
         }
         rootProject.ext.scalaCompileAnalysisMap = map
      }
      // configure some specific properties of this task based on the map above
   }
}
```

I think this is saying "to configure ScalaCompile tasks, we must configure all the ScalaCompile tasks...".  It looks like we don't actually need any of the information until execution time, so it would make sense to try to defer some of this until then.

**Comment by big-guy** [comment]
PR: https://github.com/gradle/gradle/pull/6646
