### ISSUE TITLE
Native Build Flags Not Passed to Compiler/Linker as expected

### ISSUE THREAD

**Issue by brandon-mckenzie** [gradle/gradle-native#844]
Based on lack of response to the corresponding [help thread](https://discuss.gradle.org/t/native-build-flags-not-passed-to-compiler-linker-as-expected/28523), and behavior contrary to what has been documented, I'm following up on this as a bug.

I am attempting to build a C++ demo that involves multiple threads, which would necessitate the `-pthread` flag being passed to GCC. 

### Expected Behavior
` -pthread` parameter is been passed to my toolchain, gcc specifically.

### Current Behavior
Instead, the build fails with error `undefined reference to 'pthread_create'`, indicative of the appropriate flags not passing. Additionally, the flag is not appearing in options.txt for the Linker or Compiler as expected, providing further evidence indicating the flag did not get passed.

### Context
C++ multithreaded applications taking advantage POSIX thread libraries are impossible to build with Gradle, as that flag is required for such an application.  I was considering adopting Gradle for a multithreaded server/logging application, but this bug renders that prospect impossible.  I had high hopes for this, as we have a mixed language team (mostly C++ and Java), and having the same build management tools for everything we work with was an attractive idea, especially as I was already familiar with Gradle prior experience in Java development.

### Steps to Reproduce (for bugs)

Create project with below files:

` build.gradle`:

```groovy
plugins {
    id 'cpp-application'
}

model {
    binaries {
        all {
            if(toolChain in Gcc) {
                cppCompiler.args "-pthread" \\, "-lstdc++" <- Also tried adding this
                linker.args "-pthread" \\, "lstdc++" <- Also tried adding this
            }
        }
    } 
}
```

`main.cpp`:

```c++
#include<thread>
#include<chrono>
#include<iostream>
using namespace std;

int main(int argc, char** argv) {
    thread t1([](){this_thread::sleep_for(chrono::seconds(1)); cout << "t1\n";});
    thread t2([](){std::cout << "t2\n";});
    t1.join();
    t2.join();
    return 0;
}
```
Execute `gradle build`.  Met with a Linker failure due to missing pthread flag.
Note that `gcc -lstdc++ -pthread src/main/cpp/main.cpp -o test` from project root ran perfectly on the same code.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/wbao3zu2tnjfo

**Comment by big-guy** [comment]
Hi @brandon-mckenzie,

Sorry, you've tripped over some work-in-progress.  The `cpp-application` and `cpp-library` plugins are for the [new C++ plugins](https://blog.gradle.org/introducing-the-new-cpp-plugins), while the user guide only talks about the software model based plugins (aka the "old" plugins). The `model {}` API/configuration is only for those plugins, while the new plugins use an API that's more similar to Gradle's longstanding Java plugins.

In your example, `cpp-application` doesn't look at any of the configuration in the `model {}` block.

Here's a sample of adding `-pthread` to all test executables link tasks:
https://github.com/gradle/native-samples/blob/6fbae41974772123a847071d4fa6be861d316b00/cpp/library-with-tests/build.gradle

This is a bit in flux, but the samples here are kept up-to-date.  Here's the instructions for running that sample: https://github.com/gradle/native-samples#libraries-with-tests-library-with-tests

Thanks for your interest!
