### ISSUE TITLE
SSH Config For Source Dependencies? 

### ISSUE THREAD

**Issue by jamespedwards42** [gradle/gradle-native#863]
I am able to configure and build against public SSH repositories from Github.  However, when I try to configure a private repository hosted by Gitlab I get the following root cause exception.  

```
Caused by: com.jcraft.jsch.JSchException: UnknownHostKey: gitlab.com. RSA key fingerprint is b6:03:0e:39:97:9e:d0:e7:24:ce:a3:77:3e:01:42:09
        at com.jcraft.jsch.Session.checkHost(Session.java:805)
        at com.jcraft.jsch.Session.connect(Session.java:345)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:117)
        ... 158 more
```

I develop locally against this private repository and double checked that I don't currently have any issues accessing it by cloning it again.  Apologies if this is a duplicate of https://github.com/gradle/gradle-native/issues/842, but it felt like a separate issue, not sure.

For the settings.gradle file below, the configuration for the public  project, `json-iterator`, works, but fails for the other.  Is there any additional configuration that needs to be provided?

settings.gradle: 
```
sourceControl {
  gitRepository('ssh://git@github.com/comodal/json-iterator.git') {
    producesModule("systems.comodal:json-iterator")
  }
  gitRepository('ssh://git@gitlab.com/<ORG>/<PROJECT>.git') {
    producesModule("<ORG>:<PROJECT>")
  }
}
```

SSH config (`~/.ssh/config`):
```
Host gitlab.com
IdentityFile ~/.ssh/gitlab_id_rsa
IdentitiesOnly yes
```

**Comment by ghale** [comment]
It's likely the same issue as #842.  You can validate by checking the key entry for gitlab.com in `~/.ssh/known_hosts`.  If the only key(s) for gitlab.com have a type starting with `ecdsa`, then that's probably it.  You should be able to workaround by adding the rsa key to known_hosts:
```
ssh-keyscan -H -t rsa gitlab.com >> ~/.ssh/known_hosts
```

**Comment by jamespedwards42** [comment]
@ghale Thank you  :) that workaround did fix it.
