### ISSUE TITLE
two files to specify dependency: one version range, other fixed version

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle-native#872]
npm with the features "npm ci" and facebooks yarn introduced a feature to have two files for dependencies. one targetted for development on the personal workspace having a version range, and one for continuous and release builds having a fixed version number, see https://yarnpkg.com/lang/en/docs/cli/upgrade/.

can gradle provide a similar feature please? for both, binary or source code dependencies.

**Comment by big-guy** [comment]
Hi @soloturn, 

You get something similar with Gradle's [dependency locking](https://docs.gradle.org/nightly/userguide/dependency_locking.html#header).  Dependency ranges are in your `build.gradle` and a separate lock file is generated to pin versions.

This doesn't work for source dependencies yet, but that's our intention.
