### ISSUE TITLE
Gradle can checkout a git repository from the Maven to VCS Map

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-native#88]
Gradle can check out a git repository as part of satisfying a dependency and add it as an implicit included build to the consuming project. This allows users to specify a VCS mapping from Maven Coordinate to a git VCS repository specification for an existing Gradle build, and then build that project from sources using composite builds.

**Comment by adammurdoch** [comment]
Should we call out git specifically? We don't want to support anything else yet, I think.

**Comment by eljobe** [comment]
Good point @adammurdoch. I've added git to both the title and the description of this issue.

**Comment by eljobe** [comment]
Started working on this here: https://github.com/gradle/gradle/pull/2886

**Comment by eljobe** [comment]
We're adding a little bit more to this interface to enable the `VcsDependencyResolver` to ask the `VersionControlSystem` what versions it has for a particular dependency. You can follow-along on gradle/gradle#3034

**Comment by eljobe** [comment]
I'm making really good progress today on this. Here's what I've done so far (but not pushed to the branch):
  * Split `GitVersionControlSpec` into an interface an implementation
  * Added tests for `DefaultGitVersionControlSpec`
  * Added methods on our test fixture for creating tags and branches
  * Written a functional test for the `GetVersionControlSystem.getAvailableVersions()`
      * This test is now failing because the implementation hasn't been created yet. I am **not** blocked. I know just how to proceed.

I'm now going to take a long lunch to enjoy some time on the beach. But, I'll be back in about 2.5 hours and working extra-late tonight. So, I might be up for some more pairing with @big-guy

**Comment by eljobe** [comment]
This is now making its way through branch verification on CI: https://builds.gradle.org/viewQueued.html?itemId=8403858&tab=queuedBuildOverviewTab
