### ISSUE TITLE
Fix deprecation warnings in Android plugin

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#885]
We're getting some deprecation warnings with the Android plugin in 5.0 when getting the IDE model using the tooling API due to configuration resolution without the project lock.  We should probably disable the mutation checks any time we're doing something other than a build.

**Comment by big-guy** [comment]
lenient locking or whatever we talked about

**Comment by big-guy** [comment]
only fix the tooling model builders

**Comment by ghale** [comment]
PR https://github.com/gradle/gradle/pull/7308
