### ISSUE TITLE
Gradle no longer support proper location of artifacts when multiple repositories is provided

### ISSUE THREAD

**Issue by faiyat** [gradle/gradle-native#889]
Gradle allow to specify multiple repositories for dependency resolution.  However, it always tries to look for all dependencies in the first repository.  If fail the build immediately if it couldn't find it there, instead of searching through all the repositories.

### Expected Behavior
It should continue to search all repositories if it couldn't find in the first one, then second, etc.  The build should only fail after all repositories have been searched and not find in any of them.

### Current Behavior
The artifact exists in the 2nd repository.  But the build failed immediately after it fail to find it in the 1st one.

### Context
We use nexus to store our internally created artifacts.  We also proxy'd all public repositories in nexus as well, such as maven central, cloudera, etc.  In the repositories closure of gradle, we provided multiple urls to each of these repositories, internal or proxy'd.   And we expect Gradle to search in all of them before declare an artifact is not found.  

Following is a snippet from our build script.  turn, turn_test are internal repositories that store artifacts created in house; while central, cloudera are proxies to public repositories.  Snapshots is our internal snapshot repositories.

    repositories {
    	        maven {
    		      url 'http://maven.turn.com/service/local/repositories/turn/content/'
    	        }
                maven {
                      url 'http://maven.turn.com/service/local/repositories/central/content/'
                }        		
		maven {
			url 'http://maven.turn.com/service/local/repositories/snapshots/content/'
		}
		maven {
			url 'http://maven.turn.com/service/local/repositories/turn_test/content/'
		}		
		maven {
			url 'http://maven.turn.com/service/local/repositories/cloudera/content/'
		}	
    }

### Steps to Reproduce (for bugs)
In our dependencies closure, one of the dependencies is:
compile "org.codehaus.groovy:groovy-all:$groovyVersion.+"

When build executed, we are getting the following error:

00:02:07.554 > Could not resolve org.codehaus.groovy:groovy-all:2.3.+.
00:02:07.554   Required by:
00:02:07.554       project :modules:kvstore
00:02:07.554    > Failed to list versions for org.codehaus.groovy:groovy-all.
00:02:07.554       > Unable to load Maven meta-data from http://maven.turn.com/service/local/repositories/turn/content/org/codehaus/groovy/groovy-all/maven-metadata.xml.
00:02:07.554          > Could not get resource 'http://maven.turn.com/service/local/repositories/turn/content/org/codehaus/groovy/groovy-all/maven-metadata.xml'.
00:02:07.555             > Could not GET 'http://maven.turn.com/service/local/repositories/turn/content/org/codehaus/groovy/groovy-all/maven-metadata.xml'.
00:02:07.555                > Read timed out

where the groovy-all artifact is available in maven central.  But it exited after failed to find it in turn repository.

### Your Environment
We have Gradle 4.5.1.  Java 1.80.  We are using nexus to store our artifacts.

**Comment by big-guy** [comment]
Issue moved to [gradle/gradle #7336](https://github.com/gradle/gradle/issues/7336) via [**ZenHub**](https://www.zenhub.com/)
