### ISSUE TITLE
Fix deprecation warnings in Gradle build

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#890]
With the single project lock work, we have surfaced some instances in the gradle build where we are doing cross-project configuration resolution and are throwing deprecation warnings.  We should investigate where we're doing this and fix them.

**Comment by ghale** [comment]
Looks like the deprecations fall into three usages that are all the same sort of thing:
- checkBinaryCompatibility adds configurations from other projects directly to its inputs [here](https://github.com/gradle/gradle/blob/65b82cf3b4d63b5dbbd5f0e18373286667e36566/subprojects/distributions/binary-compatibility.gradle#L109)
- generateGradleApiPackageList adds configurations from other projects directly to its inputs [here](https://github.com/gradle/gradle/blob/23a23bdd36c53423e17b7ed2dcfd32d9418c0c82/subprojects/runtime-api-info/runtime-api-info.gradle.kts#L30)
- javadocAll adds file collections from other projects (that are backed by configurations) directly to its inputs [here]( https://github.com/gradle/gradle/blob/80c82374aa5c108c1e0052de1f64ec83f1b42855/subprojects/docs/docs.gradle#L274)

**Comment by ghale** [comment]
One more (same sort of thing):
- apiMetadata adds configurations from the root project directly to its inputs [here](https://github.com/gradle/gradle/blob/e9b85bb0e2a703a08291df8aadc2efd3d4efba58/subprojects/api-metadata/api-metadata.gradle.kts#L19)

**Comment by lacasseio** [comment]
`checkBinaryCompatibility` is fixed in this PR: https://github.com/gradle/gradle/pull/7407

**Comment by big-guy** [comment]
@lacasseio I merged PR 7407 above into master, but we probably want to put these all on release first so we don't have any surprises with a 5.0 nightly

**Comment by lacasseio** [comment]
`generateGradleApiPackageList` is fixed in this PR: https://github.com/gradle/gradle/pull/7433

**Comment by lacasseio** [comment]
I will cherry-pick the commit inside release.

**Comment by big-guy** [comment]
@lacasseio I cherry-picked it already, should have told you when we were chatting

**Comment by lacasseio** [comment]
`javadocAll` is fixed in this PR: https://github.com/gradle/gradle/pull/7450
