### ISSUE TITLE
Source Dependencies: Wired/Unnecessary `version {}` block

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle-native#895]
I just read and test a little bit with the [`source dependencies`](https://blog.gradle.org/introducing-source-dependencies) feature.

While the syntax for the "git-tag as version" makes sense to me:
```groovy
implementation 'org.gradle.cpp-samples:utilities:1.0'
```
the syntax for "other branches" does not:
```groovy
dependencies {
    implementation('org.gradle.cpp-samples:utilities') {
        version {
            branch = 'release'
        }
    }
}
```

### Expected Behavior
Branches (and maybe git-hashes (see #883 )) can be used as "normal gradle version":
```groovy
implementation 'org.gradle.cpp-samples:utilities:[TAG,BRANCH OR HASH]'
```

Users may be confused about the new syntax (the `version{}` block) they have to use.
Because a BRANCH or HASH would specify the version of the dependency.

### Current Behavior
We have to add a `version {}` block to the configuration/dependency which defines the version of the dependency.

**Comment by big-guy** [comment]
This is intentional. This is part of some other work for defining version constraints that represent how that version should be interpreted.
