### ISSUE TITLE
Investigate why dependency resolution blocks while resolving metadata from project dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#897]

**Comment by adammurdoch** [comment]
To reproduce this, run `./gradlew userguide javadocAll` on the `gradle/gradle` build. You can see on the console a bunch of `classpathManifest` tasks blocked waiting to resolve dependencies of the `runtimeClasspath` configuration while `docs:userguideSinglePage` is running (and which is _really_ slow for some reason).

**Comment by adammurdoch** [comment]
Looking at the thread dump, it seems the worker threads for these tasks are down in `ProjectDependencyResolver.resolveArtifacts()` waiting to acquire a mutation lock on a project. So It seems that the metadata construction is actually ok, at least in this scenario, but the problem lies with resolving the artifacts for the target project + configuration.

**Comment by lacasseio** [comment]
I don't know if this is related to this issue but I'm getting a deadlock using latest master and a source dependency. The build lock when compiling the `buildSrc` of the source project. To reproduce you can checkout the [lacasseio/exemplar branch](https://github.com/lacasseio/vscode-gradle-plugin/tree/lacasseio/exemplar) and just try to build the project. I got the following [thread dump](https://github.com/gradle/gradle-native/files/2483697/threads_report.txt).

**Comment by big-guy** [comment]
@lacasseio can you open this as an issue on gradle/gradle and assign it to 5.0RC1?

**Comment by ghale** [comment]
I've created https://github.com/gradle/gradle-native/issues/899 to capture the issue above.

**Comment by adammurdoch** [comment]
Split out #903 and #904 based on the investigation. Closing this issue.
