### ISSUE TITLE
Fix deadlock issue when source dependency has buildSrc

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#899]
https://github.com/lacasseio/vscode-gradle-plugin/tree/lacasseio/exemplar has a source dependency on https://github.com/gradle/exemplar, which has a buildSrc.  With the single project lock, this causes the buildSrc project to be built [here](https://github.com/gradle/gradle/blob/f974085dcdae21a3737661b016335f9ef5935ba6/subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProjectStateRegistry.java#L57) while the project state registry lock is being held.  This then creates a deadlock while the buildSrc build executes.

**Comment by ghale** [comment]
PR https://github.com/gradle/gradle/pull/7411

@lacasseio I verified that it fixes the issue with vscode-gradle-plugin - can you take a look at ☝️ ?

**Comment by lacasseio** [comment]
Looks good, Sterling already reviewed it and merged it. I merged release in master so I will close the issue.
