### ISSUE TITLE
Unit testing support for architecture variants

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#917]
Split off from #777

**Comment by big-guy** [comment]
What are the defaults for a unit test component WRT architecture and the main component has architecture specified?

specified for both?

different/incompatible architectures between test component and main component.

we can mostly assume happy path case.

**Comment by ghale** [comment]
Some comments on test coverage:
https://github.com/gradle/gradle/pull/7545#discussion_r229186454
https://github.com/gradle/gradle/pull/7545#discussion_r229186673

**Comment by ghale** [comment]
PR for fixing native unit tests on Xcode 10: https://github.com/gradle/gradle/pull/7956

PR for adding architecture support for unit tests: https://github.com/gradle/gradle/pull/7960
