### ISSUE TITLE
Native import via Tooling API for build with varied operating system and architecture

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#919]
### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment]
For this issue, I added test coverage for libraries and application: https://github.com/gradle/gradle/pull/8090

I'm unsure how we want to expose the architecture name and operating system as they both not used by anyone or anything really. Clion behaves properly with the current tooling API.

**Comment by big-guy** [comment]
I think the other important thing to check here is what happens when you have a project that targets multiple OSes or does not target the host.

- Do you see all of the choices? I think you don't/shouldn't.
- If the project does not target the host OS, do you have any choices? Can it be imported at all? I think it would make sense to not be able to see the non-host choices, but I think you should be able to import the project and it would just show up as empty (I think).

**Comment by adammurdoch** [comment]
The answers to these questions should be the same for all IDE integrations, that is for Xcode, VS, tapi, and whatever we add later. So, if we add some tests for this for the tapi model, perhaps also add the same tests for Xcode and VS.

**Comment by lacasseio** [comment]
The answer to the questions are:

> - Do you see all of the choices? I think you don't/shouldn't.
Partly, if the operating system match, then we try to "realize" all the architecture for the specific operating system. If the architecture isn't buildable by any toolchain, the import will simply fail. Any operating system that isn't the current host is ignored.

> If the project does not target the host OS, do you have any choices?
If there aren't any buildable options, nothing is shown in Clion. The import succeeds but shows nothing can be built.

To answer's @adammurdoch questions, the experience is no the same for Xcode with regards to the first question. The IDE plugin creates a bit of a broken Xcode workspace. I haven't try VS. We should address this as a separate issue. There's already some overlapping issue with this work on the board. Let's stick for this one to add the test coverage and fix anything deeper than the test coverage as part of another issue.
