### ISSUE TITLE
Demonstrate how to depend on a particular variant of a library

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#923]
Given a library that builds both shared and static versions, how does a consuming build specify that they want shared or static.  This may not be easy to do now, but we should demonstrate how this can be done.

**Comment by k-mack** [comment]
I think #1017 discusses this --- specifically, [this comment](https://github.com/gradle/gradle-native/issues/1017#issuecomment-556150296).

**Comment by lacasseio** [comment]
Thanks @k-mack for helping pointing out duplicate. Let's favor the other issue given it has more context.
