### ISSUE TITLE
Do not expose native plugin services in Gradle core APIs

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#927]
The `TargetMachine` concept shouldn't be visible from a project that doesn't have one of the native plugins applied.

Instead these types should and factories should be made visible in the usual way that a plugin would add things to the project. `Project.getMachines()` should be replaced by a project extension that is added by the native plugins. The related types should live in platform-native project rather than core-api:

- `MachineArchitecture`
- `OperatingSystemFamily`
- `TargetMachine`
- `TargetMachineFactory`

Also dependencyManagement project should not declare any dependency on platformNative.

**Comment by lacasseio** [comment]
PR available here: https://github.com/gradle/gradle/pull/7778
