### ISSUE TITLE
Do not add the host as a target machine when any target machines have been defined for a native component

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#928]
When I have this in a build script:

```
application {
    targetMachines.add(machines.windows())
}
```

then I end up with 2 variants: one for windows and one for the host. We should make this less confusing. Arguably, it's a usability issue with `SetProperty`, but it should probably also be an error to have target machines contain the implicit host target machine and any other value, regardless of how the values end up in the set.

**Comment by lacasseio** [comment]
PR https://github.com/gradle/gradle/pull/7801 remove `TargetMachineFactory#host()` from public API and use an ad-hoc default value configuration on the `targetMachines` property.

**Comment by lacasseio** [comment]
A similar issue yet different is handled in PR https://github.com/gradle/gradle-native/issues/944.
