### ISSUE TITLE
Detangle XCTest from JVM testing infrastructure 

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#93]
- [ ] Change dependency between `testing-native` to depend on `testing-base` instead of `testing-jvm`

**Comment by eljobe** [comment]
This card says it is in "Reviewing", but it doesn't have an author. Where is the review happening? Was it on gradle/gradle#3234

**Comment by lacasseio** [comment]
My bad for not adding myself to it. It's basically the detanglement of the native testing from JVM testing. The idea was to start with a design document then move forward with the modification but the work happened faster during the meetup. I will edit the title and close the issue.

**Comment by lacasseio** [comment]
Actually, I'm not going to close this now and there was some leftover comment to address and I would prefer fixing them now before closing this issue. A branch is almost ready for review, then we can close this issue.

**Comment by lacasseio** [comment]
This was completed by PR https://github.com/gradle/gradle/pull/3289.
