### ISSUE TITLE
Binaries on Linux should be relocatable within the install package

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#930]
### Expected Behavior

Test coverage showing that once an application is installed the original binaries can be deleted while keeping the installed application working.

Moreover, the binaries fetched from cache should work when installed in a different location.

### Current Behavior

macOS handle relocation even though we have absolute paths in the binary. However, Linux is true to the absolute path and will fail if the original binaries can't be found.

### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/gradle/pull/6176 contains what needs to be fixed.

**Comment by big-guy** [comment]
@lacasseio I left comments on the PR
