### ISSUE TITLE
Libraries that target macOS and published with older versions of Gradle should be resolved correctly

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#943]
It looks like we recently changed the value of the 'operating system' attribute on macOS, meaning that libraries published with older versions cannot be resolved any more as the values no longer match.

We might just document with the breakage, or change the value back or add a compatibility rule to say 'macos' is ok to use when 'macOS' has been requested.

**Comment by big-guy** [comment]
We'll change it back since it doesn't really matter.

**Comment by big-guy** [comment]
@adammurdoch does it make sense that String attributes are case sensitive?
