### ISSUE TITLE
Visual Studio IDE integration breaks C++17 intellisense on VS2017

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#975]
Intellisense for C++17 features were reported to not function properly with solution generated with Gradle opened on Visual Studio 2017.

**Comment by lacasseio** [comment]
One thing to check before debugging this further is to see if `/std:c++17` flag is added to the command line which is most likely used within Intellisense build.

**Comment by big-guy** [comment]
We need more investigation here

**Comment by lacasseio** [comment]
I can confirm the issue, this will be fixed in 6.0: https://github.com/gradle/gradle/pull/10493
