### ISSUE TITLE
Investigate Visual Studio 2019 support effort

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#976]
Visual Studio 2019 IDE preview is available and support should be added to Gradle. A quick read through the [release note](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview) doesn't show anything surprising and it should be pretty trivial to detect the new tool chain.

**Comment by lacasseio** [comment]
According to the preview image on Appveyor, [Visual Studio 2019 Preview can be used without any change to Gradle](https://ci.appveyor.com/api/buildjobs/2eqph9081w5egdmr/log) by configuring the `VisualCpp` tool chain `installDir` directly:
```
model {
    toolChains {
        vs2019(VisualCpp) {
            installDir "C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview"
        }
    }
}
```

Gradle could find the preview version automatically [if we pass the `-prerelease` flag to `vswhere.exe`](https://ci.appveyor.com/project/lacasseio/gradle-vs2019#L97). I don't suggest making this the default. Instead, I feel that manually configuring the tool chain is perfectly acceptable due to the preview nature of the tool chain.

The next step would be to install Visual Studio 2019 preview and add code coverage to Gradle making sure we still use 2017 in the quick feedback and 2019 preview in the full coverage.

**Comment by big-guy** [comment]
We should find out when we expect VS2019 to be released.

**Comment by lacasseio** [comment]
Visual Studio 2019 is expected to be released in March or April.

**Comment by ThadHouse** [comment]
It was announced that 2019 would be release on April 2. 

https://visualstudio.microsoft.com/vs2019-launch/

It would be nice to have this ready pretty quickly after that.

**Comment by big-guy** [comment]
I think what Daniel found was if VS2019 was a "final" release, we would just automatically find it and use it.  Is that right @lacasseio ?

**Comment by lacasseio** [comment]
Yes, we will see if we can set up some sort of automation to test against the preview version. On first try, it seems to be working properly.

**Comment by lacasseio** [comment]
As expected, because we now use the vswhere tool, VS2019 is properly detected: https://ci.appveyor.com/project/lacasseio/gradle-vs2019/builds/27231954

**Comment by lacasseio** [comment]
Let's focus on installing VS2019 on CI.
