### ISSUE TITLE
Improve support for Intellisense of unbuildable components inside Visual Studio and Xcode

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#980]
Given we don't create a binary model for unbuildable configuration, we don't have access to the correct include path, etc. It causes unbuildable configuration to have incomplete information to provide the right Intellisense information.

This work should focus on finding a way to dissociate the calculation of the binary include path and such from the binary implementation.

**Comment by big-guy** [comment]
dupe #977
