### ISSUE TITLE
Developer builds separate debuggable and releasable binaries for a Swift executable or library

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#99]
Add some initial support for build types, allowing the developer to build either debuggable or releasable binaries, or both, for a Swift component. For this story, the set of build types will be hard-coded, so that build types cannot be added or removed. Support for adding adding and removing build types will be added later.

Allow build logic to define separate compiler arguments each build type. For this story, this support can happen at the compile task level, instead of adding some high level modelling. Both build types will share the same source files, dependencies and other settings beyond compiler arguments.

When building a debuggable binary, the debuggable binary of each library consumed by that binary must be used. And when building a releasable binary, the releasable binary of each library must be used. This should respect configuration changes to the output locations of each binary.

The `assemble` task will build the debuggable binaries, the `check` task will test the debuggable binaries. XCTest integration will test only the debuggable binaries, for this story.

Xcode file generation should make both build types visible to the developer in Xcode, selecting the debuggable binaries by default.

Implementation:

- [x] `assemble` and `check` use the debug variant and not the release variant.
- [x] selects correct variant for dependency resolution.
- [x] enable debugging for debug variant, optimization for release variant by default.
- [x] can set command-line args for each variant.
- [x] xcode sees each variant.
- [x] remove variant specific settings from the component APIs.
- [x] developer installs the release variant
- [x] DSL decoration of binary model objects
- [x] samples are updated

Later:

- [ ] lifecycle task for each variant.
- [ ] developer discovers lifecycle tasks (eg has description, group, etc)
- [ ] address duplication in the C++ and Swift implementations.
- [ ] public APIs to reuse tasks, binary model, component model.
- [ ] public APIs to extend binary model, component model.

**Comment by adammurdoch** [comment]
This is done for now. Split out #140 and #141 for later improvements.

**Comment by eljobe** [comment]
One thing I miss in our current process is a link between this closed issue and the corresponding implementation pull request or commits. I think we should make a habit of linking the commits with the issues they contribute toward with commit message references, or by just dumping links to the commits or pull requests into the issue as we are closing it.
