### ISSUE TITLE
Gradle Dependency Issue 

### ISSUE THREAD

**Issue by diamondiona** [gradle/gradle-native#998]
[MessageBrokerGradlePlugin.zip](https://github.com/gradle/gradle-native/files/2961874/MessageBrokerGradlePlugin.zip)

I'm building "build.gradle" according to this document:
http://ajoberstar.org/grgit/index.html

For some reason, it didn't load grgit jar.

Here is the build.gradle:

plugins {
id 'groovy'
}

repositories {
jcenter()

}

dependencies {
implementation gradleApi()
implementation localGroovy()
//implementation files('libs/grgit-core-3.0.0.jar')
//implementation fileTree(dir: 'libs', include: ['.jar'])
//implementation fileTree(dir: 'libs', include: ['.jar'])
//compile group:'org.ajoberstar.grgit', name : 'grgit-core', version : '3.0.0-beta.1'
compile 'org.ajoberstar.grgit:grgit-core:3.0.0'

}

sourceSets {
main {
groovy {
srcDirs = ['buildSrc/src/main/groovy']
}
}
}

Here is the error:
C:\work\MessageBrokerGradlePlugin>gradlew build
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy
startup failed:
C:\work\MessageBrokerGradlePlugin\buildSrc\src\main\groovy\ca\cooperators\mb\tasks\CloneGitRepoTask.groovy: 10: unable to resolve class org.ajoberstar.grgit.Branch
@ line 10, column 1.
import org.ajoberstar.grgit.Branch
^

1 error

:buildSrc:compileGroovy FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
Compilation failed; see the compiler error output for details.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 4.463 secs

**Comment by lacasseio** [comment]
This issue board is for any issue related to the native ecosystem of Gradle. Please use the [Gradle forum](https://discuss.gradle.org/) for any questions about using Gradle.
